### ISSUE TITLE
audio-desync

### ISSUE THREAD

**Issue by SkalskiP** [s0md3v/roop#10]
Hi 👋🏻 As discussed on [Twitter](https://twitter.com/s0md3v/status/1663100597736968192?s=20), I'm uploading input image + video and output video. 

https://github.com/s0md3v/roop/assets/26109316/86eb733a-2843-43e0-a58c-e36b3833e087

![photo_2023-05-29 11 16 01](https://github.com/s0md3v/roop/assets/26109316/cc2cc39e-0034-4ae2-8507-f88d4aa37d5f)

https://github.com/s0md3v/roop/assets/26109316/e43be6d6-97a7-4423-80db-127669c95f42

**Comment by s0md3v** [comment]
I tried it.

Looks like this is a ffmpeg/fps issue. The input file shows a length of `00:23` in VLC (and the file you uploaded) and output file is `00:24`.

All roop does is to extract the frames and replace them one by one. It uses `ffmpeg` to do the extraction, applying audio and combining frames to create the video.

I have never encountered this desync issue before. I'll get back to it after making the GUI a bit-friendly. Thanks for the heads-up.

**Comment by kmskrishna** [comment]
Have to say, the face swap on Ellie made me chuckle.

**Comment by teebu** [comment]
I'm facing the same issue with audio sync. src video is 16 sec, output is 17. 

note: ignoring the output quality, sync is the topic at hand.

https://github.com/s0md3v/roop/assets/5531844/74f3f1e2-90aa-4ff4-b4c3-97d76b452b34


https://github.com/s0md3v/roop/assets/5531844/d336f108-1139-423e-b6a7-ba63b6d6a8c9

**Comment by xaviviro** [comment]
https://github.com/s0md3v/roop/pull/101

**Comment by henryruhs** [comment]
Should be resolved as of #101
