### ISSUE TITLE
Running run.py and nothing happens

### ISSUE THREAD

**Issue by nseq** [s0md3v/roop#100]
Here's what I did, I'm trying to run this on Kaggle notebook with GPU T4, it doesn't have onnxruntime or onnxruntime-gpu installed, I did download inswapper_128.onnx to roop folder
```
!pip uninstall -y torch torchvision torchaudio
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
!pip install -r requirements.txt
!pip install onnxruntime-gpu
```
Then I run
`!python run.py --gpu --keep-fps -f /kaggle/working/aidka.jpg -t /kaggle/working/video.mp4 -o /kaggle/working/test.mp4`
It downloads this file:
```
download_path: /root/.insightface/models/buffalo_l
Downloading /root/.insightface/models/buffalo_l.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip...
100%|████████████████████████████████| 281857/281857 [00:06<00:00, 40519.35KB/s]
```
and it just stops after this, nothing happens, no errors, just nothing. Need help

**Comment by henryruhs** [comment]
You are using absolute paths... layer 8 problem here

**Comment by nseq** [comment]
lmao you are right, I didn't even notice this:
-f SOURCE_IMG, --face SOURCE_IMG
                        use this face
-t TARGET_PATH, --target TARGET_PATH
                        replace this face
-o OUTPUT_FILE, --output OUTPUT_FILE

**Comment by nseq** [comment]
> You are using absolute paths... layer 8 problem here

Okay, I dropped all my files inside the dir where run.py is and running this
`!python run.py --gpu --keep-fps -f aidka.jpg -t video.mp4 -o test.mp4`
it still doesn't work, nothing happens

additional info: running without `--gpu` works fine

**Comment by henryruhs** [comment]
Feel free to open a pull request, we could need the help

**Comment by nseq** [comment]
I didn't change anything in OP... All I did was I accidentally closed the issue and then reopenned it, sorry

**Comment by henryruhs** [comment]
Try discord for help
