### ISSUE TITLE
stuck in processing

### ISSUE THREAD

**Issue by Prisoner2-6-7** [s0md3v/roop#107]
/usr/local/lib/python3.11/dist-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.                                                                          To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.                 P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4                                                                                        /usr/local/lib/python3.11/dist-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.                                                                          To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.                 P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4                                                                                        /usr/local/lib/python3.11/dist-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.                                                                          To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.                 P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4                                                                                        /usr/local/lib/python3.11/dist-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.                                                                          To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.                 P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4                                                                                        /usr/local/lib/python3.11/dist-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.                                                                          To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.                 P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4                                                                                        /usr/local/lib/python3.11/dist-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.                                                                          To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.                 P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4

**Comment by s0md3v** [comment]
It's not stuck. These are just logs, not errors. Its working fine.
