### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by taladro** [s0md3v/roop#11]
Before the first run I get this error:

   running build_ext
      building 'insightface.thirdparty.face3d.mesh.cython.mesh_core_cython' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

**Comment by s0md3v** [comment]
As the error suggests, you need to install "Microsoft Visual C++ 14.0". It even has a link in the error.
