### ISSUE TITLE
No module named "onnxruntime"

### ISSUE THREAD

**Issue by qwsazi** [s0md3v/roop#112]
Error:

qwsazx@qwsazx:~/roop$ python3 run.py
Traceback (most recent call last):
  File "/home/qwsazx/roop/run.py", line 5, in <module>
    import core.globals
  File "/home/qwsazx/roop/core/globals.py", line 1, in <module>
    import onnxruntime
ModuleNotFoundError: No module named 'onnxruntime'

I've completed installation, but after python3 run.py this returns

**Comment by Moeblack** [comment]
`pip install onnxruntime-gpu`

**Comment by qwsazi** [comment]
Oh, I'm stupid. 
pip install onnxruntime solves this
