### ISSUE TITLE
ffmpeg is not installed. Read the docs: https://github.com/s0md3v/roop#installation.

### ISSUE THREAD

**Issue by joerude** [s0md3v/roop#116]
**Describe the bug**

I have made `pip install -r requirements.txt`

Firstly I got `ModuleNotFoundError: No module named 'onnxruntime'`
After installing **onnxruntime** via `pip install onnxruntime` and `pip install onnxruntime-gpu`

Now I got

>>> python run.py 
```bash

ffmpeg is not installed. Read the docs: https://github.com/s0md3v/roop#installation.
ffmpeg is not installed. Read the docs: https://github.com/s0md3v/roop#installation.
ffmpeg is not installed. Read the docs: https://github.com/s0md3v/roop#installation.
ffmpeg is not installed. Read the docs: https://github.com/s0md3v/roop#installation.
ffmpeg is not installed. Read the docs: https://github.com/s0md3v/roop#installation.
ffmpeg is not installed. Read the docs: https://github.com/s0md3v/roop#installation.
ffmpeg is not installed. Read the docs: https://github.com/s0md3v/roop#installation.
ffmpeg is not installed. Read the docs: https://github.com/s0md3v/roop#installation.
ffmpeg is not installed. Read the docs: https://github.com/s0md3v/roop#installation.
ffmpeg is not installed. Read the docs: https://github.com/s0md3v/roop#installation.

```

**Details**
What OS are you using?
- [x] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you try to use a GPU?
- [x] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [x] I have the latest code from the github repository
- [ ] I have followed the installation guide

**Comment by Noelemahc7** [comment]
1) Did you install FFMPEG?
2) On Windows this includes including it into system paths, did you do the Linux equivalent?

**Comment by henryruhs** [comment]
Sorry but I close this without ceremony.
