### ISSUE TITLE
[Feature Request] Videos with multiple people

### ISSUE THREAD

**Issue by bbecausereasonss** [s0md3v/roop#117]
We need a way to signify which face/quadrant for videos with multiple people

As described we need a way to suggest which face to replace if a video has more than one person. ie) Segment everything?

**Comment by 132world** [comment]
> This is definitely possible and is a planned feature.

we also need the option to replace all the faces in the video with the same source face. This is necessary for VR videos.

**Comment by Mayorc1978** [comment]
> > This is definitely possible and is a planned feature.
> 
> we also need the option to replace all the faces in the video with the same source face. This is necessary for VR videos.

Aren't faces distorted in VR videos? Wouldn't that make difficult to replace them in any case?

**Comment by 132world** [comment]
> Aren't faces distorted in VR videos? Wouldn't that make difficult to replace them in any case?

 You cut out the portions where the face is not distorted and then run the deepfake on it. Even when the face is distorted a little bit the deepfake looks fine. I have already tried it with simswap.

**Comment by zkh83** [comment]
When will this feature be supported ? Wish you have a plan and schedule

**Comment by henryruhs** [comment]
Planned via https://github.com/s0md3v/roop/issues/622
