### ISSUE TITLE
Endless loop on frames<cpu cores

### ISSUE THREAD

**Issue by vkleinmp** [s0md3v/roop#120]
if the input vide/gif has fewer frames than cpu cores the programm enters a loop without end.

**To Reproduce**
use a very short video or gif or a single image

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you try to use a GPU?
- [x] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by TitasDas** [comment]
This can be replicated with image to image? instead of image to video?

**Comment by noob-guy-dev** [comment]
having same issue ,  but able to make a video using less number of cores. (I have 8 cores)

`python run.py --cores 6`

**Comment by vkleinmp** [comment]
> having same issue , but able to make a video using less number of cores. (I have 8 cores)
> 
> `python run.py --cores 6`

Didn't know python can do this. Thanks !

**Comment by ErikDombi** [comment]
> > having same issue , but able to make a video using less number of cores. (I have 8 cores)
> > `python run.py --cores 6`
> 
> Didn't know python can do this. Thanks !

It's not a python feature 😛 It's one of the flags for `run.py`, so the cores are handled by roop itself

**Comment by henryruhs** [comment]
Please send a PR

**Comment by henryruhs** [comment]
Try next branch, I fixed the issue when frames are lower or equal then cpu cores.
