### ISSUE TITLE
AttributeError: 'INSwapper' object has no attribute 'taskname'

### ISSUE THREAD

**Issue by EKZERSIS** [s0md3v/roop#122]
python run.py
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\ekzer/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\ekzer/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\ekzer/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\ekzer/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Traceback (most recent call last):
  File "C:\Users\ekzer\A1111\roop\run.py", line 25, in <module>
    from core.processor import process_video, process_img
  File "C:\Users\ekzer\A1111\roop\core\processor.py", line 5, in <module>
    from core.config import get_face
  File "C:\Users\ekzer\A1111\roop\core\config.py", line 4, in <module>
    face_analyser = insightface.app.FaceAnalysis(name='buffalo_l', providers=core.globals.providers)
  File "C:\Users\ekzer\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\app\face_analysis.py", line 37, in __init__
    elif model.taskname not in self.models and (allowed_modules is None or model.taskname in allowed_modules):
AttributeError: 'INSwapper' object has no attribute 'taskname'

**Comment by dmx974** [comment]
same issue, impossible to solve.

**Comment by zaazii** [comment]
same here. When I put the file inswapper_128  in the root folder it says inswapper_128 doesn't exist. When I put it in the buffalu folder it says 'INSwapper' object has no attribute 'taskname'.

**Comment by hy426** [comment]
I have the same issue. My environment is Ubuntu 18.04 with conda, Python 3.8, RTX 3090, CUDA 11.7 and PyTorch 2.0.11.

**Comment by jjandnn** [comment]
@all 这个问题我已经回答过了。https://github.com/s0md3v/roop/issues/42，已经关闭。#42问题。我只是不清楚作者为啥不在read me里说清楚。
Hey, guys.
I've already answered that question. https://github.com/s0md3v/roop/issues/42, has been closed.# 42 issues. I don't know why the author didn't say it in the book.

ps：Do not have any characters other than English and numbers in the path and file。

**Comment by henryruhs** [comment]
Can you try the fork from https://github.com/s0md3v/roop/pull/91 please?

**Comment by zaazii** [comment]
> Can you try the fork from #91 please? I resolved the model path via
> 
> ```
> model_path = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'inswapper_128.onnx')
> ```

It finally worked. Thanks a lot for your efforts.

**Comment by henryruhs** [comment]
awesome! now merge back to the original project...
