### ISSUE TITLE
[ONNXRuntimeError] LoadLibrary failed with error 126 "" when trying to load onnxruntime_providers_tensorrt.dll

### ISSUE THREAD

**Issue by Zargerion** [s0md3v/roop#125]
I got error:

RuntimeError: D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1025 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\dev\conda\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

And have this on win10. (nvidia 3060)

![63996e2f4f33b7234a6e9e8d4773ee35](https://github.com/s0md3v/roop/assets/53129740/ad127807-762d-401e-9ed4-94ffb1bea0aa)

**Comment by Tonybam72** [comment]
I am also getting this error upon running with --gpu. Trying a test bluescreened my pc lmao. Works fine when I tried the basic cpu installation.

**Comment by ozanaki** [comment]
Same issue:
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"    
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.

**Comment by iKlsR** [comment]
> I am also getting this error upon running with --gpu. Trying a test bluescreened my pc lmao. Works fine when I tried the basic cpu installation.

Same, had to revert back to CPU, on a 1080

**Comment by Moeblack** [comment]
Just For Windows Nvidia GPU User, the Provider returned by Program include tensorrtexcutionprovider, but the insightface default model don't surpport this.

![image](https://github.com/s0md3v/roop/assets/28835093/34581292-fda2-46d6-93fc-170f080940ee)

I made a very crude modification to fix this error, and it was useful for me. You can give it a try. 

https://github.com/Moeblack/roop

**Comment by FurkanGozukara** [comment]
i spent 5 hours to fix gpu with testing all library versions

cudnn
torch cuda

still not working :/

windows - python - venv

**Comment by hanli2016** [comment]
> Just For Windows Nvidia GPU User, the Provider returned by Program include `tensorrtexcutionprovider`, but the insightface default model don't surpport this.
> 
> ![image](https://user-images.githubusercontent.com/28835093/242132682-34581292-fda2-46d6-93fc-170f080940ee.png)
> 
> I made a very crude modification to fix this error, and it was useful for me. You can give it a try.
> 
> https://github.com/Moeblack/roop

Using your modified version is successful, thank you！

**Comment by henryruhs** [comment]
We disabled Tensor for now, try again with latest.

**Comment by Kerntrick** [comment]
Should this issue be close?  It bug still persists.

**Comment by sam445456** [comment]
> Just For Windows Nvidia GPU User, the Provider returned by Program include `tensorrtexcutionprovider`, but the insightface default model don't surpport this.
> 
> ![image](https://user-images.githubusercontent.com/28835093/242132682-34581292-fda2-46d6-93fc-170f080940ee.png)
> 
> I made a very crude modification to fix this error, and it was useful for me. You can give it a try.
> 
> https://github.com/Moeblack/roop

How to undo this step?  

I run roop as well before this step, even with the title error.

This step fixed the title error but roop process very slow and sometimes crashed.

Python used all the CPU and memory, it's doesn't happen before this modification.

Or how to make it run better?

Thanks
