### ISSUE TITLE
can any one help??

### ISSUE THREAD

**Issue by KelvinT9696** [s0md3v/roop#126]
face_analyser = insightface.app.FaceAnalysis(name='buffalo_l', providers=core.globals.providers)
                    ^^^^^^^^^^^^^^^
AttributeError: module 'insightface' has no attribute 'app'

what does it mean?

**Comment by Moeblack** [comment]
looks like you didn't install insightface correctly. remmember install MSVC C++ 14 and Build tools.

**Comment by KelvinT9696** [comment]
> MSVC C++ 14 and Build tools.

i did installed this , so how im going to install insightface corrently?

**Comment by KelvinT9696** [comment]
> maybe you should `pip install -r requirement.txt --force-reinstall `

 note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects
