### ISSUE TITLE
Error when I click on start

### ISSUE THREAD

**Issue by alexfredo** [s0md3v/roop#13]
Hi this is the message of error I get : 
AVFormatContext @ 0000025af7156500] Unable to choose an output format for ''C:\capt\Deepfake/vid/%04d.png''; use a standard extension for the filename or specify the format manually.
'C:\capt\Deepfake/vid/%04d.png': Invalid argument

**Comment by s0md3v** [comment]
Hi, I pushed some a patch right now. Please try again with latest changes.

**Comment by taladro** [comment]
After pulling new version I tried it and gets stalled on:

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]

**Comment by s0md3v** [comment]
1. is the **roop** window visible?
2. Is it happening before or after clicking on start?

If its happening after clicking on start, the program is working and you should see the results shortly.
If its happening before clicking on start then no worries, click on start.
If you don't see any window or start button, let me know.

**Comment by alexfredo** [comment]
its happening after clicking on start

**Comment by alexfredo** [comment]
it stops at : 
File "C:\capt\Deepfake\run.py", line 124, in <lambda>
    start_button = tk.Button(window, text="Start", bg="green", command=lambda: [save_file(), start()])
  File "C:\capt\Deepfake\run.py", line 85, in start
    args['frame_paths'] = tuple(sorted(
  File "C:\capt\Deepfake\run.py", line 87, in <lambda>
    key=lambda x: int(x.split("/")[-1].replace(".png", ""))
ValueError: invalid literal for int() with base 10: 'vid\\0001'
inswapper-shape: [1, 3, 128, 128]
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]

**Comment by LokeYourC3PH** [comment]
> it stops at : File "C:\capt\Deepfake\run.py", line 124, in start_button = tk.Button(window, text="Start", bg="green", command=lambda: [save_file(), start()]) File "C:\capt\Deepfake\run.py", line 85, in start args['frame_paths'] = tuple(sorted( File "C:\capt\Deepfake\run.py", line 87, in key=lambda x: int(x.split("/")[-1].replace(".png", "")) ValueError: invalid literal for int() with base 10: 'vid\0001' inswapper-shape: [1, 3, 128, 128] Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} inswapper-shape: [1, 3, 128, 128] Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} inswapper-shape: [1, 3, 128, 128] inswapper-shape: [1, 3, 128, 128] inswapper-shape: [1, 3, 128, 128] inswapper-shape: [1, 3, 128, 128]

I'd suggest using the Linux Kernel on Windows and running it that way. Install Ubuntu 22.04 LTS from the Microsoft Store after enabling the Linux Kernel, and try again that way, I'd bet it works. Why I don't know though lol. And let me know how it goes.

**Comment by 0xunderl0rd** [comment]
Same issue, perhaps? My process is hanging here:

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Shadow/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
find model: C:\Users\Shadow/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
find model: C:\Users\Shadow/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
find model: C:\Users\Shadow/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
find model: C:\Users\Shadow/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
find model: C:\Users\Shadow/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]

**Comment by s0md3v** [comment]
@0xunderl0rd its working as intended, these are not errors.

**Comment by 0xunderl0rd** [comment]
> 

That's great to know, however, it appears nothing is happening when this is on screen? The process seems to hang there, no output file is generated and my activity monitor is showing that CPU usage drops after a while...

**Comment by s0md3v** [comment]
Are you sure there isn't a file at the location you specified while clicking start?

Try again with the latest patch.

**Comment by 0xunderl0rd** [comment]
I see you fixed the windows file-path issue, I believe that was the root cause. Thanks so much (for the support, and the awesome app!)

Is there a version of CUDA you recommend for this build? I have Cuda installed but --gpu is giving errors, so I'd like to reinstall whatever build is best in my roop venv...

You rock. And roll.
