### ISSUE TITLE
File "inswapper_128.onnx" does not exist!

### ISSUE THREAD

**Issue by ICreativeKid** [s0md3v/roop#135]
Getting this error File "inswapper_128.onnx" does not exist!

**Comment by Luisdar0z** [comment]
Did you download the model and place it in the root folder?

**Comment by visvignesh** [comment]
Check installation.

**Comment by visvignesh** [comment]
> Getting this error File "inswapper_128.onnx" does not exist!

Check out wiki/1.-Installation

**Comment by henryruhs** [comment]
Read the docs
