### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by LokeYourC3PH** [s0md3v/roop#14]
I'm facing a similar/same issue:

```
frame= 4777 fps=370 q=-0.0 Lsize=N/A time=00:02:39.23 bitrate=N/A speed=12.3x
video:2557927kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/ubuntu/roop/run.py", line 124, in <lambda>
    start_button = tk.Button(window, text="Start", bg="green", command=lambda: [save_file(), start()])
  File "/home/ubuntu/roop/run.py", line 89, in start
    start_processing()
  File "/home/ubuntu/roop/run.py", line 30, in start_processing
    process_video(args['source_img'], args["frame_paths"])
  File "/home/ubuntu/roop/core/processor.py", line 10, in process_video
    source_face = get_face(cv2.imread(source_img))
  File "/home/ubuntu/roop/core/config.py", line 9, in get_face
    return sorted(analysed, key=lambda x: x.bbox[0])[0]
IndexError: list index out of range
```

I have selected both a face (TEST.png) and video (TEST.mp4).

_Originally posted by @LokeYourC3PH in https://github.com/s0md3v/roop/issues/3#issuecomment-1566991104_

**Comment by s0md3v** [comment]
This happens when the program is unable to identify a face in the image. Can you try with a different image to see if that's the case?

**Comment by s0md3v** [comment]
Also, are you on mac by any chance?

**Comment by LokeYourC3PH** [comment]
I'm on Windows 11 Pro, using Ubuntu 22.04 LTS with the Linux Kernel in Windows (works always fine, don't worry about that part).

I personally believe it's the video, where there might be frames in which the person's face isn't visible maybe? But I'll try another picture first.

**Comment by LokeYourC3PH** [comment]
By the way, side comment: Would single image replacement instead of video be possible to add? Or is that already working?

**Comment by s0md3v** [comment]
@LokeYourC3PH Yes, you can select an image as a target and it will work. However, the results are poor around the edges.  A little touch-up with photoshop will make them look good.

**Comment by LokeYourC3PH** [comment]
> @LokeYourC3PH Yes, you can select an image as a target and it will work. However, the results are poor around the edges. A little touch-up with photoshop will make them look good.

Ah okay that makes sense since you only got one image as a reference. With videos, the anti-aliasing and moving motion automatically takes care of that.
