### ISSUE TITLE
Try it on Replicate.com

### ISSUE THREAD

**Issue by okaris** [s0md3v/roop#142]
I've created a demo for this repo on replicate.com, you can try it running on an A100 gpu at [https://replicate.com/okaris/roop](https://replicate.com/okaris/roop)

**Comment by henryruhs** [comment]
Hey, what code fragments does this use? Is this version controlled?

**Comment by okaris** [comment]
It's using a slightly modified fork of this repo. The modifications are to purely create a wrapper for being able to use with Replicate's cog framework to deploy on cloud. I haven't made any further modifications to alter the underlying functionality.

**Comment by henryruhs** [comment]
I would prefer to keep a branch for this purpose in this repository and you deploy from that one.
