### ISSUE TITLE
Fatal error C1083 while installing insightface

### ISSUE THREAD

**Issue by Imtbdev** [s0md3v/roop#143]
I tried to install build tools + win 10/11 sdk + C++ and it doesn't help, also I tried to do it via visual studio installer, it doesn't help either. Also i tried restarting my pc. Im using win 11

**To Reproduce**
1. Install ffmpeg
2. Install C++ 14 and build tools and Visual Studio
3. See error
C:\Users\useruser\AppData\Local\Temp\pip-install-rnmtm60n\insightface_717ebe7a64ee4bc395cdc306697e0b3c\insightface\ ThirdParty\face3d\mesh\cython\mesh_core.h(4): fatal error C1083: ьҐ r¤ Ґvbp ®val vm d © "ўЄ"ozҐЁҐ: stdio.h: No such file or directory

 I am not using the `---gpu` flag

I have the latest code from the github repository
I have followed the installation guide

**Comment by henryruhs** [comment]
Please join Discord for instant help
