### ISSUE TITLE
A problem was encountered while running. Everything installed fine. Environment: Windows10+Nvida GPU

### ISSUE THREAD

**Issue by 7288Fzq** [s0md3v/roop#145]
![image](https://github.com/s0md3v/roop/assets/71710433/151dd0c1-f69d-4d6f-9c9c-9109100da7df)

**Comment by henryruhs** [comment]
My guess: a falsy image...

**Comment by 7288Fzq** [comment]
> 我的猜测：一个虚假的形象......

Do you mean that I entered the wrong picture, but I saw the two pictures I specified correctly in the roop interface.

**Comment by 7288Fzq** [comment]
> 我的猜测：一个虚假的形象……

The suffixes of both pictures are jpg

**Comment by 7288Fzq** [comment]
> 我的猜测：一个虚假的形象......

![image](https://github.com/s0md3v/roop/assets/71710433/14174e2b-ebf6-4fca-9ccb-dfb94a7fd5a6)
