### ISSUE TITLE
NameError: name 'face_swapper' is not defined

### ISSUE THREAD

**Issue by Pansolo72** [s0md3v/roop#149]
**Describe the bug**
  File "C:\Users\Owner\roop\run.py", line 191, in start
    process_img(args['source_img'], target_path, args['output_file'])
  File "C:\Users\Owner\roop\core\processor.py", line 40, in process_img
    result = face_swapper.get(frame, face, source_face, paste_back=True)
             ^^^^^^^^^^^^
NameError: name 'face_swapper' is not defined

**To Reproduce**
After selecting source and target - start - location - Roop runs then stops on the error NameError: name 'face_swapper' is not defined.  I am just swapping a face on a jpg.  Single image but it was working from yesterdays instructions on a different computer. 

**Details**
What OS are you using?
- [ ] Windows 10

Are you try to use a GPU?
- [ ] No, Ryzen 1700

**Screenshots**

**Sanity Check**
Just installed the program an hour ago following the latest instructions.  I have it installed on another computer from yesterdays instructions and it works.

**Comment by Al3601** [comment]
same here, last commit broken everything

**Comment by Pansolo72** [comment]
> same here, last commit broken everything

Ok.  Good to know.

**Comment by henryruhs** [comment]
Does this fix it?

```
    result = get_face_swapper().get(frame, face, source_face, paste_back=True)
```

**Comment by Al3601** [comment]
> Made a commit from the phone. Does this fix it?
> 
> ```
>     result = get_face_swapper().get(frame, face, source_face, paste_back=True)
> ```

can confirm, this worked (only with CPU not with GPU)

**Comment by henryruhs** [comment]
Thanks for the report and testing

**Comment by Pansolo72** [comment]
> Made a commit from the phone. Does this fix it?
> 
> ```
>     result = get_face_swapper().get(frame, face, source_face, paste_back=True)
> ```
Is that in the processor.py file?

**Comment by henryruhs** [comment]
Yes, I pushed it already... run git pull

**Comment by Pansolo72** [comment]
> Yes, I pushed it already... run git pull

Sorry.. I'm not all of this.
From the Git command line?  What is the exact command line?

**Comment by Pansolo72** [comment]
> > Yes, I pushed it already... run git pull
> 
> Sorry.. I'm not all of this. From the Git command line? What is the exact command line?

Nevermind.. got it... Thanks!!!  Wasn't in the right directory.
