### ISSUE TITLE
Add GPU Instructions for Intel Arc

### ISSUE THREAD

**Issue by Valkryst** [s0md3v/roop#150]
The current [GPU Acceleration](https://github.com/s0md3v/roop/wiki/2.-GPU-Acceleration) instructions do not include steps for Intel Arc GPUs. It may be possible to use something like [this](https://github.com/intel/intel-extension-for-pytorch) to add support

If it helps, I can test any changes on an A770 16GB and/or A380 6GB

**Comment by s0md3v** [comment]
Wiki does contain instructions for intel arc. The section is titled "intel" which may have caused the confusion.

https://github.com/s0md3v/roop/wiki/2.-GPU-Acceleration#intel
