### ISSUE TITLE
Failed to build insightface even after installing MS Visual C++

### ISSUE THREAD

**Issue by AniMoster** [s0md3v/roop#153]
As you can see below, I have installed Microsoft Visual C++ but still getting this error

![Screenshot 2023-05-31 080556](https://github.com/s0md3v/roop/assets/94463968/10a91e6b-62be-43bf-a9ef-55e35b10822d)

```
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects
```

**Comment by UberGuidoZ** [comment]
Visual Studio Build Tools is different than the Visual Studio Runtimes. It appears you have the runtimes installed but are missing the build tools. Download [Visual Studio - Community Edition](https://visualstudio.microsoft.com/downloads/) and during install, make sure to include the `Python` and `C++` packages.

**Comment by henryruhs** [comment]
True, you need VS build tools
