### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.15.0 (from versions: none)

### ISSUE THREAD

**Issue by wwwAngHua** [s0md3v/roop#156]
**Describe the bug**
use pip3 install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.15.0 (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu==1.15.0

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ * ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ * ] Intel
- [ ] Mac

**Sanity Check**
- [ * ] I have the latest code from the github repository
- [ * ] I have followed the installation guide

**Comment by s0md3v** [comment]
This issue should be fixed now. Clone the repo and try again.

**Comment by oxidizer05** [comment]
ERROR: Could not find a version that satisfies the requirement onnxruntime1.15.0 (from versions: none)
ERROR: No matching distribution found for onnxruntime1.15.0

my python version 3.10.9
i'm install onnxruntime with this command pip3.10 install onnxruntime
but installed 9.5.0-cp310-cp310-macosx_10_10_x86_64.whl
i need onnxruntime-1.15.0-cp310-cp310-macosx_10_15_x86_64.whl
how to do it?
