### ISSUE TITLE
Error parsing message

### ISSUE THREAD

**Issue by brazilgithub** [s0md3v/roop#158]
I have this error.
I'm using Windows
I'm try to use a GPU NVIDIA RTX 3090

![image](https://github.com/s0md3v/roop/assets/61645540/d8456fe6-6b47-4dd8-9e98-ed9681f28512)

**Comment by adithya-s-sekhar** [comment]
You can ignore those, it'll continue to work. I've noticed the same on Windows but no errors on WSL.

**Comment by henryruhs** [comment]
Looks like a problem in the face analyser. Can you please try another image?

**Comment by henryruhs** [comment]
I close this for now, please reopen if the error still exists
