### ISSUE TITLE
Python script not working in macbook m1

### ISSUE THREAD

**Issue by hashphpdev07** [s0md3v/roop#16]
Getting below error in macbook m1 chip

ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu

**Comment by s0md3v** [comment]
The package you are trying to install is for NVIDIA. Here's the one for Mac: https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider.html

**Comment by LokeYourC3PH** [comment]
> Getting below error in macbook m1 chip
> 
> ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu (from versions: none) ERROR: No matching distribution found for onnxruntime-gpu

You're trying to use NVIDIA GPU rendering, but the M1s don't have any NVIDIA or AMD GPU, so you can only use it without GPU rendering for the moment until M1 is (if ever) supported. Launch it without the "--gpu" flag.

**Comment by hashphpdev07** [comment]
> > Getting below error in macbook m1 chip
> > ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu (from versions: none) ERROR: No matching distribution found for onnxruntime-gpu
> 
> You're trying to use NVIDIA GPU rendering, but the M1s don't have any NVIDIA or AMD GPU, so you can only use it without GPU rendering for the moment until M1 is (if ever) supported. Launch it without the "--gpu" flag.

Thank you. Let me try it. Thanks for quick help.

**Comment by hashphpdev07** [comment]
Its working perfectly! But after successfully run, I can not able to upload target and face files. Any suggestion?

**Comment by LokeYourC3PH** [comment]
> Its working perfectly! But after successfully run, I can not able to upload target and face files. Any suggestion?

Honestly, I don't know. I don't use and (no offence but) would never use Mac, ever. However, since Python works 99% identically across platforms, try placing your logs (just copy-paste from the console window whatever it outputs) here after clicking any of the buttons for choosing your file(s). That way we could determine wherein lies the issue.
