### ISSUE TITLE
cv2

### ISSUE THREAD

**Issue by Deneleon** [s0md3v/roop#163]
**Describe the bug**
I'm getting an AttributeError while trying to run a Python application that uses the cv2 library. The error states: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import). It seems that this error occurs when trying to import the cv2 module.

**To Reproduce**

> Clone the repository and install all required dependencies.
> Navigate to the directory D:\soft\script video change\roop.
> Run the script using the command python run.py.
> The mentioned error appears during the execution.

**Details**
What OS are you using?
> Windows

Are you trying to use a GPU?
> No. I am not using the ---gpu flag

Additional context
> I am using a Windows 10 system with an NVIDIA 1050ti GPU. I have tried reinstalling the opencv-python package and also tried to install it with GStreamer support (pip install opencv-python-headless[gstreamer]), but it didn't help.

Sanity Check
> I have the latest code from the github repository
> I have followed the installation guide

Screenshots
![image](https://github.com/s0md3v/roop/assets/135107549/b7e4577f-7e62-4eea-8cfb-3cba1a9d1c6c)

**Comment by henryruhs** [comment]
Join Discord for instant help, we don't help with installation problems here.
