### ISSUE TITLE
error with Inswapper

### ISSUE THREAD

**Issue by sandiks** [s0md3v/roop#164]
File "/home/user/venv/lib/python3.11/site-packages/insightface/app/face_analysis.py", line 37, in __init__
    elif model.taskname not in self.models and (allowed_modules is None or model.taskname in allowed_modules):
         ^^^^^^^^^^^^^^
AttributeError: 'INSwapper' object has no attribute 'taskname'

**Comment by henryruhs** [comment]
Issues has been opened and resolved x times. Use the search, thanks
