### ISSUE TITLE
[Feature Request] ARM GPU Support

### ISSUE THREAD

**Issue by ArtemKiyashko** [s0md3v/roop#165]
How can i get it using ARM GPU acceleration like "Arm Mali-G610 MP4 “Odin” GPU" on my OrangePI5?

I was able to run without GPU acceleration and it does working good, but wondering if there is any possibility to speedup processing vie integrated GPU?

**Comment by henryruhs** [comment]
See https://github.com/s0md3v/roop/issues/154#issuecomment-1569525572

**Comment by giers10** [comment]
We have to wait for onnxruntime to have GPU support in their mac-arm build.

**Comment by henryruhs** [comment]
Close this for now, we continue tracking that issue here https://github.com/s0md3v/roop/issues/165
