### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by TitasDas** [s0md3v/roop#17]
Great work! while trying it out I had to work my way around the versioning of the different libraries like - 
**_numpy_** and **_protobuf_**. Is there a way you can freeze the versioning of these libraries in the requirements.txt file or add this to the documentation highlighting as to what the correct versions (read based on compatibility) are for each of the libraries used? 

Keep running into this error - 

> RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

> ImportError: cannot import name 'Concatenate' from 'typing_extensions' (C:\ProgramData\Anaconda3\lib\site-packages\typing_extensions.py)

Thank you in advance.

**Comment by TitasDas** [comment]
Keep running into this error - 

> RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

> ImportError: cannot import name 'Concatenate' from 'typing_extensions' (C:\ProgramData\Anaconda3\lib\site-packages\typing_extensions.py)

**Comment by TitasDas** [comment]
Although I fixed this by upgrading to the latest versions of both numpy and typing-extensions. I seem to be stuck at a different place while running the program. Will share that as a different issue.

**Comment by TitasDas** [comment]
In case you don't think specific versioning is necessary , feel free to close this @s0md3v .

**Comment by s0md3v** [comment]
@TitasDas I will definitely version this but I am ironing out the basic things. The changes are too quick rn to be documented.

Tomorrow I will publish `0.0.1-rc`

**Comment by s0md3v** [comment]
The problem with versioning is that it can it can cause conflicts for people who will be installing the dependencies natively (without conda etc).

**Comment by s0md3v** [comment]
I might be wrong tho, let me know.
