### ISSUE TITLE
What about a docker image?

### ISSUE THREAD

**Issue by therepo90** [s0md3v/roop#171]
Neither of the instruictons work on my M1. Can you create docker image to get rid of all these issues?

**Comment by henryruhs** [comment]
Someone on Discord posted a container - I forwarded this issue to him

**Comment by henryruhs** [comment]
https://github.com/s0md3v/roop/issues/162#issuecomment-1572777094

**Comment by henryruhs** [comment]
Based on the chat log, the following requirements can be identified:

- The Docker container must be able to run without needing to checkout the repository first.
- Roop must be checked out inside Dockerfile to ensure standalone functionality.
- Different docker-compose.yml files can be combined for CPU vs. CUDA version.
- Use the "docker compose" command without extra shells or other cross-platform incompatible components.
- Expose a WORKDIR for the outputs.
- Create a service that translates from REST to CLI for easier use.
- Allow for sending a POST with headless args and retrieving output once ready.
- An example docker compose command with multiple YAML files is:

```
docker-compose -f docker-compose.yml -f docker-compose.cuda.yml up
``

**Comment by mbetrifork** [comment]
I'm trying to write a Dockerfile myself because of the Python version nightmare which no Python developer ever thinks is going to be a problem for any end user, whatsoever.

Anyway, I tried the following:
```
FROM python:3.9-alpine
RUN apk update
RUN apk add make automake gcc g++ subversion python3-dev cmake
WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install torch torchvision torchaudio --force-reinstall --index-url https://download.pytorch.org/whl/cu118
RUN pip install onnxruntime-gpu
RUN pip install -r requirements.txt
```

This should be about on par with the gpu install instructions but it doesn't work:
```
$  docker build -t roop-dev .
[omitted]
Collecting torch
  Downloading https://download.pytorch.org/whl/cu118/torch-2.0.0%2Bcu118-cp39-cp39-linux_x86_64.whl (2267.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 GB 1.4 MB/s eta 0:00:00
ERROR: Cannot install torch==2.0.0+cu118 and torch==2.0.1+cu118 because these package versions have conflicting dependencies.

The conflict is caused by:
    torch 2.0.1+cu118 depends on triton==2.0.0; platform_system == "Linux" and platform_machine == "x86_64"
    torch 2.0.0+cu118 depends on triton==2.0.0; platform_system == "Linux" and platform_machine == "x86_64"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```
The instructions don't specify why you need to install onnxruntime and torch manually when those things are already in the requirements file but I do as I'm told. I did comment out those lines in the requirements file though:
```
...
# onnxruntime==1.15.0; sys_platform == 'darwin' and platform_machine != 'arm64'
# onnxruntime-silicon==1.13.1; sys_platform == 'darwin' and platform_machine == 'arm64'
# onnxruntime-gpu==1.15.0; sys_platform != 'darwin'
# torch==2.0.1+cu118; sys_platform != 'darwin'
# torch==2.0.1; sys_platform == 'darwin'
```

I  really think this is an interesting project and I want to try it out and provide some useful feedback. I'm stuck on the runtime environment - which isn't the first time for a Python project .. :-)

**Comment by henryruhs** [comment]
@mbetrifork You can use this as a start: https://github.com/s0md3v/roop/pull/445/files

**Comment by henryruhs** [comment]
Move to https://github.com/s0md3v/roop/issues/632
