### ISSUE TITLE
Insight Face Error

### ISSUE THREAD

**Issue by kwalitykontrol1** [s0md3v/roop#184]
I follow the install instructions, I run it and get ModuleNotFoundError: No module named 'insightface'. So then I download insightface and put that folder inside my roop folder, and then I get this error AttributeError: module 'insightface' has no attribute 'app'. If I keep the insight folder out of the roop folder I get the original No module named 'insightface' error.

**Comment by henryruhs** [comment]
Join Discord for instant help
