### ISSUE TITLE
Could not find a version that satisfies the requirement onnxruntime-gpu==1.15.0 (from versions: none)

### ISSUE THREAD

**Issue by oxidizer05** [s0md3v/roop#189]
ERROR: Could not find a version that satisfies the requirement onnxruntime1.15.0 (from versions: none)
ERROR: No matching distribution found for onnxruntime1.15.0

mac python version 3.10.9
i'm install onnxruntime with this command pip3.10 install onnxruntime
but installed onnx-1.14.0-cp310-cp310-macosx_10_12_x86_64.whl
i need onnxruntime-1.15.0-cp310-cp310-macosx_10_15_x86_64.whl
how to do it?

Cloning into 'roop'...
remote: Enumerating objects: 580, done.
remote: Counting objects: 100% (212/212), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 580 (delta 160), reused 154 (delta 126), pack-reused 368
Receiving objects: 100% (580/580), 9.92 MiB | 11.08 MiB/s, done.
Resolving deltas: 100% (343/343), done.
user@comp ~ % cd roop && pip3 install -r requirements.txt
Collecting numpy==1.24.3 (from -r requirements.txt (line 1))
Using cached numpy-1.24.3-cp310-cp310-macosx_10_9_x86_64.whl (19.8 MB)
Requirement already satisfied: opencv-python==4.7.0.72 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (4.7.0.72)
Collecting onnx==1.14.0 (from -r requirements.txt (line 3))
Using cached onnx-1.14.0-cp310-cp310-macosx_10_12_x86_64.whl (13.8 MB)
Collecting insightface==0.7.3 (from -r requirements.txt (line 4))
Using cached insightface-0.7.3.tar.gz (439 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... done
Installing backend dependencies ... done
Preparing metadata (pyproject.toml) ... done
Collecting psutil==5.9.5 (from -r requirements.txt (line 5))
Using cached psutil-5.9.5-cp36-abi3-macosx_10_9_x86_64.whl (245 kB)
Collecting tk==0.1.0 (from -r requirements.txt (line 6))
Using cached tk-0.1.0-py3-none-any.whl (3.9 kB)
Collecting pillow==9.5.0 (from -r requirements.txt (line 7))
Using cached Pillow-9.5.0-cp310-cp310-macosx_10_10_x86_64.whl (3.4 MB)
Collecting torch==2.0.1 (from -r requirements.txt (line 8))
Using cached torch-2.0.1-cp310-none-macosx_10_9_x86_64.whl (143.4 MB)
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.15.0 (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu==1.15.0

**Comment by TitasDas** [comment]
Please can you try the plain - `pip install onnxruntime`
And let us know if this worked. If yes, I will fix this in the requirements.txt as I am already fixing another issue there.

**Comment by adithya-s-sekhar** [comment]
do you have python and pip installed?

**Comment by oxidizer05** [comment]
> user@comp

user@comp ~ % pip --version
zsh: command not found: pip
user@comp ~ % pip3 --version
pip 23.1.2 from /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip (python 3.10)

**Comment by uPagge** [comment]
It seems that onnxruntime-gpu is not for Apple Silicon, it's very sad

**Comment by brandoncamerer** [comment]
roop git:(main) ✗ pip install onnxruntime-gpu
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu

**Comment by creative-andrew** [comment]
Same error on MAC OS m2
