### ISSUE TITLE
ffmpeg is not installed!

### ISSUE THREAD

**Issue by WGXT** [s0md3v/roop#202]
**Describe the bug**
ffmpeg is not installed!

**To Reproduce**
Executing `python run.py` command

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by RichardErkhov** [comment]
Hi! You can download ffmpeg from their official [website](https://ffmpeg.org/download.html)

**Comment by henryruhs** [comment]
Well then install it :D

**Comment by orangpelupa** [comment]
ffmpeg is already installed but still the same error. the run.py says ffmpeg is not installed

the solution: manually copy the ffmpeg binary to the same location as run.py

**Comment by WGXT** [comment]
> ffmpeg is already installed but still the same error. the run.py says ffmpeg is not installed
> 
> the solution: manually copy the ffmpeg binary to the same location as run.py

you are right! Thanks bro

**Comment by taobaibia** [comment]
<img width="500" alt="image" src="https://github.com/s0md3v/roop/assets/48398413/28bfd428-f358-4434-9e3f-529a704faaca">
ffmpeg is not installed!
I don't know what went wrong, I have changed many versions ，please！

**Comment by msskaa12** [comment]
afer manually copy the ffmpeg binary to the same location as run.py ，I still have the same problem，please！

**Comment by msskaa12** [comment]
> <img alt="image" width="500" src="https://user-images.githubusercontent.com/48398413/246745517-28bfd428-f358-4434-9e3f-529a704faaca.png"> ffmpeg is not installed! I don't know what went wrong, I have changed many versions ，please！

After reinstall homebrew  ，and then install ffmpg ，it work for me。In China mainland，we should change our howbrew install address ，you can use this link https://cloud.tencent.com/developer/article/2138945

**Comment by oogleabcd** [comment]
> > <img alt="image" width="500" src="https://user-images.githubusercontent.com/48398413/246745517-28bfd428-f358-4434-9e3f-529a704faaca.png"> ffmpeg is not installed! I don't know what went wrong, I have changed many versions ，please！
> 
> After reinstall homebrew ，and then install ffmpg ，it work for me。In China mainland，we should change our howbrew install address ，you can use this link https://cloud.tencent.com/developer/article/2138945

I am in windows, and it is normal to copy the exe directly to the virtual environment.
D:\Apps\roop\venv\Scripts
