### ISSUE TITLE
Solved. [After the latest commit (4a8ddf7) the console quits]

### ISSUE THREAD

**Issue by eliasts** [s0md3v/roop#203]
Scratch that, Solved it. Was not updated correctly.

**Comment by eliasts** [comment]
Was not updated correctly

**Comment by ErikDombi** [comment]
For future reference, it's best not to edit your issue after it's need solved. Just leave a comment with the closure on how you fixed it. The thread becomes significantly harder to follow for people having the same issue when it's edited with all the details gone
