### ISSUE TITLE
 Could not find a version that satisfies the requirement onruntime-gpu== 1.15.0 (from versions: none) 

### ISSUE THREAD

**Issue by brandoncamerer** [s0md3v/roop#205]
**Describe the bug**
When installing reqs on my intel mac I get this error 

ERROR: Could not find a version that satisfies the requirement onruntime-gpu==
1.15.0 (from versions: none)
ERROR: No matching distribution found for onruntime-gpu==1.15.0

**To Reproduce**
1. Install Reqs on intel mac

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ X] Mac

Are you try to use a GPU?
- [X] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**
<img width="605" alt="image" src="https://github.com/s0md3v/roop/assets/50874245/8f5b3533-7e95-4fd7-b9c2-e0ba1ef68bc2">

**Sanity Check**
- [ X] I have the latest code from the github repository
- [X ] I have followed the installation guide

**Comment by henryruhs** [comment]
Join Discord for instant help
