### ISSUE TITLE
Still using cpu despite --gpu tag

### ISSUE THREAD

**Issue by ZephyrusXI** [s0md3v/roop#206]
I just checked my task manager recently because how slow the videos processed.

What I noticed was that my CPU usage was >80% and HDD was 100%, while my GPU is at 0.

What am I doing wrong?

The only difference I see between using the --gpu tag and not is that, without the tag my PC is unusable while processing (massive lag and stutter). With the tag, I can use my PC albeit after the swapping has started.
![Screenshot 2023-05-31 235101](https://github.com/s0md3v/roop/assets/111444272/39390663-34c4-44fb-9f6d-9d694edf66b3)
![Screenshot 2023-05-31 235136](https://github.com/s0md3v/roop/assets/111444272/f37363d5-03c8-4253-b9e7-f22505f1d12a)
![Screenshot 2023-05-31 235213](https://github.com/s0md3v/roop/assets/111444272/90377e39-8409-4115-b33f-e4f1c85926ac)

**Comment by bbecausereasonss** [comment]
Welcome to everyones problem.

**Comment by henryruhs** [comment]
Clone of https://github.com/s0md3v/roop/issues/132
