### ISSUE TITLE
dependency conflict with numpy

### ISSUE THREAD

**Issue by conceptualspace** [s0md3v/roop#207]
**Describe the bug**
dependency conflict: onnxruntime-gpu 1.15.0 depends on numpy >= 1.24.2 but tensorflow 2.12.0 depends on numpy < 1.24

**To Reproduce**
pip install

**Details**
What OS are you using?
- [*] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [*] I have the latest code from the github repository
- [*] I have followed the installation guide

**Comment by raffaem** [comment]
> Should be solved in main

it isn't
