### ISSUE TITLE
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1266: error: (-2:Unspecified error) The function is not implemented.

### ISSUE THREAD

**Issue by kool99988** [s0md3v/roop#208]
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1266: error: (-2:Unspecified error) The function is not implemented.

**The previous version is fine until updated to the latest version**

**Describe the bug**

**Details**
What OS are you using?
- [* ] Windows 

Are you try to use a GPU?
- [ *] NVIDIA
- [ *] Intel

**Comment by henryruhs** [comment]
Reinstall opencv-python

```
pip uninstall opencv-python
```

```
pip install opencv-python
```

**Comment by kool99988** [comment]
2023-06-01 04:57:02.145997: I tensorflow/stream_executor/cuda/cuda_blas.cc:1786] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
100%|████████████████████████████████████████████████████████████████████████████████████████████████▊| 583/584 [00:12<00:00, 51.61it/s]Exception in Tkinter callback
Traceback (most recent call last):
  File "E:\AI\sd-webui-aki-v4.1\python\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "E:\AI\roop\run.py", line 275, in <lambda>
    start_button = tk.Button(window, text="Start", bg="#f1c40f", relief="flat", borderwidth=0, highlightthickness=0, command=lambda: [save_file(), start()])
  File "E:\AI\roop\run.py", line 202, in start
    seconds, probabilities = predict_video_frames(video_path=args['target_path'], frame_interval=50)
  File "E:\AI\sd-webui-aki-v4.1\python\lib\site-packages\opennsfw2\_inference.py", line 178, in predict_video_frames
    cv2.destroyAllWindows()  # pylint: disable=no-member
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1266: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

**I've tried it many times, it doesn't work, but the previous version is fine**
