### ISSUE TITLE
Sound and picture are out of sync

### ISSUE THREAD

**Issue by jjandnn** [s0md3v/roop#210]
2023.6.1 The latest master, the sound and picture are not synchronized after synthesis, and the sound is one second late！

**Comment by FurkanGozukara** [comment]
yes you need to fix sound yourself

i have shown in this video : https://www.youtube.com/watch?v=OI1LEN-SgLM

**Comment by jjandnn** [comment]
@FurkanGozukara Not the problem you are talking about, 4 hours ago, that is, before the author updated the latest version of master (he first updated the progress bar plugin tqdm), there is no problem.
