### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by dazinator** [s0md3v/roop#211]
**Describe the bug**

following basic instructions
at pip install step, package version conflict:

```
ERROR: Cannot install -r requirements.txt (line 2), -r requirements.txt (line 3), -r requirements.txt (line 4), -r requirements.txt (line 9) and numpy==1.23.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.23.5
    opencv-python 4.7.0.72 depends on numpy>=1.21.2; python_version >= "3.10"
    opencv-python 4.7.0.72 depends on numpy>=1.22.0; python_version >= "3.11"
    opencv-python 4.7.0.72 depends on numpy>=1.17.0; python_version >= "3.7"
    opencv-python 4.7.0.72 depends on numpy>=1.17.3; python_version >= "3.8"
    opencv-python 4.7.0.72 depends on numpy>=1.19.3; python_version >= "3.9"
    onnx 1.14.0 depends on numpy
    insightface 0.7.3 depends on numpy
    onnxruntime-gpu 1.15.0 depends on numpy>=1.24.2
```

I used `choco install python` to install python on windows 11.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows ``
- [ ] Mac

Are you try to use a GPU?
- [x] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by FurkanGozukara** [comment]
for those having problems here the tutorial and the GitHub file. use this commit id and follow instructions it is working. i just did a fresh install. this is for windows

https://github.com/FurkanGozukara/Stable-Diffusion/blob/main/Tutorials/1-Click-DeepFake-Tutorial.md

https://www.youtube.com/watch?v=OI1LEN-SgLM

```git checkout ab2fc1c221b78b2a57f2e971cf5064da089b576f```

**Comment by henryruhs** [comment]
Please join Discord for help
