### ISSUE TITLE
banned

### ISSUE THREAD

**Issue by hassan-sd** [s0md3v/roop#215]
You ban discord members who mention there is a NSFW blocker in place.
All you need to do is state your intentions are not NSFW and don't allow it in your discord, instead you ban anyone who tells users what their error really means.

You give them an error that states there is something wrong with face detection but in reality it's that your NSFW blocker is kicking in and you try to hide it. Stop being an ass like this.

**Comment by s0md3v** [comment]
ok.

**Comment by dazinator** [comment]
read the disclaimer on the readme - pretty clear to me
