### ISSUE TITLE
[Feature Request] Real-time processing (video to video)

### ISSUE THREAD

**Issue by nihs269** [s0md3v/roop#218]
Sorry, I want to know this project can be run in real-time or it generate a new video from source video??

**Comment by RichardErkhov** [comment]
Right now Im working on it and expect first working test version today or tomorrow. Will notify if I did so,ething, but please remind me as I can forget

**Comment by henryruhs** [comment]
sure, we would love to accept a PR. this might improve performance a ton.

**Comment by SantiiRepair** [comment]
hey

**Comment by phineas-pta** [comment]
so will it replace https://github.com/iperov/DeepFaceLive (recently stalled) ?

**Comment by RichardErkhov** [comment]
idk, I don't think so

**Comment by henryruhs** [comment]
This feature is out of project scope. Sorry 😐
