### ISSUE TITLE
Everything works except the output video doesn't have face changed

### ISSUE THREAD

**Issue by ZephyrusXI** [s0md3v/roop#221]
Only some videos, the face swapping doesn't take place. The frames are extracted and then compiled into a output video without faceswap. It works fine for some other videos. Don't know what the problem is. They're all mp4 as well.
After extracting video is created without processing.

[EDIT}
Solution: Changing the name of the target file seems to fix it. Reason still unknown

**Comment by henryruhs** [comment]
We focus on reproducable bugs only as we limited in time. PR are welcome if someone can find the bug.

**Comment by UseLEss213** [comment]
how to fix this error -   

Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in Pillow setup command: use_2to3 is invalid.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
