### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'keras'

### ISSUE THREAD

**Issue by juddisjudd** [s0md3v/roop#228]
**Describe the bug**
Cannot run "python run.py"

**Keep getting:**
```
Traceback (most recent call last):
  File "D:\_AI\roop\run.py", line 15, in <module>
    from opennsfw2 import predict_video_frames, predict_image
  File "c:\python\lib\site-packages\opennsfw2\__init__.py", line 4, in <module>
    from ._inference import Aggregation
  File "c:\python\lib\site-packages\opennsfw2\_inference.py", line 15, in <module>
    from ._inspection import make_and_save_nsfw_grad_cam
  File "c:\python\lib\site-packages\opennsfw2\_inspection.py", line 17, in <module>
    model: tf.keras.Model,
AttributeError: module 'tensorflow' has no attribute 'keras'
```

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

I have uninstalled and reinstalled tensor flow via pip and conda and either seem to change this.
All other requirements are installed as well.

**Comment by michael1618** [comment]
Re-import tensorflow and try
