### ISSUE TITLE
Validation for select a face

### ISSUE THREAD

**Issue by henryruhs** [s0md3v/roop#23]
Button "Select a face" should have a validation to prevent crashes describe in https://github.com/s0md3v/roop/issues/14. There is no point on processing the video if the face is not detected.

**Comment by henryruhs** [comment]
I meant the image extraction, yes... well it is a nice to have feature. Take care of the urgent bugs instead.

**Comment by LokeYourC3PH** [comment]
> I meant the image extraction, yes... well it is a nice to have feature. Take care of the urgent bugs instead.

Indeed, for me there's other more pressing issues for now, and maybe getting a higher model (256 or 512) somehow to increase output resolution, that would be nice.

**Comment by s0md3v** [comment]
Done. Now the user will be warned if no face is detected in the source image before any kind of processing is done.

**Comment by LokeYourC3PH** [comment]
> Done. Now the user will be warned if no face is detected in the source image before any kind of processing is done.

Holy shit that was fast. Thanks a lot!
