### ISSUE TITLE
Has anyone successfully used it? I have run it many times, and the result is that the video is no different from the original video. I began to suspect that this code may be a joke

### ISSUE THREAD

**Issue by shenbushou** [s0md3v/roop#235]
Has anyone successfully used it? I have run it many times, and the result is that the video is no different from the original video. I began to suspect that this code may be a joke

**Comment by jjandnn** [comment]
你的路径中有非法字符，比如中文。请把你的整个包放到无非法字符的路径下，比如D:/，以及所有文件全部英文或数字。
There are illegal characters in your path, such as Chinese. Please put your entire package in a path with no illegal characters, such as D:/, and all files in English or numbers.

**Comment by tanhm12** [comment]
Same problem here, I've tried many different SOURCE_IMG but none of them worked. I ran it with GPU and command was `CUDA_VISIBLE_DEVICES=1 python run.py --gpu -f ./obama.jpg -t ./superman-face.mp4 -o ./result.mp4`
