### ISSUE TITLE
Use codeFormer to upscale the swapped face and merged with frame.

### ISSUE THREAD

**Issue by Moeblack** [s0md3v/roop#237]
**Describe your suggestion**

for exmaple

```
def process_img(source_img, target_path, output_file):
    frame = cv2.imread(target_path)
    face = get_face(frame)
    source_face = get_face(cv2.imread(source_img))
    _img, _ = get_face_swapper().get(frame, face, source_face, paste_back=False)
    result = _img 
    cv2.imwrite("face"+output_file, result)
```

use this can output all swapped face pics, and use [Codeformer-pip](https://github.com/kadirnar/codeformer-pip) to upscale them, then merged with frame.

but how can I merged them? any suggestions?

**Comment by henryruhs** [comment]
We have an issue for that... https://github.com/s0md3v/roop/issues/146
