### ISSUE TITLE
GPU acceleration not working on Arch

### ISSUE THREAD

**Issue by sandiks** [s0md3v/roop#247]
GPU NVIDIA GeForce RTX 2060
cuda 11.0.3 
cudnn8-cuda11.0

`
/home/user/venv/lib/python3.11/site-packages/torch/cuda/__init__.py:107: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
You are using --gpu flag but CUDA isn't available or properly installed on your system
`

**Comment by RichardErkhov** [comment]
sorry, not sure what to do in this situation, maybe you can try to use another distribution? I will try to see what I can do for arch.
Is something from here compatible with your system ? https://developer.nvidia.com/cuda-11-7-0-download-archive?target_os=Linux&target_arch=x86_64

**Comment by CeeBeeEh** [comment]
@sandiks Use [DistroBox](https://github.com/89luca89/distrobox). With that you can setup whatever OS environment you want without having to mess with your base system. Speaking from experience it makes working with AI and GPU accelerated systems much easier, especially running Arch.
