### ISSUE TITLE
"Keep frames dir" checked but still deletes frames dir

### ISSUE THREAD

**Issue by MantisTree** [s0md3v/roop#248]
I check the box next to "keep frames dir" but the frames dir still gets deleted upon successful completion of task.

**Comment by s0md3v** [comment]
@henryruhs I think this may have introduced the issue: https://github.com/s0md3v/roop/commit/43990c9367c3cb5f3c0d20436cf9eb849594c53a

**Comment by shadowlocked** [comment]
It definitely is an issue, also for me.

**Comment by henryruhs** [comment]
can someone send a PR?

**Comment by joni999** [comment]
It does work for me - maybe it was already fixed?

**Comment by henryruhs** [comment]
Please try laterst main and reopen if the issue still exists.
