### ISSUE TITLE
Installing on Mac M1

### ISSUE THREAD

**Issue by aldoyh** [s0md3v/roop#249]
**Describe the bug**

**To Reproduce**
Just right after running the install command `./buildmacos.sh`
I got this:

![Screenshot 2023-06-01 at 16 26 09](https://github.com/s0md3v/roop/assets/5215449/cfe310ae-46ea-4a0e-a3a4-c236651897d3)

Full output log here:
https://app.warp.dev/block/PdGLwEqOYoAmls5ttI03Hg

**Details**
What OS are you using?
Mac M1 Max

Are you try to use a GPU?
- [ ] Mac

**Screenshots**

**Sanity Check**
- [✅] I have the latest code from the github repository
- [✅] I have followed the installation guide

**Comment by henryruhs** [comment]
Merge to main - should work now... but do not expect great performance, there are still issues

**Comment by aldoyh** [comment]
You guys are doing wonderful job, I'll update back with the status, if does work I will sponsor this amazing project! ❤️
