### ISSUE TITLE
[Features Request] - Drag & Drop + Auto Output Names + Test Mode

### ISSUE THREAD

**Issue by AlonDan** [s0md3v/roop#256]
My suggestions are focused on improving the UI / UX to make things more pleasant and make ROOP more AWESEOME.
I have many more ideas, but let's start simple:

---
**Drag & Drop**
Will be nice to just Drag an image to the "Select a Face" 
Same for the "Select a Target" not as a replacement, but extra option.
UX wise It's faster to have directories open and drag from them.

---
**Auto Output**
OUTPUT file will be based on:
TARGET + SOURCE filenames + SUFFIX + Version Number (instead of overwrite)

It will be great if we can input any suffix name as input box and allow the UI to REMEMBER (store) it even after closing ROOP UI, so next session we won't have to change it again, unless we want.

For example:
Source file: **MyFace**.png 
Target file: **MyVideo**.mpg
Suffix name: ** - ROOP**
Version name: (start from 01 and goes up instead of overwrite)

Output: **MyVideo_MyFace - ROOP - 01**.mpg
Output again (same files): **MyVideo_MyFace - ROOP - 02**.mpg

SimSwap uses suffix and when using THE SAME FILES AGAIN
the result will start give it numbers (version) so it won't overwrite, safe-mode.

---
**Test Mode**
Sometimes you just want to try a short amount of a longer video
Test mode with input to allow X amount of seconds to test.

For example: 
You may like to test 5 or 10 seconds instead of 60 seconds of the full clip.
The OUTPUT default could be based on ABOVE naming + extra SUFFIX:

Output: **MyVideo_MyFace - ROOP - 01 - (Test 7 sec)**.mpg

---
Please keep up the good work on ROOP 💙
I'll be happy to see any of the suggestions here applied, if you need more UI / UX ideas I have so many and I would LOVE to contribute with my design ideas to make ROOP great!

**Comment by henryruhs** [comment]
Merged with https://github.com/s0md3v/roop/issues/257
