### ISSUE TITLE
[Feature Request] UI Improvements

### ISSUE THREAD

**Issue by AlonDan** [s0md3v/roop#257]
✅ **Display Preview while Rendering**
It will be great to have a BOX within the UI to shows the process while rendering.
Another option is extra window, but using the UI as once piece is much more organized and user friendly.

---
🟡 **Progress Bar**
At the moment we can only look at the console to see the percentage %
Showing it within the UI will be much cleaner and yet again, user friendly.

---
✅  **Select Face or Multiple Faces**
This is inspired from SimSwap where you can choose multiple SOURCES (faces)
and pick where to place each one on the TARGET video with multiple people.

For starter it will be nice to just allow select which face to use if you have multiple people in the TARGET VIDEO, at the moment I believe it's only on once based on some rules, so it will flip around faces if they're closer to the camera or centered (it's a guess)

Multi SOURCE FACES on TARGET video with MULTIPLE PEOPLE probably will be great to have as the next evolution like in SimSwap, that's a lot of control for the user.

My suggestions are focused on improving the UI / UX to make things more pleasant and make ROOP more AWESEOME.
I have many more ideas, but let's start simple:

---
✅ **Drag & Drop**
Will be nice to just Drag an image to the "Select a Face" 
Same for the "Select a Target" not as a replacement, but extra option.
UX wise It's faster to have directories open and drag from them.

---
✅ **Auto Output**
OUTPUT file will be based on:
TARGET + SOURCE filenames + SUFFIX + Version Number (instead of overwrite)

It will be great if we can input any suffix name as input box and allow the UI to REMEMBER (store) it even after closing ROOP UI, so next session we won't have to change it again, unless we want.

For example:
Source file: **MyFace**.png 
Target file: **MyVideo**.mpg
Suffix name: ** - ROOP**
Version name: (start from 01 and goes up instead of overwrite)

Output: **MyVideo_MyFace - ROOP - 01**.mpg
Output again (same files): **MyVideo_MyFace - ROOP - 02**.mpg

SimSwap uses suffix and when using THE SAME FILES AGAIN
the result will start give it numbers (version) so it won't overwrite, safe-mode.

---
🟡 **Test Mode / Select Range of output**
Sometimes you just want to try a short amount of a longer video
Test mode with input to allow X amount of seconds to test.

There could be a range slider inside the preview.

For example: 
You may like to test 5 or 10 seconds instead of 60 seconds of the full clip.
The OUTPUT default could be based on ABOVE naming + extra SUFFIX:

Output: **MyVideo_MyFace - ROOP - 01 - (Test 7 sec)**.mpg

---
🟡 **A simple webui based on gradio**

This would have a huge benefit for docker based solutions.

---
🟡 **Add Multiple Process Que List / Batch**
Based on the current GUI:
Since we can SEE 2 Thumbnails per task process:
SOURCE + TARGET

We should place 1 of 1 on TOP = means, one "PAGE" or task.

To add another task you will press a PLUS BUTTON 
it will look like 1 of 2 etc..
To delete current task (the specific "page" user currently on)
press a MINUS BUTTON or TRASHCAN icon - (delete current page / task)

top will update 1 of 3 etc.. or 1 of 1 by default for one task only.

Once pressing START to render, it will SHOW the current "page" (1 of 3 for example)
and move on to the next one when it's finished: 2 of 3 etc..

This could be VERY useful in my opinion.

---

Please keep up the good work on ROOP 💙
I'll be happy to see any of the suggestions here applied, if you need more UI / UX ideas I have so many and I would LOVE to contribute with my design ideas to make ROOP great!

**Comment by henryruhs** [comment]
I like the ideas a lot - like preview and testing a short range totally is on my todo list. Should we make a pool so the community has the change to vote for the next features?

**Comment by K1llMan** [comment]
Qt-based GUI.

**Comment by Colliwomple** [comment]
Hi !
Maybe a small thing for many but i can´t resize the UI. So resizable UI would make a difference

**Comment by henryruhs** [comment]
@K1llMan That will be tuff as QT comes with their own Threads...

**Comment by K1llMan** [comment]
1. Select specific frame in preview.
2. Possibility to check every processor result from list in preview.
3. Save frame or processor result from preview.
4. Support of range preview processing.

**Comment by crowbait** [comment]
I'd like to suggest drag-and-drop face and video selection. Just makes the workflow simpler and faster.

**Comment by vectorobject** [comment]
I've written a GUI for roop，hope it can help you.

![](https://github.com/vectorobject/faceswap/blob/main/readme_assets/main.png?raw=true)

https://github.com/vectorobject/faceswap

**Comment by henryruhs** [comment]
@vectorobject That looks really coo - I suggest you reach out on Discord and open a thread on our workshop section so you can promote your project to our users.

**Comment by dinhnguyen-groove** [comment]
To make the app simple, I suggest we add these settings to the advanced setting section. Could you please create a wireframe or something like that, so that I or anyone can give a hand on this UI feature, @henryruhs ?

**Comment by henryruhs** [comment]
I close this as the next UI does cover a wide variety of the requests.

Try it already by switching to next branch

```
git pull
git checkout next
pip install -r requirements.txt
```
