### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'videosrc\\0001'

### ISSUE THREAD

**Issue by cibernicola** [s0md3v/roop#26]
Just this:
```
video:324317kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Exception in Tkinter callback
Traceback (most recent call last):
  File "*:\*\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "J:\roop\run.py", line 130, in <lambda>
    start_button = tk.Button(window, text="Start", bg="green", command=lambda: [save_file(), start()])
  File "J:\roop\run.py", line 91, in start
    args['frame_paths'] = tuple(sorted(
  File "J:\roop\run.py", line 93, in <lambda>
    key=lambda x: int(x.split("/")[-1].replace(".png", ""))
ValueError: invalid literal for int() with base 10: 'videosrc\\0001'
```

Under Windows 10, trying to use it with CUDA.

**Comment by cibernicola** [comment]
git pull:
```
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 13 (delta 9), reused 6 (delta 4), pack-reused 0
Unpacking objects: 100% (13/13), 2.24 KiB | 1024 bytes/s, done.
From https://github.com/s0md3v/roop
   825b7e7..fa813d8  main       -> origin/main
Updating 825b7e7..fa813d8
Fast-forward
 core/config.py    |  3 ++-
 core/processor.py |  3 ++-
 core/utils.py     | 18 +++++++++++-------
 run.py            | 21 ++++++++++++++++-----
 4 files changed, 31 insertions(+), 14 deletions(-)
```
python run.py --gpu

```
Traceback (most recent call last):
  File "J:\roop\run.py", line 3, in <module>
    import core.globals
ModuleNotFoundError: No module named 'core.globals'
```

**Comment by solanovisitor** [comment]
Same issue as @cibernicola here!

**Comment by s0md3v** [comment]
I am sorry, I'm an idiot. Forgot to upload that file. Try now :(

**Comment by solanovisitor** [comment]
I'm now getting the following error after python run.py --gpu:

`Traceback (most recent call last):
  File "__init__.pxd", line 942, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/faceswap/roop/run.py", line 16, in <module>
    from core.processor import process_video, process_img
  File "/content/gdrive/MyDrive/faceswap/roop/core/processor.py", line 2, in <module>
    import insightface
  File "/usr/local/lib/python3.10/dist-packages/insightface/__init__.py", line 18, in <module>
    from . import app
  File "/usr/local/lib/python3.10/dist-packages/insightface/app/__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "/usr/local/lib/python3.10/dist-packages/insightface/app/mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "/usr/local/lib/python3.10/dist-packages/insightface/thirdparty/face3d/__init__.py", line 3, in <module>
    from . import mesh
  File "/usr/local/lib/python3.10/dist-packages/insightface/thirdparty/face3d/mesh/__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
  File "insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.pyx", line 6, in init insightface.thirdparty.face3d.mesh.cython.mesh_core_cython
  File "__init__.pxd", line 944, in numpy.import_array
ImportError: numpy.core.multiarray failed to import`

**Comment by cibernicola** [comment]
Same argument, this error.
```
Traceback (most recent call last):
  File "*:\*\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "J:\roop\run.py", line 141, in <lambda>
    start_button = tk.Button(window, text="Start", bg="green", command=lambda: [save_file(), start()])
  File "J:\roop\run.py", line 93, in start
    Path(output_dir).mkdir(exist_ok=True)
  File "*:\**\lib\pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
```
Then it freezes here:
![image](https://github.com/s0md3v/roop/assets/4579387/0922898c-1738-4540-9ff4-42d6bab2c20a)

**Comment by shhivv** [comment]
```
~ python run.py --gpu
Traceback (most recent call last):
  File "run.py", line 16, in <module>
    from core.processor import process_video, process_img
  File "C:\Users\shivs\Downloads\roop\core\processor.py", line 1, in <module>
    import cv2
  File "C:\Users\shivs\AppData\Local\Programs\Python\Python38\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\shivs\AppData\Local\Programs\Python\Python38\lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "C:\Users\shivs\AppData\Local\Programs\Python\Python38\lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "C:\Users\shivs\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\shivs\AppData\Local\Programs\Python\Python38\lib\site-packages\cv2\gapi\__init__.py", line 301, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)```

Getting a different error here

**Comment by solanovisitor** [comment]
> I'm now getting the following error after python run.py --gpu:
> 
> ```
> Traceback (most recent call last):
>   File "__init__.pxd", line 942, in numpy.import_array
> RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/content/gdrive/MyDrive/faceswap/roop/run.py", line 16, in <module>
>     from core.processor import process_video, process_img
>   File "/content/gdrive/MyDrive/faceswap/roop/core/processor.py", line 2, in <module>
>     import insightface
>   File "/usr/local/lib/python3.10/dist-packages/insightface/__init__.py", line 18, in <module>
>     from . import app
>   File "/usr/local/lib/python3.10/dist-packages/insightface/app/__init__.py", line 2, in <module>
>     from .mask_renderer import *
>   File "/usr/local/lib/python3.10/dist-packages/insightface/app/mask_renderer.py", line 8, in <module>
>     from ..thirdparty import face3d
>   File "/usr/local/lib/python3.10/dist-packages/insightface/thirdparty/face3d/__init__.py", line 3, in <module>
>     from . import mesh
>   File "/usr/local/lib/python3.10/dist-packages/insightface/thirdparty/face3d/mesh/__init__.py", line 9, in <module>
>     from .cython import mesh_core_cython
>   File "insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.pyx", line 6, in init insightface.thirdparty.face3d.mesh.cython.mesh_core_cython
>   File "__init__.pxd", line 944, in numpy.import_array
> ImportError: numpy.core.multiarray failed to import
> ```

Solved with:

```
!sudo pip install numpy --upgrade --ignore-installed
```

**Comment by cibernicola** [comment]
```
DON'T WORRY. IT'S NOT STUCK.
DON'T WORRY. IT'S NOT STUCK.
DON'T WORRY. IT'S NOT STUCK.
DON'T WORRY. IT'S NOT STUCK.
DON'T WORRY. IT'S NOT STUCK.
```
<3

but:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "*:\*\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "J:\roop\run.py", line 144, in <lambda>
    start_button = tk.Button(window, text="Start", bg="green", command=lambda: [save_file(), start()])
  File "J:\roop\run.py", line 95, in start
    output_dir = output_dir.lstrip("\\", "")
TypeError: lstrip expected at most 1 argument, got 2
```

**Comment by s0md3v** [comment]
@cibernicola check again, pushed another fix

**Comment by cibernicola** [comment]
somthing is wrong with paths:
`.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
ffmpeg version 4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200523
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[image2 @ 000001ed3e09afc0] Pattern type 'glob' was selected but globbing is not supported by this libavformat build
K:/videosrc\*.png: Function not implemented
ffmpeg version 4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200523
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
K:/videosrc\output.mp4: No such file or directory
Exception in Tkinter callback
Traceback (most recent call last):
  File "*\lib\shutil.py", line 815, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'K:/videosrc{sep}output.mp4' -> 'K:/output.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "*\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "J:\roop\run.py", line 144, in <lambda>
    start_button = tk.Button(window, text="Start", bg="green", command=lambda: [save_file(), start()])
  File "J:\roop\run.py", line 111, in start
    add_audio(output_dir, target_path, args['keep_frames'], args['output_file'])
  File "J:\roop\core\utils.py", line 41, in add_audio
    shutil.move(output_dir + "{sep}output.mp4", save_to)
  File "*\lib\shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "*0\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "*\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'K:/videosrc{sep}output.mp4'
`

**Comment by s0md3v** [comment]
@cibernicola You are almost there, you just weren't able to save the video!

This should be fixed now, finally, I think!

**Comment by alexfredo** [comment]
It's works for me with the latest change !

**Comment by cibernicola** [comment]
> @cibernicola You are almost there, you just weren't able to save the video!
> 
> This should be fixed now, finally, I think! Try with the latest changes

Re testing, but it appears this Message: "K:/videosrc\K:/videosrc.mp4: Invalid argument"

![image](https://github.com/s0md3v/roop/assets/4579387/262f8492-7a0c-4877-91b8-266df69e75d3)

**Comment by s0md3v** [comment]
wait a second, what OS are you using @cibernicola?

**Comment by cibernicola** [comment]
Windows 10

**Comment by cibernicola** [comment]
Output from
```
import platform
print(platform.platform())
```

![image](https://github.com/s0md3v/roop/assets/4579387/fc104f82-0cc0-46d1-83d1-d04338934ae5)

**Comment by cibernicola** [comment]
`K:/vid2\K:/vid2.mp4: Invalid argument`
`K:/vid2\K:/vid2.mp4: Invalid argument`
```
[image2 @ 000002d6ea9cafc0] Pattern type 'glob' was selected but globbing is not supported by this libavformat build
K:/vid2\*.png: Function not implemented
```

Where:

"select image" = k:\be.jpg
"select target" = k:\vid2.mp4
"result" = k:\output.mp4

:S

**Comment by s0md3v** [comment]
@cibernicola Okay, last chance. Run it again.

**Comment by cibernicola** [comment]
Now it seems to work!

but its using CPU, but step by step, I'll tell u asap.

**Comment by s0md3v** [comment]
@cibernicola idk what the fuck is going on, sorry. Can you use a print statement see the value of output_dir?

**Comment by cibernicola** [comment]
![image](https://github.com/s0md3v/roop/assets/4579387/18652d98-4824-4238-b96e-ef8c0ffb371b)

Output directory: K://vid2.

**Comment by s0md3v** [comment]
I figured out the problem I think. @cibernicola 

Python wants the paths to be `C:\like\this`
ffmpeg wants them to be `/like/this/`

I think I can fix this, brb

**Comment by cibernicola** [comment]
But "K://vid2" its not a folder, dunno why it gets it as a folder, is the video target, is it correct?

**Comment by s0md3v** [comment]
@cibernicola Try now. If it doesn't work, I guess I will install windows myself and fix it lol.

**Comment by cibernicola** [comment]
evolving! but:
**Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "J:\roop\run.py", line 139, in <lambda>
    start_button = tk.Button(window, text="Start", bg="green", command=lambda: [save_file(), start()])
  File "J:\roop\run.py", line 100, in start
    args['frame_paths'] = tuple(sorted(
  File "J:\roop\run.py", line 102, in <lambda>
    key=lambda x: int(x.split("/")[-1].replace(".png", ""))
ValueError: invalid literal for int() with base 10: 'vid2\\0001'**

*it creates vid2 dir *

**Comment by s0md3v** [comment]
Okay, thanks for helping me out so far. I am switching to windows and taking caring of it personally. brb

**Comment by s0md3v** [comment]
@cibernicola I ran it on windows, fixed the errors and it should be working now.

**Comment by cibernicola** [comment]
Perfect, now its working!!! 

not using GPU, but its working!
