### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by guoqing886** [s0md3v/roop#260]
The conflict is caused by:
    The user requested numpy==1.23.5
    opencv-python 4.7.0.72 depends on numpy>=1.21.2; python_version >= "3.10"
    opencv-python 4.7.0.72 depends on numpy>=1.22.0; python_version >= "3.11"
    opencv-python 4.7.0.72 depends on numpy>=1.17.0; python_version >= "3.7"
    opencv-python 4.7.0.72 depends on numpy>=1.17.3; python_version >= "3.8"
    opencv-python 4.7.0.72 depends on numpy>=1.19.3; python_version >= "3.9"
    onnx 1.14.0 depends on numpy
    insightface 0.7.3 depends on numpy
    onnxruntime-gpu 1.15.0 depends on numpy>=1.24.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by 42lux** [comment]
Same for me the requirements.txt is borked

**Comment by walkxcode** [comment]
Try using Python 3.10.x. If you need more help, I've written a step my step guide in my fork: https://github.com/walkxcode/roop/blob/main/docs/INSTALLATION.md

**Comment by ErikDombi** [comment]
@henryruhs Could you at least say WHY you're closing issues? Like at LEAST have some sort of copy & paste message explaining how to find similar issues. Would abide by common curtesy
