### ISSUE TITLE
Cannot install packages due to conflicting dependencies

### ISSUE THREAD

**Issue by EidosL** [s0md3v/roop#265]
**Describe the bug**
Cannot install packages due to conflicting dependencies

‘’ ERROR: Cannot install -r requirements.txt (line 10), -r requirements.txt (line 2), -r requirements.txt (line 3), -r requirements.txt (line 4) and numpy==1.23.5 because these package versions have conflicting dependencies. The conflict is caused by: The user requested numpy==1.23.5 opencv-python 4.7.0.72 depends on numpy>=1.21.2; python_version >= "3.10" opencv-python 4.7.0.72 depends on numpy>=1.22.0; python_version >= "3.11" opencv-python 4.7.0.72 depends on numpy>=1.17.0; python_version >= "3.7" opencv-python 4.7.0.72 depends on numpy>=1.17.3; python_version >= "3.8" opencv-python 4.7.0.72 depends on numpy>=1.19.3; python_version >= "3.9" onnx 1.14.0 depends on numpy insightface 0.7.3 depends on numpy onnxruntime-gpu 1.15.0 depends on numpy>=1.24.2 To fix this you could try to: 1. loosen the range of package versions you've specified 2. remove package versions to allow pip attempt to solve the dependency conflict ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts 

**To Reproduce**
1. Clone the repository and navigate to the project directory.
2. Run the command pip install -r requirements.txt.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x ] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**
![image](https://github.com/s0md3v/roop/assets/70374652/53da071d-adcd-4b4e-90e6-16636f43a9fb)

**Sanity Check**
- [x ] I have the latest code from the github repository
- [x ] I have followed the installation guide

**Comment by henryruhs** [comment]
Please try the following and report what worked for you:

1. remove the version from numby**==**
1. remove numpy completely in hope related dependencies resolve it
1. try another python version like 3.10

for each step rerun pip install -r requirements.txt

**Comment by mpishchaev** [comment]
I belive the problem is in the following:
    onnxruntime-gpu 1.15.0 depends on numpy>=1.24.2
    tensorflow-intel 2.12.0 depends on numpy<1.24 and >=1.22

**Comment by henryruhs** [comment]
tensorflow==2.13.0rc1; sys_platform == 'windows'

does this solve it? the problem is I cannot test it as I use Ubuntu 22

**Comment by opsxff** [comment]
Did you use python3.11?  I used python3.10 to solve it.

**Comment by mpishchaev** [comment]
Yes, the last python - 3.11.3 (Win 11).
Tried the following:
- remove `numpy`
- remove `tensorflow==2.12.0; sys_platform != 'darwin'`
Neither is working

**Comment by mpishchaev** [comment]
rollbacked python to 3.10 - the issue resolved

**Comment by henryruhs** [comment]
Great... still this will happen to lot of people. Sorry but we have no real solution as it differs on each platform

**Comment by walkxcode** [comment]
Here is the solution. You have to install the correct python version and use a virtual environment.
https://github.com/walkxcode/roop/blob/main/docs/INSTALLATION.md
