### ISSUE TITLE
option for full gpu utilization 

### ISSUE THREAD

**Issue by 132world** [s0md3v/roop#266]
My vram is 6 GB and the app is using %30 of it. It spikes from time to time but mostly remains around %30. On google colab it uses only 3 GB. I wonder if it's possible to add the option for full utilization of the gpu.

**Comment by kool99988** [comment]
Similarly, my 4070t is running up to 3G

**Comment by henryruhs** [comment]
There is an open PR for this... we take care of it, no worries
