### ISSUE TITLE
'NoneType' object has no attribute 'dumps'

### ISSUE THREAD

**Issue by YanTianlong-01** [s0md3v/roop#270]
**Describe the bug**
```
Exception ignored in: <function Pool.__del__ at 0x7f88b30bdb80>
Traceback (most recent call last):
  File "/Users/yantianlong/opt/anaconda3/lib/python3.9/multiprocessing/pool.py", line 268, in __del__
  File "/Users/yantianlong/opt/anaconda3/lib/python3.9/multiprocessing/queues.py", line 372, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
```

**To Reproduce**
1. select the photo and video
2. Click on 'start'
3. `[WARNING] No face detected in source image. Please try with another one.`
4. select another image
5. Click on 'start'
6. See the error

**Details**
What OS are you using? 
- [x] Mac

Are you try to use a GPU?
- [x] No. I am not using the `---gpu` flag

**Screenshots**
<img width="1426" alt="image" src="https://github.com/s0md3v/roop/assets/78240661/f125587e-fe87-4816-8346-0858e6b1a5b4">
<img width="1440" alt="image" src="https://github.com/s0md3v/roop/assets/78240661/d61ba016-1b23-4f2d-a8f8-ef257b147387">

<img width="1418" alt="image" src="https://github.com/s0md3v/roop/assets/78240661/be5309eb-fbc5-497d-b6fe-333886f7989f">

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by henryruhs** [comment]
Try Python 3.10 or join Discord for help
