### ISSUE TITLE
Could not find a version that satisfies the requirement onruntime-gpu== 1.15.0 (from versions: none)

### ISSUE THREAD

**Issue by xiaofeige** [s0md3v/roop#273]
**Describe the bug**
No matching distribution found for onnxruntime-gpu==1.15.0
![image](https://github.com/s0md3v/roop/assets/10513399/533d3642-f91b-4f7b-845c-5ff554cdc5fc)

**To Reproduce**
follow the installation step as you said, 

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ✅] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [✅] Mac with AMD gpu

**Screenshots**

**Sanity Check**
- [ ] I have the latest code from the github repository
- [ ] I have followed the installation guide

there are so many same problems as mime , please help us here ,not discard or some where else.

**Comment by henryruhs** [comment]
I think you have an outdated version, this should not happen under Mac. Please join Discord, we don't give installation support in GitHub issues.
