### ISSUE TITLE
python run.py  error  "illegal hardware instruction"

### ISSUE THREAD

**Issue by ZhangWeiHelloWorld** [s0md3v/roop#276]
**Describe the bug**

exec python run.py
env:
python version **3.10.11**
Mac m1
<img width="450" alt="image" src="https://github.com/s0md3v/roop/assets/31679484/309ca4b7-d990-4527-998e-e5408b93d054">

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ✅] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ✅] Mac

**Screenshots**

**Sanity Check**
- [ ] I have the latest code from the github repository
- [ ] I have followed the installation guide

**Comment by henryruhs** [comment]
M1 issue, nothing we can do about it. Join #mac on Discord for help
