### ISSUE TITLE
CPU multiprocessing causes progess bar to flicker

### ISSUE THREAD

**Issue by henryruhs** [s0md3v/roop#281]
Processing bar does flicker on CPU only mode. It is probably connected to the "skip if no face" condition

**Comment by kelvinthh** [comment]
Can confirm this happens on Mac as well in CPU mode.

**Comment by henryruhs** [comment]
Fixed it in next branch, hopefully it is not slower now

**Comment by henryruhs** [comment]
A potential solution could be [tqdm-multiprocess]( https://pypi.org/project/tqdm-multiprocess). Pull request are welcome!
