### ISSUE TITLE
[Feature Request] Process a directory with images 

### ISSUE THREAD

**Issue by durachio** [s0md3v/roop#282]
Right now roop is supporting the processing of video.

I propose to implement the possibility to process images as well. It can be done by specifying the folder with images one wants to process and then roop will process the whole folder of images. Even the possibility to process only 1 image would be very good for the start. Thanks!

**Comment by henryruhs** [comment]
Makes sense... good point

**Comment by danyderden** [comment]
Or multiple selection of images

**Comment by ExecutableMarley** [comment]
roop already supports the processing of single images. I suggest adding a batch image processing option to the command line mode since that would be really easy to do with the existing source.
Example pic:
![image](https://github.com/s0md3v/roop/assets/47697856/96df186a-5b26-4b5b-8194-2eabae3997cc)

**Comment by durachio** [comment]
@ExecutableMarley I just tried it and it does not work for me. On the latest version, I am getting an exception. 

```
Traceback (most recent call last):
  File "C:\Python3.10.4\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\roop\run.py", line 276, in <lambda>
    start_button = tk.Button(window, text="Start", bg="#f1c40f", relief="flat", borderwidth=0, highlightthickness=0, command=lambda: [save_file(), start()])
  File "C:\roop\run.py", line 221, in start
    start_processing()
  File "C:\roop\run.py", line 99, in start_processing
    for i in range(0, len(frame_paths), n):
ValueError: range() arg 3 must not be zero
```

**Comment by ExecutableMarley** [comment]
@durachio Yes it seems like there is a bug that prevents image processing from working. Until the latest the next branch gets merged into main you can manually fix it by changing line 93 in "run.py" from "if args['gpu']:" to "if args['gpu'] or is_img(args['target_path']):"

**Comment by kex0** [comment]
This PR can do it. #188

**Comment by henryruhs** [comment]
Not planned at the moment
