### ISSUE TITLE
GPU unavailable for MacOS Parallels Desktop users

### ISSUE THREAD

**Issue by Coutinho159** [s0md3v/roop#283]
CPU works properly in a Mac M1 Pro using Parallels Desktop with Windows 11 but it is really slow (10 frames rendered each 5 minutes)
Due to CUDA 12 not supporting my current gpu, is not possible to run it with the —gpu command.
It would be amazing with someday this roop could work directly in the macOS without parallels desktop to run gpu.

**Comment by henryruhs** [comment]
We do not support CUDA higher than 11.8 anyway. Same as https://github.com/s0md3v/roop/issues/162

**Comment by kelvinthh** [comment]
Just use `pip install onnxruntime-silicon` as shown in the wiki. `--gpu` does work on M1 Macs but now it would take up a huge chunk of your memory and memory swap.
