### ISSUE TITLE
NVIDIA RTX 3060 GPU not being used

### ISSUE THREAD

**Issue by SmoothBrainApe** [s0md3v/roop#284]
Hi, just want to report if its a bug or not.

I have installed on both my laptop and pc, both run Linux Mint (Ubuntu based)

Installed properly with no known errors. Works great on laptop with NVIDIA 1060

But when I used it on my PC running NVIDIA RTX 3060, it doesnt use the GPU but keeps using CPU. Tried reinstalling from timeshift snapshot but same results. I installed the exact same way on both laptop and PC but only works fine on laptop. Perhaps some issue with newer GPU?

Got some screenshots. It says (CPUExecutionProvider) on the PC. When I do on laptop is says (CUDAExecutionProvider)

![R1](https://github.com/s0md3v/roop/assets/135333835/f05788df-07e4-4ccd-bbbb-f414d1653dc0)
![R2](https://github.com/s0md3v/roop/assets/135333835/930536f6-8372-4556-937d-0db00e072774)

**Comment by henryruhs** [comment]
There is a related PR open
