### ISSUE TITLE
 Failed building wheel for insightface

### ISSUE THREAD

**Issue by antispamtutoruser123** [s0md3v/roop#29]
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Iinsightface/thirdparty/face3d/mesh/cython -IC:\Users\jj131\AppData\Local\Temp\pip-build-env-57p_hett\overlay\Lib\site-packages\numpy\core\include -IC:\Users\jj131\AppData\Local\Programs\Python\Python310\include -IC:\Users\jj131\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpinsightface/thirdparty/face3d/mesh/cython/mesh_core.cpp /Fobuild\temp.win-amd64-cpython-310\Release\insightface/thirdparty/face3d/mesh/cython/mesh_core.obj
      mesh_core.cpp
      C:\Users\jj131\AppData\Local\Temp\pip-install-nwtd9gn3\insightface_a627e7b51d7a49a19c1df75acae001f4\insightface\thirdparty\face3d\mesh\cython\mesh_core.h(4): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

**Comment by antispamtutoruser123** [comment]
There are a lot of warnings like thiswhen trying to install this package:

 C:\Users\jj131\AppData\Local\Temp\pip-build-env-v8_nthjx\overlay\Lib\site-packages\setuptools\command\build_py.py:201: _Warning: Package 'insightface.data.objects' is absent from the `packages` configuration.

**Comment by s0md3v** [comment]
@antispamtutoruser123 are you installing it with pip?

**Comment by Moeblack** [comment]
just install Visual Studio

**Comment by 144358** [comment]
> 

yes
