### ISSUE TITLE
[Feature request]: Batch Render

### ISSUE THREAD

**Issue by AlonDan** [s0md3v/roop#293]
**Add Multiple Process Que List / Batch**
Based on the current GUI:
Since we can SEE 2 Thumbnails per task process:
SOURCE + TARGET

We should place 1 of 1 on TOP = means, one "PAGE" or task.

---
To add another task you will press a PLUS BUTTON 
it will look like 1 of 2 etc..
To delete current task (the specific "page" user currently on)
press a MINUS BUTTON (delete current page / task)

top will update 1 of 3 etc.. or 1 of 1 by default for one task only.

Once pressing START to render, it will SHOW the current "page" (1 of 3 for example)
and move on to the next one when it's finished: 2 of 3 etc..

This could be VERY useful in my opinion.

**Comment by henryruhs** [comment]
Merge it with your UI branch - please do not open so many issues

**Comment by AlonDan** [comment]
> Merge it with your UI branch - please do not open so many issues

Sorry about that, I'll edit the current one in order to add more UI suggestions.
Feel free to delete this one, thanks again for your great work 💙
