### ISSUE TITLE
The conflict 

### ISSUE THREAD

**Issue by Ysuperjie** [s0md3v/roop#294]
how do i deal with this problem：：：
The conflict is caused by:
    The user requested numpy==1.23.5
    opencv-python 4.7.0.72 depends on numpy>=1.21.2; python_version >= "3.10"
    opencv-python 4.7.0.72 depends on numpy>=1.22.0; python_version >= "3.11"
    opencv-python 4.7.0.72 depends on numpy>=1.17.0; python_version >= "3.7"
    opencv-python 4.7.0.72 depends on numpy>=1.17.3; python_version >= "3.8"
    opencv-python 4.7.0.72 depends on numpy>=1.19.3; python_version >= "3.9"
    onnx 1.14.0 depends on numpy
    insightface 0.7.3 depends on numpy
    onnxruntime-gpu 1.15.0 depends on numpy>=1.24.2

**Comment by henryruhs** [comment]
Either use the search (as we covered this countless times) or join Discord for help.
