### ISSUE TITLE
Software crashes on Windows 10

### ISSUE THREAD

**Issue by Basicrain** [s0md3v/roop#297]
Software opens and lets me choose input media, but as long as i hit "Start" it ends with

"Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Windows\System32\roop\run.py", line 141, in select_face
    preview_image(args['source_img'])
  File "C:\Windows\System32\roop\run.py", line 109, in preview_image
    img = Image.open(image_path)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'C:/Users/User/Desktop/faceswap project/2.mp4'
C:\Windows\System32\roop\run.py:110: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  img = img.resize((180, 180), Image.ANTIALIAS)
C:\Windows\System32\roop\run.py:128: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  img = img.resize((180, 180), Image.ANTIALIAS)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\User/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\User/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\User/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\User/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\User/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
100%|████████████████████████████████████████████████████████████████████████████████| 632/632 [00:06<00:00, 99.31it/s]"

I have no idea where exactly i should pass 'rcond=-1' value if it is the issue, or what else should i do to get it to work. I do not use GPU option.

**Comment by henryruhs** [comment]
Not working with that kind of video you are using ^

**Comment by Basicrain** [comment]
What kind of video should i use?

**Comment by henryruhs** [comment]
PORN
