### ISSUE TITLE
Allow specify directory where models are stored

### ISSUE THREAD

**Issue by BenBE** [s0md3v/roop#30]
It would be nice if you could specify a directory where models are stored/loaded from.

Currently models are stored all over the place (home directory), while other models are loaded from your current working directory.

**Comment by s0md3v** [comment]
I understand that this can be annoying for some people I won't complicate things more than they need to be.

To answer why one model needs to be downloaded manually and put in **roop** dir is because it was taken down by its authors and can't be download automatically.

**Comment by BenBE** [comment]
The problem is not about manual downloading of some of the models (totally fine with this), but it would be nice, if things could be held in one common directory.

P.S.: Thanks for the background for why the manual download is.

**Comment by BenBE** [comment]
Quick one-shot for having all needed models in a central directory (subdirectory `models` below cwd):

```diff
$ git diff --cached 
diff --git a/core/config.py b/core/config.py
index bbaad5ea..dff09ece 100644
--- a/core/config.py
+++ b/core/config.py
@@ -2,7 +2,7 @@ import insightface
 import onnxruntime
 import core.globals
 
-face_analyser = insightface.app.FaceAnalysis(name='buffalo_l', providers=core.globals.providers)
+face_analyser = insightface.app.FaceAnalysis(name='buffalo_l', providers=core.globals.providers, root=".")
 face_analyser.prepare(ctx_id=0, det_size=(640, 640))
 
 
diff --git a/core/processor.py b/core/processor.py
index eb759750..004e8bf1 100644
--- a/core/processor.py
+++ b/core/processor.py
@@ -5,7 +5,7 @@ import core.globals
 from core.config import get_face
 from core.utils import rreplace
 
-face_swapper = insightface.model_zoo.get_model('inswapper_128.onnx', providers=core.globals.providers)
+face_swapper = insightface.model_zoo.get_model('inswapper_128.onnx', providers=core.globals.providers, root=".")
 
 
 def process_video(source_img, frame_paths):
```

Would even be better to just pass this value as an argument.
