### ISSUE TITLE
PowerShell tried to load a malicious resource detected as Heur.BZC.ZFV.Boxter.341.8545EB6F and was blocked. Your device is safe.

### ISSUE THREAD

**Issue by paradisebuster44** [s0md3v/roop#301]
**Describe the bug**
Got this message while installing requirements.txt. I am using BitDefender antivirus.

"PowerShell tried to load a malicious resource detected as Heur.BZC.ZFV.Boxter.341.8545EB6F and was blocked. Your device is safe."

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you try to use a GPU?
- [x] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by ljara2106** [comment]
Based on google searches, looks to be false positive alerts from your antivirus.

https://stackoverflow.com/questions/58530046/bitdefender-says-code-insiders-download-has-heur-bzc-nzf-pantera-7-37c58ef0
