### ISSUE TITLE
i have problem with launch this app

### ISSUE THREAD

**Issue by TimotheiPsh** [s0md3v/roop#303]
**Describe the bug**

**To Reproduce**
2. Click on 'Start'

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [*] Windows 
- [ ] Mac

Are you try to use a GPU?
- [*] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [*] I have the latest code from the github repository
- [*] I have followed the installation guide

 File "E:\Work\Shared\Python39_64\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\timot/.insightface\models\buffalo_l\w600k_r50.onnx failed:Protobuf parsing failed.

**Comment by henryruhs** [comment]
Installation help on Discord only
