### ISSUE TITLE
[Suggestion] Offer the possibility to use the GPU for ffmpeg processing

### ISSUE THREAD

**Issue by AntwaneB** [s0md3v/roop#305]
Hello,

Using the `-hwaccel cuda` flag when running a ffmpeg command, you can enable GPU-based processing. Example:

```
ffmpeg -hwaccel cuda -i "{input_path}" "{output_dir}{sep}%04d.png"
```

I have tested this on my computer with a Ryzen9 3900x and a RTX 3080 and it was actually slower than using the CPU only (up to 2x based on my tests), but I think it may be beneficial for people that have a CPU with less cores, or a GPU that is way better than their CPU.

So the suggestion is to give an option to use GPU processing for ffmpeg specifically (so that it can be set separately from the general `--gpu` flag).

On long videos, extracting the frames and setting the FPS takes a measurable amount of time so if it can be cut down for some people it's great.

Thanks.

**Comment by henryruhs** [comment]
We have this already in the next branch

**Comment by AntwaneB** [comment]
After looking, you have the option on by default if GPU processing is enabled with the `--gpu`, but as I saw in my tests, this will decrease performances for a lot of situations. So this one should be behind a separate flag.
