### ISSUE TITLE
[Feature Request] Increase the face resolution

### ISSUE THREAD

**Issue by zhaojigang** [s0md3v/roop#308]
**Describe your suggestion**
![image](https://github.com/s0md3v/roop/assets/14085645/a9b66c72-1b33-4513-b3ab-9646229a252e)
The one on the left is generated directly by me using software；On the right is the video synthesized after increasing the resolution of the image frame.
Can we add an option to whether to synthesize ultra clear videos? If yes, before synthesizing the video, we will first increase the resolution of the changed face images

**Comment by zhaojigang** [comment]
sorry, i find the pr,i close this fr

**Comment by jeffryWillam** [comment]
大佬，你这是怎么调高分辨率的？
