### ISSUE TITLE
First progress meter gets to 100%, then program just closes.

### ISSUE THREAD

**Issue by MantisTree** [s0md3v/roop#309]
A few days ago, I determined it did this for videos over 2 minutes - even a video over 2:01 would cause it, so I broke my videos in to 2:00 chunks.  Now it can't do those either. Even reducing to 1 minute chunks causes this behavior.

I am running on NVIDIA.  I have just cloned. I have run pip install -r requirements.txt which returned no issues.  

Program launches normally.  I am selecting all three checkboxes. I select a face, a target, and an output file.  I have also tried all command line operators which also generates the same behavior.

This issue occurs with or without --gpu flag.

![rooperror](https://github.com/s0md3v/roop/assets/16402210/2f3fc77e-14f0-4eb7-ba92-1adec3158257)

**Comment by s0md3v** [comment]
NSFW videos don't work with this tool.

**Comment by MantisTree** [comment]
> NSFW videos don't work with this tool.
> 
> If it wasn't an NSFW video, reopen the issue.

Is a bikini NSFW?  Is this your limitation or a limitation of the packages used?

**Comment by s0md3v** [comment]
It's a limitation of the package being used, it simply gives a score.

I am planning to replace it as soon as possible with the nudenet library
that can identify specific NSFW parts of body.
