### ISSUE TITLE
CPU Executive Provider error

### ISSUE THREAD

**Issue by prateekkeshari** [s0md3v/roop#31]
Getting this error in terminal:
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}

Trying with a source image and target video. The output doesn't show. However, when I do a source image and a target photo, it works (however the quality of the output is pixelated).

Thank you!

**Comment by s0md3v** [comment]
That's not an error, it's just information. Wait and you will see the output.
