### ISSUE TITLE
Feature request: keep track of progress

### ISSUE THREAD

**Issue by Rigo-m** [s0md3v/roop#313]
Some systems with less memory (e.g.: in my case 8gb m1 apple silicon) crashes when going out of memory. A quick fix for this could be to keep track pf already tranforms frame so that you can run the app many times on the same video skipping already transformed frames

**Comment by Deadstarrr** [comment]
I have 24gb of memory and I get the "out of memory" errors too.

**Comment by phineas-pta** [comment]
use `--max-memory` to limit how much RAM it can use

**Comment by henryruhs** [comment]
we could try to add it to progress bar... did it for vram in next branch already

**Comment by Rigo-m** [comment]
Actually I tried using the max memory argument, but it crashed anyway. So maybe there's a problem with mac memory management in arm64?

**Comment by henryruhs** [comment]
can you try the next branch?

**Comment by Rigo-m** [comment]
Sure! I'll let you know as soon as i get home. In the mean time I wish you a happy Sunday!

**Comment by Rigo-m** [comment]
So:
- Max memory argument is still a no-no in mac silicon, but it's an upstream issue with python ignoring rlimit in mac silicons as I've found out after some googling.
- Cpu processing is slow and cpu goes bonkers (obviously) but flawless
- Gpu processing setting `--gpu-vendor apple` crashes after ~200 frames processed.

Can I help you anyhow with some code tests? I'm a javascript programmer so I'm oblivious to Python but if I can help anyway I will!

**Comment by henryruhs** [comment]
Close in favor of https://github.com/s0md3v/roop/issues/321
