### ISSUE TITLE
Pipeline-alike module mechanism

### ISSUE THREAD

**Issue by K1llMan** [s0md3v/roop#314]
1. Create pipeline frames producer class. Optional saving frames or extracting directly to memory.
2. Create common module interface for process blocks. Pipeline parts can running separately.
3. Create resource balancer if it's possible to speed up full process.
4. Create mechanism for constructing process pipeline from blocks.
5. Create pipeline result frames collector. From memory or disk.

**Comment by henryruhs** [comment]
Like the idea but the amount of energy and time that has to put into this could be a show stopper. Can we at least prepare the current codebase in a way to make this possible later on?

**Comment by K1llMan** [comment]
Yes, sure. swapper almost done for it. Needed some interfaces for passing process parameters instead of using globals everywhere.

**Comment by henryruhs** [comment]
We need to refactor and restructure the codebase first. Like `core.py` is still a big mess... the project needs to be able to receive PRs on a daily base without breaking instantly.

That being said: wait a bit with a PR until the project is more stable. You can still share your ideas by providing code snips in this issue.

I can imagine that leaving the frames in the memory could be a huge performance boost.

**Comment by Moeblack** [comment]
wouldn't it result in excessive memory overhead? We can Extracte several tens of thousands of frames from a 20-minute video.

**Comment by K1llMan** [comment]
Extracting should work not like ffmpeg but frame by frame mechanism. Then frame goes through full pipeline directly to output file. There may be some issues with parallel extracting and collecting frames.
Loading models shouldn't be a problem if user know limits of resources. I think about warming up mechanism to get faster test preview and initializing full process. Also if models are large we can store intermediate result into physical file and load models one by one.

**Comment by K1llMan** [comment]
Basic functionality on branch https://github.com/K1llMan/roop/tree/pipeline

`python run_pipeline.py -f "<>" -t "<>" -o "<>"`

Directly read and swap.
core_pipeline.py contains definition of basic pipeline with extractor, swapper, collector and postprocessor. Progress and preview handlers can be used. Also created cancellation token for process termination.

**Comment by K1llMan** [comment]
@henryruhs So. Can I create pull request to 'next' with basic implementation? It has its own package with own 'core' and 'run'.

**Comment by henryruhs** [comment]
Yes just send a PR and describe what problems you could solve and what the advantage of the integration is. I just have to align all the PRs, it might cause couple of merge conflicts until it goes through so please be patient.

**Comment by henryruhs** [comment]
We have something similar in the works, I close this for now. Thanks for the contribution anyway.
