### ISSUE TITLE
roop does not do anything

### ISSUE THREAD

**Issue by ggauzin** [s0md3v/roop#320]
after starting deepfaking it still shows "Status: waiting for input"
![image](https://github.com/s0md3v/roop/assets/128216038/190072dc-b568-4bed-9963-e75640c92569)
then this permanently with no result
![image](https://github.com/s0md3v/roop/assets/128216038/946103e7-7420-4efb-ad4c-f479cbc0f3c4)
i tried many times with many pic/vid combinations and i did'nt work any time
UPD: for hour straight now, i am closing it

**Comment by henryruhs** [comment]
Reinstall opencv-python

**Comment by ggauzin** [comment]
no, that does not work

**Comment by RickyWang111** [comment]
me too.  can't input video.
![image](https://github.com/s0md3v/roop/assets/96077395/16826f1c-c2ac-4c17-8ed3-23bbf831ebb8)

nothing happen.
