### ISSUE TITLE
Video can't be processed

### ISSUE THREAD

**Issue by Hillton53** [s0md3v/roop#323]
**Describe the bug**
Can't process my video (file size about 21mb) but the example video can be processed successfully

**To Reproduce**
1. Open the software
2. Choose my face and the target video
3. max fps=30 , show all the frames

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ √] Windows 
- [ ] Mac

Are you try to use a GPU?
- [√] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**log**
(venv) D:\Deepface\roop>python run.py --keep-frames --keep-fps --max-cores 1
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\yhr10/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\yhr10/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\yhr10/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\yhr10/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\yhr10/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
D:\Deepface\roop\venv\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
4497it [00:11, 387.12it/s]

(venv) D:\Deepface\roop>

**Comment by henryruhs** [comment]
I guess the NSFW filter kicked in, otherwise join Discord for help
