### ISSUE TITLE
After running, application exits with no warning/errors

### ISSUE THREAD

**Issue by ffgtu** [s0md3v/roop#326]
**Describe the bug**

When I try to run a swap the application simply exits 

68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
100%|███████████████████████████████████████████████████| 137/137 [00:01<00:00, 105.91it/s]
PS E:\Users\Filip\Documents\code\roop>

After that progress bar, it simply exits

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [ ] I have the latest code from the github repository
- [ ] I have followed the installation guide

**Comment by ffgtu** [comment]
Last working commit hash for me was 4e2be506ce72969cd799af4d55cad7c0ab4c54df 

Something after that is causing the application to simply exit after I try running a swap.

I tried re-installing everything and running through the setup again as a sanity check. Only working hash is that one

**Comment by henryruhs** [comment]
NSFW I guess
