### ISSUE TITLE
Swap image to image

### ISSUE THREAD

**Issue by wokege159** [s0md3v/roop#329]
image to video swap is running without problems but when i just swap image with other image it shows this message (Im using M1 pro):

start_button = create_button(window, "Start", lambda: [save_file(save_file_handler, target_path.get()), preview_thread(lambda: start(update_preview))])
  File "/Users/name/roopmuitobom/roop/core.py", line 196, in start
    args.frame_paths = tuple(sorted(
  File "/Users/name/roopmuitobom/roop/core.py", line 198, in <lambda>
    key=lambda x: int(x.split(sep)[-1].replace(".png", ""))
ValueError: invalid literal for int() with base 10: '00004-330165758'

**Comment by wokege159** [comment]
forgot to say that that happens when i swap jpg to jpg.

jpeg to jpeg or png to jpeg shows this:

 [libx264 @ 0x13e00a000] width not divisible by 2 (1599x1536)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x127008c00] moov atom not found
/Users/name/Library/Mobile Documents/iCloud~com~comcsoft~iterminal/Documents/keys/Models/2312/output.mp4: Invalid data found when processing input

**Comment by wokege159** [comment]
Btw, image to image swap works perfectly in preview mode with png and jpeg

**Comment by rohkeus** [comment]
I'm having the same problem when replacing a face in a gif. I'm using a M2 Pro.

[libx264 @ 0x15a606c40] width not divisible by 2 (437x431)7<00:00,  1.45s/frame]
[vost#0:0/libx264 @ 0x15a606970] Error initializing output stream: Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x146e05040] moov atom not found
/Users/rick/Downloads/giphy/output.mp4: Invalid data found when processing input

**Comment by henryruhs** [comment]
This will be fixed in next branch soon as I currently refactor the UI. Give it a couple of days to become stable, before opening new issues.
