### ISSUE TITLE
4.2gb Vram can export faster than use 5.7 gb vram of GPU, what is different --gpu-threads in ROOP-NEXT  ? 

### ISSUE THREAD

**Issue by cuong29102003** [s0md3v/roop#333]
i use nvidia RTX 2060, i sue --gpu vendor nvidia --gpu-threads 2 It work very nice, it can export about 10 - 12 frame/s and use about 4.2gb vram
![image](https://github.com/s0md3v/roop/assets/112108445/8abe60fd-3f6f-4453-b115-8d687ddc2cf1)
but i setting --gpu-threads 3 or 4 higher it export bout 7 - 9 frame and verry slow, it use me 5.7 GB of Vram
![image](https://github.com/s0md3v/roop/assets/112108445/6a98c790-79cb-415c-8ab9-d24cfef326bd)
Can you explain me about --gpu-threads, and suggest me setting for it

**Comment by henryruhs** [comment]
Use as much as possible, it is connected to the CUDA cores of your GPU I guess. Actual you have to play around with it a bit... we will later implement a formular to detect the best default GPU threads for you.
