### ISSUE TITLE
Deprecate GPU arguments

### ISSUE THREAD

**Issue by henryruhs** [s0md3v/roop#339]
We should replace the GPU arguments as the execution providers are not always GPU related?

`--gpu-vendor=apple|amd|intel|nvidia` to `--execution-provider=coreml|rocm|openvino|cuda` and
`--gpu-threads` to `--execution-threads`

We could also have  `apple-coreml` and `nvidia-cuda` so it's easier to pick by vendor.

## Execution Providers

[NVIDIA - CUDA](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html)
[NVIDIA - TensorRT](https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html)
[Intel - OpenVINO™](https://onnxruntime.ai/docs/execution-providers/OpenVINO-ExecutionProvider.html)
[Intel - oneDNN](https://onnxruntime.ai/docs/execution-providers/oneDNN-ExecutionProvider.html)
[Windows - DirectML](https://onnxruntime.ai/docs/execution-providers/DirectML-ExecutionProvider.html)
[Qualcomm - QNN](https://onnxruntime.ai/docs/execution-providers/QNN-ExecutionProvider.html)
[Android - NNAPI](https://onnxruntime.ai/docs/execution-providers/NNAPI-ExecutionProvider.html)
[Apple - CoreML](https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider.html)
[XNNPACK](https://onnxruntime.ai/docs/execution-providers/Xnnpack-ExecutionProvider.html)
[AMD - MIGraphX](https://onnxruntime.ai/docs/execution-providers/MIGraphX-ExecutionProvider.html)
[AMD - ROCm](https://onnxruntime.ai/docs/execution-providers/ROCm-ExecutionProvider.html)
[Cloud - Azure](https://onnxruntime.ai/docs/execution-providers/Azure-ExecutionProvider.html)

**Comment by s0md3v** [comment]
lgtm but `apple-coreml` and `nvidia-cuda` style args are unnecessary imo.

**Comment by henryruhs** [comment]
Well, they prefix it on the official docs aswell - user without knowledge cannot know that cuda is nvidia only.

**Comment by henryruhs** [comment]
Solved via https://github.com/s0md3v/roop/pull/459
