### ISSUE TITLE
RUNTIME_EXCEPTION : Non-zero status code returned while running Gemm node

### ISSUE THREAD

**Issue by ZephyrusXI** [s0md3v/roop#341]
Ran the program with "--gpu-vendor nvidia" since there is no "--gpu" flag anymore.
This is the error I get. It works fine except for the fact that the process is really slow. I think GPU is not being used, because of this error?

`RUNTIME_EXCEPTION : Non-zero status code returned while running Gemm node. Name:'Gemm_568' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=MSI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=164 ; expr=cublasCreate(&cublas_handle_);`

**Comment by henryruhs** [comment]
Try to reduce use `--gpu-threads=4`.

**Comment by phineas-pta** [comment]
other error people may get if setting `gpu-threads` too high

```
[E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Conv node. Name:'Conv_612' Status Message: /onnxruntime_src/onnxruntime/core/common/safeint.h:17 static void SafeIntExceptionHandler<onnxruntime::OnnxRuntimeException>::SafeIntOnOverflow() Integer overflow

[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Conv node. Name:'Conv_612' Status Message: /onnxruntime_src/onnxruntime/core/common/safeint.h:17 static void SafeIntExceptionHandler<onnxruntime::OnnxRuntimeException>::SafeIntOnOverflow() Integer overflow
```
