### ISSUE TITLE
can not run succeed

### ISSUE THREAD

**Issue by SuperRiceMan** [s0md3v/roop#342]
**Describe the bug**
The error you encountered is an AssertionError raised in the FaceAnalysis class. The FaceAnalysis class requires a model named 'detection' to be present in the self.models dictionary, but it seems that the model is missing.

**To Reproduce**
1. Run the run.py
2. Select  a face image and video
3. Click on 'Start'

**Details**
What OS are you using?
- [ ] Windows 10

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA

**Screenshots**
Exception in Tkinter callback
Traceback (most recent call last):
  File "F:\Anaconda\envs\new_torch\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "E:\deepLearining\roop-main\roop\core.py", line 285, in <lambda>
    start_button = tk.Button(window, text="Start", bg="#f1c40f", relief="flat", borderwidth=0, highlightthickness=0, command=lambda: [save_file(), start()])
  File "E:\deepLearining\roop-main\roop\core.py", line 198, in start
    test_face = get_face_single(cv2.imread(args['source_img']))
  File "E:\deepLearining\roop-main\roop\analyser.py", line 16, in get_face_single
    face = get_face_analyser().get(img_data)
  File "E:\deepLearining\roop-main\roop\analyser.py", line 10, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=roop.globals.providers)
  File "F:\Anaconda\envs\new_torch\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError
**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by henryruhs** [comment]
Nothing we can do in our side, another Python progress seems to be open and blocking it!?

**Comment by SuperRiceMan** [comment]
> Nothing we can do in our side, another Python progress seems to be open and blocking it!?

I don't know what to do,I just run the run.py without other progress

**Comment by henryruhs** [comment]
Join Discord for help, impossible to solve platform issues in a GitHub issue
