### ISSUE TITLE
ffmpeg audio processing

### ISSUE THREAD

**Issue by K1llMan** [s0md3v/roop#343]
For now ffmpeg fully render new file with audio. I think we can simply copy input audio and merge with output in seconds without hours of encoding.

Two commands I use:
```
        # Extract audio
        run_ffmpeg(f'-i "{input}" -vn -acodec copy "{input_audio}.aac"')
```
```
        # Merge output video and audio
        if os.path.isfile(input_audio):
            run_ffmpeg(f'-i "{output}" -i "{input}.aac" -c copy "{out_audio}"')
```

**Comment by AntwaneB** [comment]
I think this will only work if you keep the same FPS, but if you change the FPS (limit to 30 for example) then the audio will not be synchronized anymore.

**Comment by henryruhs** [comment]
@AntwaneB good point

**Comment by K1llMan** [comment]
> if you change the FPS (limit to 30 for example) then the audio will not be synchronized anymore.

Can't it be solved by 'atempo' audio filter?
