### ISSUE TITLE
Can't work on gpu, maybe mine doesnt work idk

### ISSUE THREAD

**Issue by MineBorder10444** [s0md3v/roop#350]
I am getting this error everytime: 
usage: run.py [-h] [-f SOURCE_IMG] [-t TARGET_PATH] [-o OUTPUT_FILE] [--keep-fps] [--keep-frames] [--all-faces]
              [--max-memory MAX_MEMORY] [--cpu-cores CPU_CORES] [--gpu-threads GPU_THREADS]
              [--gpu-vendor {apple,amd,intel,nvidia}]
run.py: error: ambiguous option: --gpu could match --gpu-threads, --gpu-vendor

**Comment by K1llMan** [comment]
Set flag --gpu-vendor instead --gpu. It's removed.

**Comment by MineBorder10444** [comment]
> Did you try to read the message? 😁

Sorry, I'm very new to this stuff.

**Comment by MineBorder10444** [comment]
> Set "--gpu-vendor nvidia" or other options in list instead "--gpu". It's removed.

This worked thankyou!
