### ISSUE TITLE
any models which keep facial accessories (eyeglasses, tatoo, etc.) ?

### ISSUE THREAD

**Issue by phineas-pta** [s0md3v/roop#354]
the current model erases any facial accessories (eyeglasses, tatoo, etc.), is there any models to keep them ?

for e.g.:
 - face: https://unsplash.com/photos/FN8Jx5WwOsU (face with tatoo and sunglasses)
 - target: https://www.youtube.com/watch?v=FaNkyVS2JjI

current output: lost tatoo and sunglasses
![image](https://github.com/s0md3v/roop/assets/37548991/c280ba58-1268-4618-b91f-fa34767918a5)

**Comment by henryruhs** [comment]
This is out of project scope as we are not the model creators. Sorry
