### ISSUE TITLE
'Cancel' button starts swapping process anyway

### ISSUE THREAD

**Issue by oneafter909** [s0md3v/roop#361]
When I press 'Cancel' button on 'Save Dialog' the swapping process starts anyway.

**To Reproduce**
1. Select Source IMG and Target
2. Press 'Start'
3. When the save dialog appears press 'Cancel'

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ x] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ x] Mac

**Comment by henryruhs** [comment]
Thank you for pointing this out, I'm working on a massive UI refactoring and will take care of that. Please reopen if this does not land in the next branch soon.
