### ISSUE TITLE
#162 should be reopened

### ISSUE THREAD

**Issue by jjangga0214** [s0md3v/roop#362]
> That being said, the args are a bit misleading but I get like 15 fps on the M1 Air using:
>```
>./run.py --gpu-vendor=apple --gpu-threads=16
>```

_Originally posted by @henryruhs in https://github.com/s0md3v/roop/issues/162#issuecomment-1576466447_

This does not work on M1 MAX. Only CPUs are used. Why should the issue be locked?

**Comment by henryruhs** [comment]
Because `onnxruntime-silicon` is using CPU only... the GPU flag is misleading... it is actual a acceleration/execution provider.
