### ISSUE TITLE
I got freeze after collect frames

### ISSUE THREAD

**Issue by leon23794** [s0md3v/roop#366]
I got freeze after collect frames

**Comment by henryruhs** [comment]
Are you on main?

**Comment by rogerb831** [comment]
I'm seeing this also when working with anything longer than a short test video.

**Comment by Rikoze777** [comment]
same problem. 100%|████████████████████████████████████| 17922/17922 [00:21<00:00, 838.43it/s] . after that nothing happens. Use cpu

**Comment by henryruhs** [comment]
This is the NSFW filter guys...
