### ISSUE TITLE
Suggestion: Add a que system

### ISSUE THREAD

**Issue by MineBorder10444** [s0md3v/roop#368]
I believe it would be beneficial to implement a queue system for face swaps, despite the possibility of sounding needy. Considering the ease and quickness with which these swaps can be performed, having a queue that allows for multiple videos to undergo the process would be highly advantageous. Currently, I find it quite tiring to wait and repeat the steps for each batch of clips, which typically range from 5 to 20 seconds. It would be immensely helpful if I could complete all these steps in a single session instead of having to return to my computer after each individual swap. While I understand this feature may not be considered essential, I must admit that it would also cater to my laziness.

**Comment by henryruhs** [comment]
Sorry but out of project scope, someone could build this using our CLI.
