### ISSUE TITLE
I get: OSError: Unable to open file (file signature not found) after first success 

### ISSUE THREAD

**Issue by andreaaraya01** [s0md3v/roop#370]
**Describe the bug**
I realize all steps with GPU use and after my first success test with the generated video I got now the message in console: "OSError: Unable to open file (file signature not found)", I restart my computer and problem persist, It is a problem with python version?

**To Reproduce**
1. open proyect in visual studio code
2. execute python run.py
3.select image and video to swap and clic start and save output.mp4
4. See error in vs code terminal

**Details**
What OS are you using?
- [x ] Windows 
- 
Are you try to use a GPU?
- [x ] NVIDIA (GTX 1080)

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by henryruhs** [comment]
Could you please join our Discord? I cannot help everyone individually

**Comment by niehaikuo** [comment]
I got the same error, how do you solve it？
