### ISSUE TITLE
关于如何提升效果

### ISSUE THREAD

**Issue by IamJasonBoy** [s0md3v/roop#372]
**Describe your suggestion**

关于效果 可以给一些建议吗
如 GPU > CPU 图片分辨率应该多少  被替换的图片/视频应该达到什么要求

**Comment by RickyWang111** [comment]
我也想知道。在哪里设置，不过看作者写的计划未来提高画质。

**Comment by henryruhs** [comment]
Reopen in english and with a proper description of your problem is. You find help at our Discord server as well.
