### ISSUE TITLE
Support to pausing and resuming execution

### ISSUE THREAD

**Issue by pozitronik** [s0md3v/roop#377]
The main idea is to give users the possibility to interrupt the current process and resume it later. This can be implemented through files that store the process's current state, including the parameters it was launched with, the current step, the frame number at which the replacement process was interrupted, and more. By default, such a file can be saved in the script directory and automatically loaded on the next run, allowing the process to continue from where it was stopped. Alternatively, the path to such a file can be passed as a parameter.

The idea can also be implemented by simply specifying launch parameters. For example:
`python run.py --face="face_path.jpg" --target="target_path.mp4" --output="result_path.mp4" --resume=swapping --frame=100500`

I think, you got the idea.

**Comment by pozitronik** [comment]
> Okay but what is the actual use case?

Uhm, sometimes I just need to do that. I can start a long swapping process and then realize I need to switch to a different task while it is running. In such situations, I have to cancel the swapping process and lose all the progress made.

I agree, this may not be a primary feature, but it's acceptable to make a suggestion, isn't it?

**Comment by henryruhs** [comment]
A destroy button landed in the next branch, but I don't see resumability coming to be honest. This is an interesting coding challenge but I prefer to focus on other things.

**Comment by pozitronik** [comment]
> Sure, you can use:
> 
> `multiprocessing.Event` and `threading.Event` for that. Essential in CPU mode we do multi processing and GPU we do multi threading.

There is no need to save the state of the threads/processes themselves. I have taken a different approach, where it is sufficient to store only the progress and parameters. You can see this in the draft: #408.

**Comment by henryruhs** [comment]
@pozitronik Indeed, the more I think about it, the more your approach makes sense as you can actual shutdown your PC and continue with the processing the next day.

Let me give this an review tomorrow. Thanks

**Comment by pozitronik** [comment]
Perhaps there was a misunderstanding, but I never agreed on implementing it specifically via events. It's possible that we approached the task from different angles, and that's fine.
Regarding my solution: I do indeed save the overall state after each successfully modified frame. The advantage of this approach is that the process can be interrupted smoothly at any moment, whether accidentally or intentionally. The drawback is the constant disk writes, but the amount of data is insignificant compared to the gigabytes of overwritten frames.
There is still room here for implementing any realtime adjustments. You can simply save the updated state; I don't see any issues with that.

**Comment by pozitronik** [comment]
TODOS:

- [ ] Support for multiple processors (to handle different types of processing).
- [ ] Change the way frames are stored by keeping unprocessed frames instead of processed ones.
- [ ] The argument `--keep-frames` should be renamed to `--keep-project` or `--keep-temp`.
- [ ] Automatically continue processing for the known target, if its temp directory is present.
- [ ] Keep the current step in the state.
- [ ] Add methods to simplify state handling like `prepare()` and `persist()`

Overall, a more clear and unambiguous behavior is required. I need to think about it.

**Comment by henryruhs** [comment]
Planned via https://github.com/s0md3v/roop/issues/629
