### ISSUE TITLE
Packages absent

### ISSUE THREAD

**Issue by JulianTierno** [s0md3v/roop#38]
_Warning: Package '**insightface.thirdparty.face3d.mesh.cython**' is absent from the `packages` configuration.
Warning: Package '**insightface.data.images**' is absent from the `packages` configuration.
_Warning: Package '**insightface.data.objects**' is absent from the `packages` configuration.

**Comment by s0md3v** [comment]
This isn't a part of **roop**. You have figure out prerequisites yourself.

**Comment by s0md3v** [comment]
Your error contains the solution:
```
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
```
