### ISSUE TITLE
[Feature] Allow an image to be provided as target

### ISSUE THREAD

**Issue by flesler** [s0md3v/roop#382]
It's maybe a bit divergent from the "main" use case, but you can probably support replacing just a single image (frame) without many changes and it'd be a nice feature.

Here are 2 use cases:
- Simply deepfake a photo
- Manually tweak frames previously generated by roop, before reassembling into a video

This is similar though not exactly the same as #282. I suppose if you support a directory of images, like in the other ticket, then putting the one image in a directory would be a workaround

**Comment by flesler** [comment]
This is similar though not exactly the same as #282. I suppose if you support a directory of images, like in the other ticket, then putting the one image in a directory would be a workaround

**Comment by flesler** [comment]
I just saw [this](https://github.com/s0md3v/roop/issues/282#issuecomment-1574035766), is this already supported? I didn't see it in the docs

**Comment by henryruhs** [comment]
Image to Image works, just try it
