### ISSUE TITLE
Everything including example works but when i use my own video, the program does not porcess to save

### ISSUE THREAD

**Issue by tangyiwei008** [s0md3v/roop#387]
**Describe the bug**
A clear and concise description of what the bug is

I am a starter and I know little about programming
**when i use the example it shows follows and worked well**
100%|██████████████████████████████████████████████████████████████████████████████████| 24/24 [00:00<00:00, 38.73it/s]
Processing:   0%|                                                                            | 0/24 [00:00<?, ?frame/s]Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Processing: 100%|███████████████████████████████████████████████████████████████████| 24/24 [00:05<00:00,  4.09frame/s]
Stream map '1:a:0' matches no streams.
To ignore this, add a trailing '?' to the map.

Video saved as: D:/deepface/face/roop/.github/examples/123213.MP4

**but when I use my own video it does not save as output**

100%|█████████████████████████████████████████████████████████████████████████████| 1486/1486 [00:02<00:00, 597.43it/s]

**the process just stop there and no output**

and during the process it also does not create a folder which contains frames
but the "preview" still works
**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ 1] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ 1] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [1 ] I have the latest code from the github repository
- [1 ] I have followed the installation guide

**Comment by henryruhs** [comment]
NSFW filter kicked in

**Comment by salva133** [comment]
Ok how to avoid that?

**Comment by henryruhs** [comment]
by not using porn
