### ISSUE TITLE
Error while trying to change from source image to target video :more details in description

### ISSUE THREAD

**Issue by anishjain94** [s0md3v/roop#39]
I follwed the instructions on you repo. i was able to use it to change faces in images. but while using video it gave me an error. attaching video of the same. 

https://github.com/s0md3v/roop/assets/25664697/425b1d6f-ab51-47bf-9678-b1d9ebab88f9

**Comment by s0md3v** [comment]
I don't have a MAC so I don't know if this is something that should be fixed from my end or is an issue in your system.

Download the latest code from here and try again. That's all I have to offer.
