### ISSUE TITLE
Error: Failed to Build Wheel for Insightface Package - Unable to Install Requirements

### ISSUE THREAD

**Issue by salva133** [s0md3v/roop#390]
**Describe the bug**
Issue like in https://github.com/s0md3v/roop/issues/99, no solution that was suggested there worked, and the issue got closed for no obvious reason.

**To Reproduce**
pip install insightface or installing the requirement**s**.txt in the roop dir

ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Sanity Check**
- [X] I have the latest code from the github repository
- [X] I have followed the installation guide

**Comment by salva133** [comment]
After re-installing the whole VS package + installing the C/C++ extension in VS Code it worked. Don't know what of the both things I did exactly helped, and I don't care. It works.

**Comment by VictorZakharov** [comment]
@salva133 What's this error?

```
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Iinsightface/thirdparty/face3d/mesh/cython -IC:\Users\Victor\AppData\Local\Temp\pip-build-env-015lvhc5\overlay\Lib\site-packages\numpy\core\include -Ig:\Git\roop\venv\include -IC:\Users\Victor\AppData\Local\Programs\Python\Python310\include -IC:\Users\Victor\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /EHsc /Tpinsightface/thirdparty/face3d/mesh/cython/mesh_core.cpp /Fobuild\temp.win-amd64-cpython-310\Release\insightface/thirdparty/face3d/mesh/cython/mesh_core.obj
      mesh_core.cpp
      C:\Users\Victor\AppData\Local\Temp\pip-install-vjx13wsz\insightface_8a73057846cd4632bcbc4645a2617d75\insightface\thirdparty\face3d\mesh\cython\mesh_core.h(4): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
```

**Comment by VictorZakharov** [comment]
I figured it out, needed to install complete C++ dev workload, without skipping anything, which is >6GB of stuff.
Would be great to minimize those additional dependencies.
