### ISSUE TITLE
[Bug] When the source is an image, --all-faces is ignored

### ISSUE THREAD

**Issue by flesler** [s0md3v/roop#393]
**Describe the bug**
When the source is an image, --all-faces is ignored. It calls `process_img` instead of `process_frames` which doesn't support multiple faces

**To Reproduce**
1. Run it such that the photo, source and destination and photos
2. Use an image with multiple faces
3. Only 1 is replaced

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by flesler** [comment]
Attached a PR that fixes the issue, tested with several multi-face images in CLI mode

**Comment by henryruhs** [comment]
thanks for finding this bug, please open a new PR for next and be aware it is `--many-faces` now.

**Comment by flesler** [comment]
Ok, feel free to just do the same change in the new branch. Should be the same :+1:

**Comment by henryruhs** [comment]
Fixed in next branch
