### ISSUE TITLE
The program is stuck and not responding during its execution

### ISSUE THREAD

**Issue by guanxing20** [s0md3v/roop#397]
**Describe the bug**
The program is stuck and not responding during its execution，I am using Python version 3.10.1 and pip version 21.2.4 on Windows 10. I have encountered the same issue on two different computers.The program always get stuck at the 'set det-size: (640, 640)' and '100%|███████████████████████████████████████████████████████████████████████████████| 528/528 [00:03<00:00, 168.52it/s]' messages in subsequent attempts. Regardless of how long I wait, the program does not continue to execute. The issue is consistent across both computers and I'm not sure what could be causing it.

**To Reproduce**
 Click on “start”

**Details**
What OS are you using?
Windows 

Are you try to use a GPU?
NVIDIA

**Screenshots**
![image](https://github.com/s0md3v/roop/assets/89514408/23e736bc-fe8c-4738-bae3-233d66cc871c)

**Sanity Check**
- [yes] I have the latest code from the github repository
- [yes ] I have followed the installation guide

**Comment by henryruhs** [comment]
NSFW filter kicking in
