### ISSUE TITLE
(f"CUDA version {CUDA_VERSION} is not supported - please downgrade to 11.8")

### ISSUE THREAD

**Issue by Deathcrash** [s0md3v/roop#398]
**Describe the bug**
I'm trying to start and start rendering, but this error is displayed, and there was no such error on older versions of your program

**To Reproduce**
1. start = create error

**Details**
What OS are you using?
 Windows  10

Are you try to use a GPU?
No. I am not using the `---gpu` flag

**Sanity Check**
+ I have the latest code from the github repository
+ I have followed the installation guide

error

```
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from roop import core
  File "C:\Code\PYTHON\roop-main4.0\roop\core.py", line 105
    quit(f"CUDA version {CUDA_VERSION} is not supported - please downgrade to 11.8")
                                                                                  ^
SyntaxError: invalid syntax

```

**Comment by Deathcrash** [comment]
and i have error

`Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from roop import core
  File "C:\Code\PYTHON\roop-main4.0\roop\core.py", line 105
    quit(f"CUDA version {CUDA_VERSION} is not supported - please downgrade to 11.8")
                                                                                  ^
SyntaxError: invalid syntax
PS C:\Code\PYTHON\roop-main4.0> python3`

**Comment by Deathcrash** [comment]
PS C:\Code\PYTHON\roop-main4.0> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
PS C:\Code\PYTHON\roop-main4.0>

**Comment by Deathcrash** [comment]
i have laptop 3060 rtx

**Comment by Deathcrash** [comment]
![2023-06-09_11-02](https://github.com/s0md3v/roop/assets/35882809/5688798a-e312-4265-b637-cf59143b0d3a)

**Comment by Deathcrash** [comment]
![image](https://github.com/s0md3v/roop/assets/35882809/cdfc706d-0e0a-47a2-b0ea-77bdb9c376f7)

**Comment by Deathcrash** [comment]
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

not help...

**Comment by Deathcrash** [comment]
DELETE PLEASE

**Comment by Deathcrash** [comment]
C

**Comment by Tam66662** [comment]
@Deathcrash I'm getting this exact same error. What did you do to fix it before you closed this issue?
