### ISSUE TITLE
"FileNotFoundError" when close app window (on Macbook M1)

### ISSUE THREAD

**Issue by wowueh** [s0md3v/roop#402]
**Describe the bug**
When close app window --> FileNotFoundError (the "temp" folder is not found)
Here after is the Terminal debug log:

**To Reproduce**
1. Use app to swap faces
2. When all done, Click on close window button
3. See error on Terminal

**Details**
What OS are you using?
- [ ] Macbook M1, Ventura

Are you try to use a GPU?
- [ ] Mac

**Screenshots**
![Ảnh màn hình 2023-06-09 lúc 14 34 31](https://github.com/s0md3v/roop/assets/19222815/f2bae581-3ab6-4ac4-83c0-41dd6c37d10b)

**Sanity Check**
- [ ] I have the latest code from the github repository, branch "Next"
- [ ] I have followed the installation guide

**Comment by henryruhs** [comment]
Should be fixed in latest next branch
