### ISSUE TITLE
Use ffmpeg wrapper instead of commands

### ISSUE THREAD

**Issue by K1llMan** [s0md3v/roop#403]
Use something like that https://github.com/kkroening/ffmpeg-python to ffmpeg operation. It's easier to use instead of all ffmpeg flags and can be usefull for upcoming operations like range processing.

**Comment by henryruhs** [comment]
Yes, makes sense!

**Comment by phineas-pta** [comment]
i'd say the opposite, see this comment
https://github.com/openai/whisper/pull/1242#issue-1670018817

**Comment by K1llMan** [comment]
https://github.com/jonghwanhyeon/python-ffmpeg

**Comment by phineas-pta** [comment]
nice 👍 it even has async support

**Comment by henryruhs** [comment]
It would be helpful to evaluate the lib I'm terms of performance. That would help a lot for a consideration.

**Comment by phineas-pta** [comment]
they're both wrappers around `subprocess` so speed shouldn't matter much

the importance is how difficult to convert existing code

**Comment by henryruhs** [comment]
I keep this in mind, at the moment we are using subprocess as well and I recently refactored it.

**Comment by phineas-pta** [comment]
the real python binding without `subprocess` is https://github.com/PyAV-Org/PyAV

but its installation may be complicated because it compiles ffmpeg
