### ISSUE TITLE
[Feature Request] - (Low Priority) On Completion Review & Reprocess of Selected Frame

### ISSUE THREAD

**Issue by bootlegchan** [s0md3v/roop#416]
The concept would be to use the established preview function to review the video on completion within that preview. Then the added function of being able to select a frame that is incorrect and try re process it. This is specifically for skipped frames or poorly matched ones. 

If it would be possible to even switch the face-image used for the single selected frame with a more appropriate angle or expression. 
Batching would be nice to select more than one frame to do this one but not necessary as the likely hood of 10+ frames needing re processing is low.

Another option would be to have this review step optionally happen, at the stage where the face-swap has happened but before the video is remerged.

**Comment by henryruhs** [comment]
Out of project scope... closed
