### ISSUE TITLE
insightface model only output 112x112 px image

### ISSUE THREAD

**Issue by koolou** [s0md3v/roop#420]
The model "inswapper_128.onnx" of InsightFace can only output images with a resolution of 112x112. Is there any way to output high-definition images?

**Comment by henryruhs** [comment]
Using inswapper_512.onnx that is not public :-)

**Comment by MantisTree** [comment]
> inswapper_512.onnx

Are you aware of anyone with that model? :D

**Comment by henryruhs** [comment]
@MantisTree See https://github.com/deepinsight/insightface/issues/2270
