### ISSUE TITLE
Overlapped face in objects

### ISSUE THREAD

**Issue by wokege159** [s0md3v/roop#425]
It is possible to create a code where overlapped swapped faces get masked by the detected objects that should appear in front of the face, like this mouth that's covering the apple?

https://github.com/s0md3v/roop/assets/135330623/349ef274-ebdb-4826-a6db-bf549ba88886

**Comment by henryruhs** [comment]
I cannot open your video but from the text I can tell you there is nothing we can do about it. We are not the creators of the model.
