### ISSUE TITLE
[NEXT] Wrong fps detection on some videos

### ISSUE THREAD

**Issue by pozitronik** [s0md3v/roop#427]
The `next` branch is used.
I have discovered that the `detect_fps()` method returns incorrect values for certain videos. Upon investigation, I found that the command `ffprobe -v error -select_streams v:0 -show_entries stream=r_frame_rate -of default=noprint_wrappers=1:nokey=1` is used to determine the FPS. I executed this command for one of the problematic files and indeed received a strange value (240). When i use a ffmpeg to determine the video parameters (`ffmpeg -i`), it returns correct fps value (~60) and shows that 240 is the *tbr* value (which means a 'time base of the stream') actually.

![изображение](https://github.com/s0md3v/roop/assets/2357892/5ecb915c-ffb2-4c2b-ba51-014eea573ffa)

Here is a file on which it can be reproduced.

https://github.com/s0md3v/roop/assets/2357892/e7444d35-ab64-444b-8706-8e180b04b79c

**Comment by henryruhs** [comment]
That is a known issue... please don't open bugs for next

**Comment by pozitronik** [comment]
Maybe it's not necessary to close issues like this if they haven't actually been completed yet? In that case, there should be fewer duplicate requests.

**Comment by henryruhs** [comment]
Next branch is under development. If we track every bug there would be like 10 more issues.

Will now add NEXT to those issues instead of closing them.

**Comment by pozitronik** [comment]
You may use issue labels as well.

**Comment by henryruhs** [comment]
Fixed via https://github.com/s0md3v/roop/commit/fca95bc9b90087fe01f8066f487e69aba4167e75
Founded and tested by user Robot - Thanks

**Comment by moeunderwood** [comment]
> Fixed via [fca95bc](https://github.com/s0md3v/roop/commit/fca95bc9b90087fe01f8066f487e69aba4167e75) Founded and tested by user Robot - Thanks

Change the fps type from int to str, for example: 2997/100

Using int type for fps is not accurate enough, causing slight differences in the length of the generated video compared to the original video, resulting in a slight deviation in the audio track. Changing fps to str type can solve this problem.

PR already created for this.

Robot
