### ISSUE TITLE
Process got stuck after counting frames

### ISSUE THREAD

**Issue by Leon-0819** [s0md3v/roop#431]
![20230611161827](https://github.com/s0md3v/roop/assets/130751334/d55a7efc-4a91-46ec-9f65-a9024182335c)
**Describe the bug**
After choose the where to put the output video, console showed it counted all the frames, 3235 in my case, after that nothing happened, waited for more than 10 mins, still nothing.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X ] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [X ] NVIDIA [3060ti]
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [X ] I have the latest code from the github repository
- [X] I have followed the installation guide

**Comment by henryruhs** [comment]
NSFW filter
