### ISSUE TITLE
[NEXT] Enhancer download problem

### ISSUE THREAD

**Issue by K1llMan** [s0md3v/roop#432]
Enhancer already has weight in roop directory
![image](https://github.com/s0md3v/roop/assets/13403439/bfe30b07-77d4-4d97-97cb-cb1b150e4ca7)
But after start processing dowloading starts again to Python directory
![image](https://github.com/s0md3v/roop/assets/13403439/0470194e-0552-4052-b959-45d8ad2f22f0)

**Comment by henryruhs** [comment]
The enhancer needs a [precheck](https://github.com/s0md3v/roop/blob/next/roop/swapper.py#L16-L18) like the swapper has already using `conditional_download()` from utilities. You can give it a try via a PR or I'll fix this later these days.
