### ISSUE TITLE
Last version having issues related to GPU VRAM?

### ISSUE THREAD

**Issue by AlonDan** [s0md3v/roop#433]
**4GB VRAM is not enough anymore**
I just tried this (latest version) and it works very slow, compare to the version before,
I get ONNXRuntimError and it takes so long to process 1 frame.

Compare to the version before which was very fast and my GPU with 4 VRAM was enough never have these errors.

Since I'm using an Nvidia GTX card this is how I ran it on anaconda:
`run.py --gpu-vendor nvidia`

The version before I used this:
`run.py --gpu`

I ran it on default settings (out of the box version)
I didn't use the memory options since I don't understand exactly (sorry I'm not a programmer) maybe it's simple to just put a number limiting to 4GB VRAM and it will be as fast as it was on the version before, I just don't know exactly how or what to type in when running in anaconda so I couldn't test it.

---
UPDATE:
I've tried once again this time:
`run.py --gpu-vendor nvidia --max-memory 2`
and also with 1 (just because I was curious)

Then I realize it's for RAM not GPU RAM (my bad) and I just not used it, If I get it right the default will just use all available RAM? (I have 32GB RAM)

It doesn't matter, I probably don't know how to use the right GPU settings with the new version and the new parameters added.
It seems to read the first read-process works fast, but the 2nd phase of actually swapping the faces in the directory start flood with messages the memory I show in the screenshot, and it the end result video just will be as the source WITHOUT the face.

Unfortunately I don't know how to use the GPU Threads new command, to be exact: I don't know what number even should I insert based on my VRAM limitation, so I can't test it.

Until it's fixed, I will get back to the version before until it's fixed because it was just much faster, worked by default and had no memory issues with my 4GB VRAM GPU.

---
**To Reproduce**
1. just run it normally and press: 'Start'
2. The new Preview feature seems to work great

**Details**
What OS are you using?
- [x] Windows 

Are you try to use a GPU?
- [x] NVIDIA

**Screenshots**
![cmd_2023-06-11_14-22-05](https://github.com/s0md3v/roop/assets/21152334/2556f67c-0b6f-475a-bd3c-7d72de159005)

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by henryruhs** [comment]
This are individual platform issues that I cannot support via GitHub - please use Discord, the community is very helpful

**Comment by pichugin-i** [comment]
Я столкнулся с этой проблемой. Чтобы этого избежать, просто используйте команду:
python run.py --gpu-vendor nvidia --max-memory 2000 --gpu-threads 3

Изменяйте параметр --gpu-threads 3, в большую сторону или в меньшую.
--gpu-threads это количество потоков

**Comment by AlonDan** [comment]
Thanks @pichugin-i it seems like the --gpu-threads 3 does the job!

I didn't use the --max-memroy 2000 as you suggested because I guess my 32GB RAM is enough, I hope I'm not wrong in that but I'm still experimenting.

**Comment by pichugin-i** [comment]
I advise you not to use your maximum memory. Make 25,000. It is because of the maximum memory usage that some information is lost and goes beyond 32GB
