### ISSUE TITLE
Ammend wiki to include DirectML when next branch is merged

### ISSUE THREAD

**Issue by andrewcharlwood** [s0md3v/roop#435]
Editing the GPU AMD installation method to the following:

# AMD
### Linux:
Follow basic instructions [here](https://github.com/s0md3v/roop/wiki/1.-Installation), then:
```
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2
pip uninstall onnxruntime onnxruntime-gpu
git clone https://github.com/microsoft/onnxruntime && cd onnxruntime
./build.sh --config Release --build_wheel --update --build --parallel --cmake_extra_defines CMAKE_PREFIX_PATH=/opt/rocm/lib/cmake ONNXRUNTIME_VERSION=$ONNXRUNTIME_VERSION onnxruntime_BUILD_UNIT_TESTS=off --use_rocm --rocm_home=/opt/rocm
pip install build/Linux/Release/dist/*.whl
```

### Windows:
ROCm is currently not supported on windows directly or via WSL. As an alternative, DirectML although slower than ROCm on  Linux, runs natively on Wndows. Follow basic instructions [here](https://github.com/s0md3v/roop/wiki/1.-Installation), then:
```
pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime-directml
```

**Comment by henryruhs** [comment]
Sorry, but I not gonna repeat a perfect documentation for 14 execution providers that can be found elsewhere... 
https://onnxruntime.ai/docs/execution-providers

I would rather prefer if someone is trying to use directml - to check for the `onnxruntime-directml` to be installed and print this to the console. PR is welcome. Thanks
