### ISSUE TITLE
Encoder selection is broken

### ISSUE THREAD

**Issue by pozitronik** [s0md3v/roop#437]
I see some strange decisions in #423.
First, you limit users from selecting their preferred encoder, which directly contradicts what you said: "[Let the user decide what encoder to use.](https://github.com/s0md3v/roop/issues/376#issuecomment-1581280834)"
Second, there is no encoder named `nvenc` in FFmpeg. If you try to use the `--video-encoder=nvenc` parameter, you won't get any results. The correct encoder names are `h264_nvenc`, `av1_nvenc`, and `hevc_nvenc`. It's important to use the correct encoder names when working with FFmpeg.

_Originally posted by @pozitronik in https://github.com/s0md3v/roop/issues/423#issuecomment-1586172176_

**Comment by henryruhs** [comment]
Limited it `['libx264', 'libx265']` to until a solution for the Constant Rate Factor aka `-crf` is not supported by every encoder has been found.

**Comment by phineas-pta** [comment]
@henryruhs i really think you don't need to unify all different ffmpeg quality controls, this make your program too rigid

to make it flexible, here my proposal:

both options `--video-encoder` & `--video-quality` should be marked *"for experienced ffmpeg users only"*

`--video-encoder` then takes any valid `-c:v` encoder, default value is `libx264`

`--video-quality` accepts any additional inputs from user, default value is `-crf 7 -pix_fmt yuv420p`

then if have time to write docs, you can add details about quality options for each encoder
