### ISSUE TITLE
Codeformer vs. PSFRGAN

### ISSUE THREAD

**Issue by C0untFloyd** [s0md3v/roop#440]
I've been toying around with the Next Branch and the Codeformer Postprocessing. While Codeformer currently is the top dog when it comes to restoring faces, the results are IMHO quite generic and loose distinct features. For this reason I guess the lesser known
[https://github.com/mindslab-ai/hififace](https://github.com/mindslab-ai/hififace)
used PSFRGAN [https://github.com/chaofengc/PSFRGAN](https://github.com/chaofengc/PSFRGAN) which to my eyes performs better at keeping face features. Here's a comparison:

### Source
![Elon_Musk_Royal_Society_(crop2)](https://github.com/s0md3v/roop/assets/131583554/cd163b18-f818-47fa-ba63-f5d52e73308e)

### Target
![Jeff_Bezos_visits_LAAFB_SMC_(3908618)_(cropped)](https://github.com/s0md3v/roop/assets/131583554/d27b2215-cc79-4c59-baed-60476c9c68f0)

### Swap Result from Roop
![test](https://github.com/s0md3v/roop/assets/131583554/75ab4af9-a6e3-4d45-8070-7b6abd28f7d7)

### Image after preprocessing with CodeFormer
![output](https://github.com/s0md3v/roop/assets/131583554/0ebf6611-a361-4a01-8fce-3441e8a80835)

### Image after preprocessing with PSFRGAN
![hq_final](https://github.com/s0md3v/roop/assets/131583554/70056702-c0bc-4f2e-989b-89c4cf687cd9)

Perhaps we could integrate different engines for post-processing? A modular concept would be great.

Oh and a small missing feature in the Next-Branch is currently that you can't mix faceswapping and enhancement altogether because for enhancements the source-filenames are used instead of the outputs from previous swapping.

**Comment by henryruhs** [comment]
People can write their own frame-processor once NEXT branch is finished - we are working towards this.
