### ISSUE TITLE
[Performance] Dynamic frame selection for multithreading

### ISSUE THREAD

**Issue by fortypercnt** [s0md3v/roop#446]
When processing a lot a frames and using multithreading, processing speed drops more and more towards the end. This is because each thread is assigned some specific frames to process at startup and some frames can take longer to finish then others. So you end up with 1-2 threads that got a bunch of "difficult" frames holding everything up while the rest are idling.
This situation could easily be avoided by having the threads pick new frames to work on dynamically from a pool instead of assigning the frames at startup. I can provide an implementation for this if you want.

**Comment by henryruhs** [comment]
I do 16 multi threads on my GPU... not sure how you wanna improve that without turning the code into a mess.

**Comment by fortypercnt** [comment]
I provided a sample implementation in #460.

**Comment by henryruhs** [comment]
Has been solved via Thread Pools.
