### ISSUE TITLE
TF-TRT Warning: Could not find TensorRT.  Does this effect performance?

### ISSUE THREAD

**Issue by flydragon2018** [s0md3v/roop#447]
**Describe the bug**
W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

Does this effect performance?

The code works fine,  though with that warning.

**To Reproduce**

following the instruction

**Details**
What OS are you using?
- [ ] Linux
 

Are you try to use a GPU?
 
- [ ] NVIDIA
 

**Screenshots**

**Sanity Check**
- [ ] I have the latest code from the github repository

**Comment by henryruhs** [comment]
Nope, Tensor is disabled for the onnxruntime.

**Comment by flydragon2018** [comment]
onnxruntime-gpu==1.15.0; sys_platform != 'darwin'   in requirements.txt

shouldn't onnxruntime-gpu  be used?
