### ISSUE TITLE
tensorflow.python

### ISSUE THREAD

**Issue by FyF1k** [s0md3v/roop#448]
from tensorflow.python.tools import module_util as _module_util
ModuleNotFoundError: No module named 'tensorflow.python'

after installing the requested libraries

**Details**
What OS are you using?
- [ ] Windows 

Are you try to use a GPU?
- [ ] NVIDIA

**Screenshots**

**Sanity Check**
- [ ] I have the latest code from the github repository
- [ ] I have followed the installation guide

**Comment by henryruhs** [comment]
We cannot support platform specific support via GitHub issues. Please join Discord, we have a very helpful community.
