### ISSUE TITLE
Linux (Ubuntu) and Python 3.11 dependency conflicts 

### ISSUE THREAD

**Issue by bearney74** [s0md3v/roop#455]
**Describe the bug**
when running pip install -r requirements under ubuntu and python 3.11, I get the following error:

ERROR: Cannot install -r requirements.txt (line 4), -r requirements.txt (line 5), -r requirements.txt (line 6), numpy==1.23.5 and onnxruntime-gpu==1.15.0 because these package versions have conflicting dependencies.                                                             
                                                                                            
The conflict is caused by:
    The user requested numpy==1.23.5
    opencv-python 4.7.0.72 depends on numpy>=1.21.2; python_version >= "3.10"
    opencv-python 4.7.0.72 depends on numpy>=1.22.0; python_version >= "3.11"
    opencv-python 4.7.0.72 depends on numpy>=1.17.0; python_version >= "3.7"
    opencv-python 4.7.0.72 depends on numpy>=1.17.3; python_version >= "3.8"
    opencv-python 4.7.0.72 depends on numpy>=1.19.3; python_version >= "3.9"
    onnx 1.14.0 depends on numpy
    insightface 0.7.3 depends on numpy
    onnxruntime-gpu 1.15.0 depends on numpy>=1.24.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts 

The following requirements.txt file solves this issue:

--extra-index-url https://download.pytorch.org/whl/cu118

numpy==1.24.2
opencv-python==4.7.0.72
onnx==1.14.0
insightface==0.7.3
psutil==5.9.5
tk==0.1.0
pillow==9.5.0
torch==2.0.1+cu118; sys_platform != 'darwin'
torch==2.0.1; sys_platform == 'darwin'
onnxruntime==1.15.0; sys_platform == 'darwin' and platform_machine != 'arm64'
onnxruntime-silicon==1.13.1; sys_platform == 'darwin' and platform_machine == 'arm64'
onnxruntime-gpu==1.15.0; sys_platform != 'darwin'
tensorflow==2.13.0rc1
opennsfw2==0.10.2
protobuf==4.23.2
tqdm==4.65.0

**Comment by henryruhs** [comment]
Use Python 3.10 for now

**Comment by RamsaTech** [comment]
Any plans to mitigate this?

**Comment by henryruhs** [comment]
send a PR if you find a way how to lock the requirements.txt to 3.10 😉
