### ISSUE TITLE
Split UI and roop

### ISSUE THREAD

**Issue by K1llMan** [s0md3v/roop#465]
1. Provide events mechanism for constrolling roop process.
2. Extract UI into new repository. 
3. Import roop into UI as git module.
4. Give users possibility to make thier own UI in thier own way with classes, hacks, bad coding practices, etc. and use roop as module.
5. Optional: provide repository with good variants of execution roop in user environment such as UI, web, CLI.

**Comment by henryruhs** [comment]
Why different repositories, would never do something like this again. Monorepo is the way to go to reduce overhead for builds, version management and easier development.

**Comment by K1llMan** [comment]
It's not about a build. It's about project management. Git module pulled like regular repo but connected to repository what uses it by link. Ok if want to put UI in this repository. When split UI and roop with events to give devs possibility to integrate roop module into thiers UI without roop UI methods in core.

**Comment by henryruhs** [comment]
Believe me, monorepos way are easier. I can explain the benefits via PM.

**Comment by henryruhs** [comment]
@K1llMan Could you give us a wrap up how to split it and what the actual usecase is? Who gonna consume that how and why?

**Comment by K1llMan** [comment]
![roop](https://github.com/s0md3v/roop/assets/13403439/814d6081-4cba-428c-800a-1b5c7e459d78)
I think about this architecture.

**Comment by thewh1teagle** [comment]
I would split the program itself into rest API, using FastAPI.
and the UI into web application which uses fetch / axios to call the API.

tkinter is hard to work with, and even when you know what you doing - you get low quality results with that.

**Comment by henryruhs** [comment]
I disagree... with customtkinter (that we use in the next branch) you can produce an desktop UI within minutes that looks neat.

**Comment by henryruhs** [comment]
After talking with @s0md3v we decided that splitting up the app goes beyond the project scope. At least for now...
