### ISSUE TITLE
"The save file operation failed to connect to the open and save panel service." on Mac with Python 3.11

### ISSUE THREAD

**Issue by Kelicious** [s0md3v/roop#47]
This happens as soon as I click the Start button. Here is the terminal output: https://pastebin.com/VxUCa02u

**Comment by s0md3v** [comment]
Have you installed ffmpeg? @Kelicious

**Comment by Kelicious** [comment]
Thanks, reinstalling ffmpeg got it to work. I switched to an M2 Mac recently but the x86_64 binary for ffmpeg was still there from the previous Intel Mac. Now the error message is still there but I can see from the command line output that it's processing.
