### ISSUE TITLE
window preview fix

### ISSUE THREAD

**Issue by pichugin-i** [s0md3v/roop#473]
When the preview window is open, then when you select the path of a new photo, it closes.
Implement it so that it closes only when the user clicks the "Open" button when choosing the path of a new photo. Previously, it was possible to roughly estimate the photo based on the fact that the preview was already open.
It would also be super if after clicking "Open" (take the path to the new photo) the old preview has closed and the new one has opened.

**Comment by henryruhs** [comment]
That is not a bug, we made it like that.
