### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by samedovzaur** [s0md3v/roop#48]
![Screenshot 2023-05-30 at 00 31 57](https://github.com/s0md3v/roop/assets/101812544/d08b9122-394e-43c2-9cb1-2fb592a4fbdf)

when I did the generation part it just generated the png files not mp4 I dunno why? 
![Screenshot 2023-05-30 at 00 30 47](https://github.com/s0md3v/roop/assets/101812544/0816a29c-7997-4acb-9064-00b36183e032)

and for saving file it shows this on Mac M2 silicon

**Comment by s0md3v** [comment]
Copy your image and video to **roop** directory. Then, run the following command and show me the output:

```
python run.py -f <face image> -t <target video> -o output.mp4
```

**Comment by samedovzaur** [comment]
it didn't work out neither :(

**Comment by samedovzaur** [comment]
dude why did you close it ?

**Comment by s0md3v** [comment]
@samedovzaur post the output here so I can see whats wrong :/
