### ISSUE TITLE
RunPod tutorial I made , 25 it frames per second for 1280 pixel video

### ISSUE THREAD

**Issue by FurkanGozukara** [s0md3v/roop#482]
I think video can be added to wiki or main readme

[**How To Use Roop DeepFake On RunPod Step By Step Tutorial With Custom Made Auto Installer Script**](https://youtu.be/jD1ZSd9aFHg)

[![image](https://i.imgur.com/Qgyv3Kq.png)](https://youtu.be/jD1ZSd9aFHg)

**Comment by henryruhs** [comment]
I love your videos, but we not gonna add it to our readme.
