### ISSUE TITLE
Convenience of choosing a path

### ISSUE THREAD

**Issue by pichugin-i** [s0md3v/roop#486]
It would be cool if there were already folders Photos, Videos, Result in roop. And it would be enough to click "face selection" to immediately be in the right folder. Similarly with the video. After clicking on start, they were already in the Result folder to save the finished video.
If the user wants to save to another location, it will not be a problem to choose a different path. But default paths would be very convenient

**Comment by pichugin-i** [comment]
I forgot that another language)
It would be cool if there were already folders Photos, Videos, Result in roop. And it would be enough to click "face selection" to immediately be in the right folder. Similarly with the video. After clicking on start, they were already in the Result folder to save the finished video.

**Comment by henryruhs** [comment]
I was thinking to default to users home? Other opinions about this?

**Comment by henryruhs** [comment]
Merged to https://github.com/s0md3v/roop/issues/467
