### ISSUE TITLE
face_enhancer frame processor requires a image

### ISSUE THREAD

**Issue by pozitronik** [s0md3v/roop#487]
The issue about `next` branch.
When I run the script with the `--frame-processor face_enhancer` option but without any source image in the input, I receive an error message saying 'Select an image that contains a face'. However, `face_enhancer` doesn't require an image; it simply upscales the provided target.

I believe, any processor module being called should check the parameter list itself.

**Comment by henryruhs** [comment]
Good point... should we move that to the pre_check() of each frame processor?

**Comment by pozitronik** [comment]
Well, in my opinion, the implementation can be any, as it still needs to be rewritten into classes anyway.

**Comment by henryruhs** [comment]
Resolved via https://github.com/s0md3v/roop/pull/488

**Comment by pozitronik** [comment]
Seems like there are some issues here.
When I run the script with the `--frame-processor=face_enhancer` option but without specifying any source, I encounter a lot of warnings such as:
`[WARN:3@7.790] global loadsave.cpp:244 cv::findDecoder imread_(''): can't open/read file: check file path/integrity`
This is because the `face_enhancer.process_video` function requires the source_path parameter to be passed.
