### ISSUE TITLE
Any way or chance to increase picture quality?

### ISSUE THREAD

**Issue by FurkanGozukara** [s0md3v/roop#49]
The resolution is really really bad

I mean even with 640x360 video it is extremely visible 

Anyone figured out improving quality some how?

**Comment by s0md3v** [comment]
It is a limitation of the swapping model.

In a few days, I will try to integrate this tool to improve the faces: https://github.com/sczhou/CodeFormer

**Comment by FurkanGozukara** [comment]
> It is a limitation of the swapping model.
> 
> In a few days, I will try to integrate this tool to improve the faces: https://github.com/sczhou/CodeFormer

I tested code former on frame but then it changes the face

So limitation is 128x128 that is just too low

I see super high resolution deep face videos what method they are using?

**Comment by s0md3v** [comment]
@FurkanGozukara They collect thousands of images of the person's face train a model on it. We are doing it with a single image.

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara They collect thousands of images of the person's face train a model on it. We are doing it with a single image.

thank you for reply

you are right. if only 128 px resolution were bigger this is still super cool

i made this with facefix. my face nothing like john wick but still decent

waiting gpu pull request fix for tutorial

https://github.com/s0md3v/roop/assets/19240467/95eb7b9d-6e76-42eb-a214-f7170d3be6d3

**Comment by s0md3v** [comment]
@FurkanGozukara you will get much better results if your face is smaller i.e. is away from camera or has a lower resolution.

Good luck for the tutorial!

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara you will get much better results if your face is smaller i.e. is away from camera or has a lower resolution.
> 
> Don't worry, we will find a way to make faces clearer.
> 
> Good luck for the tutorial!

ye i noticed that :D i will capture a distant video 

thank you will hopefully post here

this is my channel : https://www.youtube.com/SECourses

ty for the repo

do you think authors of the model we use for faceswap will train a higher resolution or will there be any other?
