### ISSUE TITLE
ImportError: No module named 'Tkinter'

### ISSUE THREAD

**Issue by SkalskiP** [s0md3v/roop#5]
It would be cool to add information about installing `Tkinter`. It is not in `requirements.txt` and in the `README.md` :/ 

This solved my issue on Ubuntu: https://stackoverflow.com/questions/25905540/importerror-no-module-named-tkinter

I can add steps to `README.md` if you want :)

**Comment by noonesaid** [comment]
I'm on Ubuntu and am still having this issue. I tried everything in the link you provided, do you know what steps that worked for you?

I did `sudo apt-get install python3-tk`
I modified the core.py to have:
```
import sys
if sys.version_info[0] == 3:
    import tkinter as tk
else:
    import Tkinter as tk
```

But I get the error "Illegal instruction (core dumped)"

The command I use is python3 run.py. python run.py does not work.
