### ISSUE TITLE
[Draft] Uniform frame processor API

### ISSUE THREAD

**Issue by henryruhs** [s0md3v/roop#506]
- As not all frame_processors are equal we need to change the API of all hook methods a bit.

Examples:

```python
def process_frame({
   subject_image: ... # face, nose, hair can be optional
   temp_frame: ...   
})
```

```python
def process_image({
   subject_path: ... # face, nose, hair can be optional
   target_path: ...
   output_path: ...
})
```

- In best case the processors only contains frame processor methods - the rest is just forwarded

   1. process_frames() **should** forward to roop.processors.frame.core.process_frames()
   2. process_image() **should** forward to roop.processors.frame.core.process_image()
   1. process_video() **already** forward to roop.processors.frame.core.process_video()

- Introduce a `pre_process()` hook for extract frames or move it to `pre_start()` - so in-memory processors could skip that

- Introduce a hook that gives information what UI elements to render - the enhancer for example does not need a source face. Therefore the ui.py needs a resolve_ui_config() for the final elements to be rendered.

```python
def ui_config() -> List[str]:
   return ['select-source', 'select-target', 'button-preview']
```

- Replace related code in core.py and ui.py to new API.

**Comment by K1llMan** [comment]
```Python
def get_frame(target: str, frame_number: int = 0) -> Any:
    if is_image(target):
        return cv2.imread(target_path)

    cap = cv2.VideoCapture(target)
    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_number)
    ret, frame = cap.read()
    return frame


def get_frames(target: str) -> Any:
    if is_image(target):
        return cv2.imread(target_path)

    cap = cv2.VideoCapture(target)
    ret, frame = cap.read()
    while not ret:
        yield return frame
        ret, frame = cap.read()


def save(output: str, frame: Any) -> None:
    # Saving

def process_frame(source_face: Any, temp_frame: Any) -> Any:
    for frame_processor in get_frame_processors_modules(roop.globals.frame_processors):
        update_status('Progressing...', frame_processor.NAME)
        frame_processor.process_frame(source_face, temp_frame)


def process(source_face: Any, target: str, output: str, frame_number: int = -1) -> Any:
    if frame_number != -1:
        frame = get_frame(target, frame_number)
        return process_frame(source_face, frame)

    for frame in get_frames(target):
        frame = process_frame(source_face, frame)
        save(output, frame)
    release_resources()


# Return lambda with closure
def get_process_function(source: str, target: str, output: str) -> Callable:
    source_face = get_one_face(cv2.imread(source))

    return lambda n: process(source_face, target, output, n)
```

**Comment by shohag288** [comment]
> - As not all frame_processors are equal we need to change the API of all hook methods a bit.
> 
> Examples:
> 
> ```python
> def process_frame({
>    subject_image: ... # face, nose, hair can be optional
>    temp_frame: ...   
> })
> ```
> 
> ```python
> def process_image({
>    subject_path: ... # face, nose, hair can be optional
>    target_path: ...
>    output_path: ...
> })
> ```
> 
> - In best case the processors only contains frame processor methods - the rest is just forwarded
> 
>    1. process_frames() **should** forward to roop.processors.frame.core.process_frames()
>    2. process_image() **should** forward to roop.processors.frame.core.process_image()
>    1. process_video() **already** forward to roop.processors.frame.core.process_video()
> 
> - Introduce a `pre_process()` hook for extract frames or move it to `pre_start()` - so in-memory processors could skip that
> 
> - Introduce a hook that gives information what UI elements to render - the enhancer for example does not need a source face. Therefore the ui.py needs a resolve_ui_config() for the final elements to be rendered.
> 
> ```python
> def ui_config() -> List[str]:
>    return ['select-source', 'select-target', 'button-preview']
> ```
> 
> - Replace related code in core.py and ui.py to new API.
> 


I'm a cyber security consultant that is conducting and leading security audits, penetration testing engagements, and red team engagements to a variety of companies, ranging from enterprise-level companies to small start-ups.

Daily activities include, but are not limited to: penetration testing, red teaming, briefing, debriefing, other meetings.

Previously I did infrastructure management at an enterprise-level company where I was administrating three (3) active directory forests and did host-based incident response.

Certificates owned:
[+] CCNA Routing and Switching 1
[+] Cisco Cyber Operations Introduction
[+] Cisco Cyber Operations...

my WhatsApp number : +8801314956025

**Comment by janvarev** [comment]
It's still may be a good idea to use https://github.com/janvarev/chain-img-processor and transfrom frame processor to plugins.
Pros:
- Plugins can have their own options for advanced users (like upscale, strength etc.). So, they can adjust them without need for adding all of these options to command line args, or be hardcoded.
- Plugins process ONLY internal cv2 images. So, around stuff like video processing, mass image processing can be done only once in most effective way, and not be the problem of plugins.
