### ISSUE TITLE
Problem with non-latin symbols in paths under Windows

### ISSUE THREAD

**Issue by pozitronik** [s0md3v/roop#511]
Tried on the `next` branch on Windows 11 with Russian locale.
There is a bug when the source or target path contains any non-ASCII symbol. I reproduced it using Cyrillic and Mkhedruli (Georgian alphabet) symbols.
To reproduce the issue, rename any file to `тестовое видео.mp4` (or `ტესტი ვიდეო.mp4` for Mkhedruli) and use it as the target, either in console or GUI mode. As a result, you will receive a bunch of errors, one for every frame: `['NoneType' object has no attribute 'shape'
WARN:3@495.146] global loadsave.cpp:244 cv::findDecoder imread_('D:/WORK/data\temp\╤В╨╡╤Б╤В╨╛╨▓╨╛╨╡ ╨▓╨╕╨┤╨╡╨╛\0355.png'): can't open/read file: check file path/integrity.`
![изображение](https://github.com/s0md3v/roop/assets/2357892/eb936315-7bd8-4d68-9fa3-87199e059e54)
Additionally, when the source file contains a Cyrillic letter (you can test it with `лицо.png`), you will also encounter an error.
![изображение](https://github.com/s0md3v/roop/assets/2357892/6c52082f-9df7-4864-9bcb-307d640abe77)

This bug does not affect the output path names.

I'll try to send a PR to fix it.

**Comment by phineas-pta** [comment]
it seems a problem with tk ui, does it happen with cli ?

**Comment by pozitronik** [comment]
> it seems a problem with tk ui, does it happen with cli ?

Yes, as I said before:

![изображение](https://github.com/s0md3v/roop/assets/2357892/0a951ac0-9ac9-422f-a0f2-8fd1a9e42d8c)

**Comment by phineas-pta** [comment]
a bug of `opencv` ?

opencv/opencv#4242

opencv/opencv#18305

**Comment by K1llMan** [comment]
Hm... Can Python process symlinks or something like that? Symlink can be created with normal standard name but reference file name with encoding.

**Comment by phineas-pta** [comment]
windows problem, doesn't happen on linux

**Comment by skrusiogit** [comment]
same problem for umlauts e.g. ü ä ö

**Comment by shohag288** [comment]
> same problem for umlauts e.g. ü ä ö

I'm a cyber security consultant that is conducting and leading security audits, penetration testing engagements, and red team engagements to a variety of companies, ranging from enterprise-level companies to small start-ups.

Daily activities include, but are not limited to: penetration testing, red teaming, briefing, debriefing, other meetings.

Previously I did infrastructure management at an enterprise-level company where I was administrating three (3) active directory forests and did host-based incident response.

Certificates owned:
[+] CCNA Routing and Switching 1
[+] Cisco Cyber Operations Introduction
[+] Cisco Cyber Operations...


My WhatsApp number : +8801314956025

**Comment by shohag288** [comment]
> windows problem, doesn't happen on linux

I'm a cyber security consultant that is conducting and leading security audits, penetration testing engagements, and red team engagements to a variety of companies, ranging from enterprise-level companies to small start-ups.

Daily activities include, but are not limited to: penetration testing, red teaming, briefing, debriefing, other meetings.

Previously I did infrastructure management at an enterprise-level company where I was administrating three (3) active directory forests and did host-based incident response.

Certificates owned:
[+] CCNA Routing and Switching 1
[+] Cisco Cyber Operations Introduction
[+] Cisco Cyber Operations...

my WhatsApp number : +8801314956025

**Comment by shohag288** [comment]
> Hm... Can Python process symlinks or something like that? Symlink can be created with normal standard name but reference file name with encoding.


I'm a cyber security consultant that is conducting and leading security audits, penetration testing engagements, and red team engagements to a variety of companies, ranging from enterprise-level companies to small start-ups.

Daily activities include, but are not limited to: penetration testing, red teaming, briefing, debriefing, other meetings.

Previously I did infrastructure management at an enterprise-level company where I was administrating three (3) active directory forests and did host-based incident response.

Certificates owned:
[+] CCNA Routing and Switching 1
[+] Cisco Cyber Operations Introduction
[+] Cisco Cyber Operations...

my WhatsApp number : +8801314956025

**Comment by shohag288** [comment]
> a bug of `opencv` ?
> 
> opencv/opencv#4242
> 
> opencv/opencv#18305


I'm a cyber security consultant that is conducting and leading security audits, penetration testing engagements, and red team engagements to a variety of companies, ranging from enterprise-level companies to small start-ups.

Daily activities include, but are not limited to: penetration testing, red teaming, briefing, debriefing, other meetings.

Previously I did infrastructure management at an enterprise-level company where I was administrating three (3) active directory forests and did host-based incident response.

Certificates owned:
[+] CCNA Routing and Switching 1
[+] Cisco Cyber Operations Introduction
[+] Cisco Cyber Operations...

my WhatsApp number : +8801314956025

**Comment by shohag288** [comment]
> Tried on the `next` branch on Windows 11 with Russian locale.
> There is a bug when the source or target path contains any non-ASCII symbol. I reproduced it using Cyrillic and Mkhedruli (Georgian alphabet) symbols.
> To reproduce the issue, rename any file to `тестовое видео.mp4` (or `ტესტი ვიდეო.mp4` for Mkhedruli) and use it as the target, either in console or GUI mode. As a result, you will receive a bunch of errors, one for every frame: `['NoneType' object has no attribute 'shape'
> WARN:3@495.146] global loadsave.cpp:244 cv::findDecoder imread_('D:/WORK/data\temp\╤В╨╡╤Б╤В╨╛╨▓╨╛╨╡ ╨▓╨╕╨┤╨╡╨╛\0355.png'): can't open/read file: check file path/integrity.`
> ![изображение](https://github.com/s0md3v/roop/assets/2357892/eb936315-7bd8-4d68-9fa3-87199e059e54)
> Additionally, when the source file contains a Cyrillic letter (you can test it with `лицо.png`), you will also encounter an error.
> ![изображение](https://github.com/s0md3v/roop/assets/2357892/6c52082f-9df7-4864-9bcb-307d640abe77)
> 
> This bug does not affect the output path names.
> 
> I'll try to send a PR to fix it.


I'm a cyber security consultant that is conducting and leading security audits, penetration testing engagements, and red team engagements to a variety of companies, ranging from enterprise-level companies to small start-ups.

Daily activities include, but are not limited to: penetration testing, red teaming, briefing, debriefing, other meetings.

Previously I did infrastructure management at an enterprise-level company where I was administrating three (3) active directory forests and did host-based incident response.

Certificates owned:
[+] CCNA Routing and Switching 1
[+] Cisco Cyber Operations Introduction
[+] Cisco Cyber Operations...

my WhatsApp number : +8801314956025

**Comment by henryruhs** [comment]
I don't want to be the show stopper but our contributing guidelines say the following:

Don't...solve third party issues in our project
