### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by 408484409** [s0md3v/roop#514]
**Describe the bug**
No error message,but not output file
input face: d:/111.png  ,video 222.mp4 ,output 333.mp4
![image](https://github.com/s0md3v/roop/assets/28914368/028dcfb6-60cd-4ec0-9c75-9868bd3227d9)
-----
python==3.10.11
numpy==1.23.5
opencv-python==4.7.0.72
onnx==1.14.0
insightface==0.7.3
psutil==5.9.5
tk==0.1.0
pillow==9.5.0
torch==2.0.1+cu118; sys_platform != 'darwin'
torch==2.0.1; sys_platform == 'darwin'
onnxruntime==1.15.0; sys_platform == 'darwin' and platform_machine != 'arm64'
onnxruntime-silicon==1.13.1; sys_platform == 'darwin' and platform_machine == 'arm64'
onnxruntime-gpu==1.15.0; sys_platform != 'darwin'
tensorflow==2.13.0rc1; sys_platform == 'darwin'
tensorflow==2.12.0; sys_platform != 'darwin'
opennsfw2==0.10.2
protobuf==4.23.2
tqdm==4.65.0

**Details**
What OS are you using?
- Windows 11
Are you try to use a GPU?
- NVIDIA
**Sanity Check**
- [x] I have the latest code from the github repository

**Comment by henryruhs** [comment]
NSFW filter kicked in
