### ISSUE TITLE
97% loading error

### ISSUE THREAD

**Issue by yushnial** [s0md3v/roop#516]
![Screenshot 2023-06-17 114211](https://github.com/s0md3v/roop/assets/78559585/fd1ba631-8600-4cc1-a752-7576ab6c6d12)

**Comment by henryruhs** [comment]
NSFW filter kicked in

**Comment by yushnial** [comment]
> NSFW filter kicked in

for Patrick Pateman?)

**Comment by yushnial** [comment]
anyway, fixed that by reinstalling opencv-python library

**Comment by s0md3v** [comment]
Was there blood in it?

NSFW isn't limited to nudity.
