### ISSUE TITLE
(NEXT): stuck at download

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [s0md3v/roop#519]
## **Describe the bug**

**Note:** This bug is encountered in the `next` branch, which is currently under development.
I am experiencing a problem where the application gets stuck at the download stage after importing the source image _(see screenshot below)_.

## **To Reproduce**
1. Switch to the `next` branch: `git switch next`
2. Run the following command: `python run.py --keep-fps --execution-provider cuda`
3. Import video: **target faces**
4. Import image: **image source**

## **Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

## Are you try to use a GPU?
- [ ] No. I am not using the `--gpu` flag
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

## **Screenshots**
![image](https://github.com/s0md3v/roop/assets/73665622/0507dfd9-1dd0-4737-8f7c-cd5896e448bb)

## **Sanity Check**
- [X] I have the latest code from the github repository
- [X] I have followed the installation guide

**Comment by henryruhs** [comment]
Join Discord for help. Works for the most people...
