### ISSUE TITLE
The performance below the nose is excellent, but above the nose it is a bit stiff, especially unable to imitate the frowning expression in the original video. I really hope to get an update in the next version

### ISSUE THREAD

**Issue by blackjxxx** [s0md3v/roop#520]
The performance below the nose is excellent, but above the nose it is a bit stiff, especially unable to imitate the frowning expression in the original video. I really hope to get an update in the next version,Thanks very much

**Comment by henryruhs** [comment]
It's a third party model... nothing we can do about it.
