### ISSUE TITLE
CUDA_ERROR_INVALID_VALUE: invalid argument

### ISSUE THREAD

**Issue by childx** [s0md3v/roop#523]
**Describe the bug**
I got an Error  with cuda (seems like be something like ffmpeg)

**To Reproduce**
After i type:
python run.py --gpu-vendor nvidia
i chose the face and the target and start

i got this error:
[h264 @ 000001e8219fd980] decoder->cvdl->cuvidCreateDecoder(&decoder->decoder, params) failed -> CUDA_ERROR_INVALID_VALUE: invalid argument
[h264 @ 000001e8219fd980] Failed setup for format cuda: hwaccel initialisation returned error.

**Details**
What OS are you using?
Windows

Are you try to use a GPU?
NVIDIA

**Screenshots**
![Screenshot 2023-06-17 135320](https://github.com/s0md3v/roop/assets/15376934/6616d349-709a-4063-8b15-4d8cfeda6f7f)

**Sanity Check**
I have the latest code from the github repository
I have followed the installation guide

**Comment by henryruhs** [comment]
What should we do about this?
