### ISSUE TITLE
[Feature Request/Suggestion] Directml Fork for AMD Windows Users

### ISSUE THREAD

**Issue by ArchAngelAries** [s0md3v/roop#527]
After seeing widespread implementation of Directml in the Stable Diffusion arena in instances like vladmandic's SD.Next, NodAI's Shark, and lshqqytiger's fork of A1111, I have to wonder if it's possible to implement a Directml fork so that AMD Windows Users can also utilize roop. 

Anyone with an AMD 7000 series card who has tried to get into locally running many different AI tools should know full well by now that we are continually screwed when it comes to both Linux and Windows support as far as AI goes. Newer Linux Distros have finally started rolling out support for cards like mine, the 7900 XT, but unfortunately certain things, like ROCm are still not compatible. Which leads me to my point, currently, in the AI space, it seems that Directml is likely the best avenue, or at least it has proven to be for me, for individuals with AMD cards, specifically newer AMD cards, to participate. I'm nowhere near skilled in coding but am learning some stuff as I go along, that said however, I think it would be helpful to provide this option to those with AMD cards, and I'm sure there's plenty like myself who would be super happy to get a fork that allows them to use many of these tools that are basically, currently, exclusionary to their hardware choice.

**Comment by henryruhs** [comment]
I do not understand this issue, do you expect us to solve the AI space? You can use directml via the --execution-provider in next branch.

**Comment by phineas-pta** [comment]
it's the CLI argument, read the docs for more
