### ISSUE TITLE
AttributeError: module 'insightface' has no attribute 'app'

### ISSUE THREAD

**Issue by kwalitykontrol1** [s0md3v/roop#53]
trying to run it from CMD in the folder path, getting this error: AttributeError: module 'insightface' has no attribute 'app' after running python run.py" in CMD. I have the insightface folder in the roop folder. What am I missing here? Thanks.

**Comment by henryruhs** [comment]
Did you install the requirements.txt ?

**Comment by s0md3v** [comment]
@kwalitykontrol1 

1. install everything from requirements.txt
2. delete the insightface folder from roop's folder and don't move it the next time its downloaded.

**Comment by kwalitykontrol1** [comment]
> Did you install the dependencies via `requirements.txt` like described in the README?

I ran pip install -r requirements.txt. Do I need to do something different?

**Comment by kwalitykontrol1** [comment]
> @kwalitykontrol1
> 
> 1. install everything from requirements.txt
> 2. delete the insightface folder from roop's folder and don't move it the next time its downloaded.

Where do I need to keep the insightface folder?

**Comment by s0md3v** [comment]
Nowhere. It will be downloaded automatically and you don't need to do anything. Let it be.

**Comment by AhmedMunaf2** [comment]
i have the same problem i delete insightface folder and run pip install -r requirements .txt and still show me :
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

> Nowhere. It will be downloaded automatically and you don't need to do anything. Let it be.

**Comment by henryruhs** [comment]
Similar to https://github.com/s0md3v/roop/issues/99#issuecomment-1568215189

**Comment by kwalitykontrol1** [comment]
If I follow the install instructions and there is no insightface folder created, so when I try and run it I get ModuleNotFoundError: No module named 'insightface'. So then I download insightface and put that folder inside my roop folder, and then I get this error AttributeError: module 'insightface' has no attribute 'app'

**Comment by kdescoubes** [comment]
Same problem as above.

`AttributeError: module 'insightface' has no attribute 'app'`

I'm running Windows 11, Python 3.11.4. I followed that comment : https://github.com/s0md3v/roop/issues/68#issuecomment-1567852562
But I encounter an endless compatibility problem with the requirements.txt file and pip : 


`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-intel 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.3 which is incompatible.`
