### ISSUE TITLE
Getting CUBLAS_STATUS_ALLOC_FAILED after roop update

### ISSUE THREAD

**Issue by amiler** [s0md3v/roop#537]
It used to work with previous roop drop (without preview option) and with Nvidia GPU acceleration After pulling a new drop from githib, I started getting the following errors: **CUBLAS_STATUS_ALLOC_FAILED** when going over individual png files and doing face swap. It comes from onnxruntime cuda_call,cc, line 114.  Preview works and you can see the face been replaced. However, when doing the whole movie, it starts generating CUBLAS_STATUS_ALLOC_FAILED errors and generated movie has no faces swapped. 

OS: Windows 10
CUDA: 11.6
Python: 3.10.x'
Nvidia GTX 1050 with 3GB of memory
Using --gpu flag produces error. CPU options works well but is very slow, as expected

I do have the latest code from github and did follow instructions to enable Nvidia CUDA acceleration under Wiki page
As mentioned, it worked well before new update for github was pulled that included Preview button

If it helps root causing the problem, Stable Diffusion setup works well with the same CUDA/CUDNN setup on the system

**Comment by matheusfterra** [comment]
Same error here

**Comment by henryruhs** [comment]
Let me google that for you (as I didn't know the error aswell):

Windows:

```
SET CUDA_LAUNCH_BLOCKING=1 python run.py
```

Unix:

```
CUDA_LAUNCH_BLOCKING=1 python run.py
```

**Comment by matheusfterra** [comment]
By this command, work correctly: python run.py --gpu-vendor nvidia --gpu-threads=3
