### ISSUE TITLE
How enable drop-down menu?

### ISSUE THREAD

**Issue by ffdown** [s0md3v/roop#540]
txt2img, img2img, no drop-down menu displayed, UI restarted, after this SD restarted

v002
no errors, no bugs, all fine installed

Windows  10
NVIDIA 4090

I have the latest code from the github repository
I have followed the installation guide

**Comment by ffdown** [comment]
And everything understood)) Face-swap is the same roop =)) and the requirements are the same only a little in larger volume and the interface is exactly =))

**Comment by henryruhs** [comment]
Thanks for letting us know.
