### ISSUE TITLE
The program is stuck here and there is no result.

### ISSUE THREAD

**Issue by qiu8888** [s0md3v/roop#548]
Processing:  96%|███████████████████████████████████████████████████ Processing:  89%|███████████████████████████████████████████████████ Processing: 100%|███████████████████████████████████████████████████ Processing: 100%|███████████████████████████████████████████████████ ████████████████| 23/23 [10:51<00:00, 28.33s/frame]
Processing: 100%|███████████████████████████████████████████████████ Processing: 100%|███████████████████████████████████████████████████ ████████████████| 23/23 [10:51<00:00, 28.34s/frame]
Processing: 100%|███████████████████████████████████████████████████ Processing: 100%|███████████████████████████████████████████████████ ████████████████| 23/23 [10:52<00:00, 28.39s/frame]
Processing: 100%|███████████████████████████████████████████████████ Processing: 100%|███████████████████████████████████████████████████ ████████████████| 23/23 [10:52<00:00, 28.39s/frame]
Processing: 100%|███████████████████████████████████████████████████ Processing: 100%|███████████████████████████████████████████████████ ████████████████| 23/23 [10:54<00:00, 28.45s/frame]
Processing:  94%|███████████████████████████████████████████████████ Processing: 100%|███████████████████████████████████████████████████ Processing: 100%|███████████████████████████████████████████████████ ████████████████| 18/18 [03:36<00:00, 12.03s/frame]

**Comment by henryruhs** [comment]
Stucked in processing porn... happens :-)
