### ISSUE TITLE
Wont run on mac? 

### ISSUE THREAD

**Issue by Maki9009** [s0md3v/roop#55]
when i try to use python run.py on m1 pro mac, i get this error

Traceback (most recent call last):
  File "/Users/maki99/Desktop/Auto111/roop/run.py", line 4, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by s0md3v** [comment]
read docs.

**Comment by Maki9009** [comment]
so if theres no mac installation process it doesn't run on mac?

**Comment by s0md3v** [comment]
Installation process is same for all platforms. There are just extra steps for AMD and NVIDIA GPU which is optional.

The program will run on Mac but it will be slower due to lack of GPU support.
