### ISSUE TITLE
Roop not appearing

### ISSUE THREAD

**Issue by Pendragon51** [s0md3v/roop#551]
I installed Visual Studio as suggested, then installed the extension, restarted a1111 but no tab appears for Roop, any thoughts would be great. One thing I  have noticed after installing Visual Studio I get from my Bitdefender this message  PowerShell tried to load a malicious resource detected as Heur.BZC.ZFV.Boxter.341.B6DD29B3 and was blocked. Your device is safe. I got it once when I was starting A1111 and then when I installed the extension.  On one end I hear it's a false positive on the other it's not, so that may be the issue that maybe something is not getting through that should, but I do see the extension and as far as I can tell there was no issue from A1111 othere than what I said above?

**Comment by henryruhs** [comment]
This is not the repo for the extension.

**Comment by Pendragon51** [comment]
I assume your talking about the repository, is it incomplete or did they
load the wrong one?
