### ISSUE TITLE
Complimentary "Pre-Roop" and Roop Upgrade to Process Multiple Files

### ISSUE THREAD

**Issue by cmatrix7777** [s0md3v/roop#552]
Hi there. Got 2 suggestions:

1) "Pre-Roop": to split a larger video into "Roop _processable_ short videos" with a given face
Give the new tool a full (say 30) mins video and a face from that video that we want to target. Then the new tool would use ffmpeg or something like losslesscut to extract (split) all the short video sequences (I mean, consecutive seconds with the target face found, that could be processed by Roop without problems) in a given folder.

2) A way to process multiple short videos in a folder (within Roop). So instead of giving a video file, give a folder and process consecutively all the videos there, saving the outputs in another folder.

**Comment by henryruhs** [comment]
Thanks for the input, I appreciate it. Allow me to ask for your API draft via https://github.com/s0md3v/roop/issues/506
