### ISSUE TITLE
Error when trying the new face_enhancer

### ISSUE THREAD

**Issue by DeadlyVirez** [s0md3v/roop#553]
**Describe the bug**
When trying the face enhancer on a video, it works most of the way but creates the error seen in the screenshot below

**To Reproduce**
1. Select picture as source
2. Select video as target
3. Select keep fps
4. Start

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**
![grafik](https://github.com/s0md3v/roop/assets/24830874/7bcfac55-1396-4951-9af2-e9504bc9327f)

**Sanity Check**
- [X] I have the latest code from the github repository
- [X] I have followed the installation guide
- [X] I'm on branch 'next'

**Comment by henryruhs** [comment]
Not sure what we can do about it, can you provide the source and target so I can try to reproduce it.

**Comment by DeadlyVirez** [comment]
Just wanted you guys to be aware that this might happen. I'm not expecting you to fix it :)
Can't provide the files unfortunately. I'm just gonna close this issue.
