### ISSUE TITLE
Updated to last version an now i get: No Module named: "scipy.signal".

### ISSUE THREAD

**Issue by ZeroCool22** [s0md3v/roop#555]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**
![Screenshot_3](https://github.com/s0md3v/roop/assets/13344308/1a770557-efd2-4ffa-bb6a-6b7244893e6e)

**Sanity Check**
- [x] I have the latest code from the github repository
`commit 70108223f98dff07eb4b502424a9d47159163861 (HEAD -> main, origin/main, origin/HEAD)`
- [x] I have followed the installation guide

But when i tried to install it, it says i already have it:

![Screenshot_5](https://github.com/s0md3v/roop/assets/13344308/a77203f9-2aee-4c05-95a5-f3c3d5001c50)

**Comment by henryruhs** [comment]
Please join Discord for platform and installation related topics.
