### ISSUE TITLE
ValueError: need at most 63 handles, got a sequence of length 66

### ISSUE THREAD

**Issue by qiu8888** [s0md3v/roop#558]
File "C:\Users\Administrator\.conda\envs\roop\lib\multiprocessing\connection.py", line 811, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 66
How can i do ?

**Comment by henryruhs** [comment]
Join Discord for help.

**Comment by qiu8888** [comment]
OK, please give me the Discord address.

**Comment by henryruhs** [comment]
it is a pinned issue...
