### ISSUE TITLE
Error FACE_ANALYSER

### ISSUE THREAD

**Issue by duirk** [s0md3v/roop#560]
line 10, in get_face_analyser
FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=roop.globals.providers)
TypeError: FaceAnalysis.__init__() got an unexpected keyword argument 'providers'

**Comment by s0md3v** [comment]
You have the wrong insightface version installed.

**Comment by duirk** [comment]
thank you very much :)

**Comment by ricardo-martinez-dev** [comment]
what's the correct version?

**Comment by ricardo-martinez-dev** [comment]
could you tell what's the correct version? I'm facing the same problem. Thanks!
