### ISSUE TITLE
[BUG] It runs successful, but the UI is blank

### ISSUE THREAD

**Issue by wangkaibo** [s0md3v/roop#565]
I have followed the installation guide, and it runs successful, but the UI is white blank.

I clicked on a part of the blank UI and a file selection dialog popped up.

![image](https://github.com/s0md3v/roop/assets/12249031/a46f9b3e-4b36-4d35-9453-c23943d270c1)

**Screenshots**
![image](https://github.com/s0md3v/roop/assets/12249031/da22ab6a-549b-484d-a22e-95d4e6e459e1)

**Comment by henryruhs** [comment]
Please join Discord - there is anything I can do on my side with bug reports like that. What do you expect?
