### ISSUE TITLE
nvidia gpu works not well

### ISSUE THREAD

**Issue by Pher1** [s0md3v/roop#567]
**Describe the bug**
when use gpu version,it get starts well but when processing the video it will stop at 25% or lower,and output the video and the output seems not work well,faces in all frames have not been changed
[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc
:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS
_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=LAPTOP-CC0F7POD ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=164 ; expr=cublasCreate(&cublas_handle_);

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ *] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [* ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [ *] I have the latest code from the github repository
- [* ] I have followed the installation guide

**Comment by henryruhs** [comment]
Try to lower the `--execution-threads`.
