### ISSUE TITLE
Opencv-The function is not implemented. Rebuild the library

### ISSUE THREAD

**Issue by bouda05** [s0md3v/roop#569]
**Describe the bug**
I have issue in GUI or commandline to start program. When I upload video and pic, press start, it fails with "cv2.destroyAllWindows()  # pylint: disable=no-member
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1266: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'"
When I use preview, it works fine.
I am starting app with bat script which is contains:
"@echo off
cd /d C:\temp\ROOP\venv\Scripts
call activate
cd /d C:\temp\ROOP\
python run.py --keep-frames --keep-fps "

**To Reproduce**
Star app with bat or via commandline
upload pic and vid
press start

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [X ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**
![obrazek](https://github.com/s0md3v/roop/assets/83223072/a6d772d4-3976-4fe9-8d03-9beb04e47da0)

**Sanity Check**
- [X ] I have the latest code from the github repository
- [ X] I have followed the installation guide

**Comment by henryruhs** [comment]
Added it to the wiki: https://github.com/s0md3v/roop/wiki/Troubleshooting#solution-to-most-opencv-errors

**Comment by bouda05** [comment]
I already did this, but it is still not working. Uninstall Opencv and onnxruntime, install again, same result

**Comment by henryruhs** [comment]
Install lib suggested in the error message.

**Comment by bouda05** [comment]
On windows is libgtk2.0 implemented in opencv-python which was reinstalled
