### ISSUE TITLE
What's in the binary bro?

### ISSUE THREAD

**Issue by chrisbward** [s0md3v/roop#57]

**Comment by s0md3v** [comment]
https://www.google.com/search?client=firefox-b-d&q=whats+an+onnx+file

**Comment by chrisbward** [comment]
https://github.com/deepinsight/insightface/issues/2315

**Comment by chrisbward** [comment]
Don't gaslight me @s0md3v , this isn't the first time we've met.

**Comment by davidhaley** [comment]
https://www.virustotal.com/gui/url/da33d4764aa8b164cc943ea37566bca47706aef82e5b4705c8a146d039744f06/detection

![image](https://github.com/s0md3v/roop/assets/11729897/b5ea3a20-c6fe-4baf-ab36-2a087af95a47)

![image](https://github.com/s0md3v/roop/assets/11729897/226a55dc-5998-47eb-93db-83eae7e944c0)

**Comment by s0md3v** [comment]
@davidhaley bro really posted a result that has nothing to do with the file.

**Comment by s0md3v** [comment]
@chrisbward The "binary" which is an onnx model came from a program that used to download the it from insightface's server just like any other model. insightface took down and put it behind a discord bot but forks and backups of that program and many other existed.

That's the story.

**Comment by chrisbward** [comment]
Gotcha - I managed to find the same binary from a little google dorking the filename, found in another repository since-pulled, called "Melt".

Hashsums matched at least, but as you can see, I've asked the original devs to put the hashsums to verify!

**Comment by s0md3v** [comment]
@chrisbward thank you! That would put people at ease!

**Comment by chrisbward** [comment]
WARNING - DO NOT USE THIS VERSION OF ROOP

I have jailed the binary inside a Docker container and will be forking/porting to Golang.
