### ISSUE TITLE
Insert runtime options as metadata into the generated video file

### ISSUE THREAD

**Issue by mossan0101** [s0md3v/roop#570]
I believe that by embedding the runtime options into the video, it will be easier to verify how the video was generated and compare it with other options. Additionally, implementing a mechanism to parse metadata from the video file by setting the path to the video file as an argument during startup would make the comparison even more straightforward. Fortunately, it is possible to embed metadata using ffmpeg. https://write.corbpie.com/adding-metadata-to-a-video-or-audio-file-with-ffmpeg

**Comment by henryruhs** [comment]
This can be done afterwards via ffmpeg... I see no reason to build it into roop.
