### ISSUE TITLE
Select the Nth face

### ISSUE THREAD

**Issue by lelapin123** [s0md3v/roop#571]
With the version of roop that is a plugin to stable diffusion, i can select the face that i want to exchange. (the Nth one)
The standalone version of roop for video should have the same feature.

Another idea that i suggest is to be able to set the rectangle in which the faces are exchanged.
(it is also easy to do)

A last idea is to set the face that should be changed in the first frame of the video and then, on each further frame, the face that has the closest position to the one that has been exchanged in the previous one.

**Comment by henryruhs** [comment]
Projects are not connected... Please do not open issues related to the extension
