### ISSUE TITLE
Processing succeed, but no output vedio

### ISSUE THREAD

**Issue by slowlypasser** [s0md3v/roop#573]
**Describe the bug**
I have tried the latest version.The program is running normally, but there is no output video, what is the problem.

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [ ] I have the latest code from the github repository
- [ ] I have followed the installation guide

**Comment by Pluto4o4** [comment]
I also encountered the same problem. Regardless of using gpu or cpu, there is no result after running successfully

**Comment by henryruhs** [comment]
Nothing I can do with this information... it works for me
