### ISSUE TITLE
run.py: error: argument --execution-provider: invalid choice: 'cuda' (choose from 'cpu')

### ISSUE THREAD

**Issue by blackjxxx** [s0md3v/roop#575]
**Describe the bug**

Following the steps in "CUDA Execution Provider (Nvidia) " of "Acceleration", the script cannot be started

Using the previous "--gpu vendor nvidia" parameter can start, but it was found that the program is running on CPU

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ 1] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [1 ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**
![20230621204204](https://github.com/s0md3v/roop/assets/136894384/7c582f44-7e8a-42bf-be4f-4c4ceb22eed0)

**Sanity Check**
- [1 ] I have the latest code from the github repository
- [ ] I have followed the installation guide

**Comment by henryruhs** [comment]
Like the errors say, it is invalid... there is no provider available like that.

**Comment by blackjxxx** [comment]
> Like the errors say, it is invalid... there is no provider available like that.
> 
> RTFM: https://github.com/s0md3v/roop/wiki/4.-Troubleshooting#only-cpu-is-processing

But I have a Graphics card "NVIDIA GeForce RTX 4070 Ti",and in the previous version with"--gpu vendor nvidia" is the normal use of graphics card operation
