### ISSUE TITLE
FPS Problem

### ISSUE THREAD

**Issue by Solomungus** [s0md3v/roop#581]
I gave Roop a clip at 25fps, the generated video was at 30 fps and was increasingly out of sync with the audio. Is Roop aware of the FPS of the source video? Can it be defaulted to use that?

Windows 10, using Roop via Visions of Chaos

RTX 3090

I had to fix it manually by keeping the frames, ripping the audio and using ffmpeg to remake the video but at 25fps, but it would be really great if Roop did it natively.

A preserve source framerate option for the output video.

**Comment by henryruhs** [comment]
There is `--keep-fps` for exactly that... reading the documentation helps
