### ISSUE TITLE
Bug: Face selection wont accept jpg images

### ISSUE THREAD

**Issue by kraibse** [s0md3v/roop#586]
**Describe the bug**
The application does not seem to accept jpg images, only png files when inserting them into the face slot.
After selecting the respective file the preview window remains empty.

**To Reproduce**
1. Select a face
2. Pick your jpg file
3. See the empty preview in the application

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you try to use a GPU?
- [x] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by henryruhs** [comment]
Tested it, this is false statement.

**Comment by kraibse** [comment]
Well, what else do you suppose it is? I could only insert it after I converted the jpg to png.
