### ISSUE TITLE
Next Branch: Fix pick_queue()

### ISSUE THREAD

**Issue by C0untFloyd** [s0md3v/roop#588]
**Describe the bug**
Threaded swapping with a remainder of frames // roop.globals.execution_threads does still freezes at the end. 

**To Reproduce**
Face Swap frames of a video where the number of frames is not divisible by 8 threads without remainder

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

In my fork my naive working fix looks like this:

def multi_process_frame(source_face: Face, target_face: Face, temp_frame_paths: List[str], process_frames: Callable[[str, List[str], Any], None], update: Callable[[], None]) -> None:
    with ThreadPoolExecutor(max_workers=roop.globals.execution_threads) as executor:
        futures = []
        queue = create_queue(temp_frame_paths)
        total = len(temp_frame_paths)
        queue_per_future = total // roop.globals.execution_threads
        while not queue.empty():
            if total < queue_per_future:
                queue_per_future = total
            future = executor.submit(process_frames, source_face, target_face, pick_queue(queue, queue_per_future), update)
            futures.append(future)
            total -= queue_per_future
        for future in as_completed(futures):
            future.result()

_The function definition is different from yours as I already use selected source and target faces as parameters._

**Comment by henryruhs** [comment]
Did you update the next branch today? This has been fixed some hours ago.
