### ISSUE TITLE
Please provide us with CUDA, CUDNN and TensorRT versions you use

### ISSUE THREAD

**Issue by adam-andrzejczak** [s0md3v/roop#59]
GPU version runs the program - although I had to manually force it in code, it seems --gpu is not recognized now. However, while I provided the image, clip and target name, the console ejects hundreds of lines of log and my comp almost freezes. It seems there are some incompatibilities between toolkit. What are you using?

Mine:
TensorRT 8.6.1.6
cudnn 8.9.0
cuda 11.6

**Comment by s0md3v** [comment]
@henryruhs might be able to help here

**Comment by henryruhs** [comment]
cuda and cudnn need to have the same version

**Comment by adam-andrzejczak** [comment]
Do you have TensorRT?

**Comment by kex0** [comment]
This seems to be the same problem as I have
https://github.com/s0md3v/roop/issues/43#issue-1731098731

I use 
CUDA 11.8
cuDNN 8.9.1
no TensorRT

**Comment by JimZeeKing** [comment]
@kex0 Hi, i cannot grasp (and frankly kinda loosing it haha) how to correctly install CUDA and CuDNN. Do you have any doc i could follow? I am trying with this doc : https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html
But i dont even have the folder they mention even though i installed the cuda toolkit 11.8

**Comment by kex0** [comment]
> @kex0 Hi, i cannot grasp (and frankly kinda loosing it haha) how to correctly install CUDA and CuDNN. Do you have any doc i could follow? I am trying with this doc : https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html But i dont even have the folder they mention even though i installed the cuda toolkit 11.8

I followed that too. You have to create the folder yourself. e.g. if you downloaded cuDNN 8.9 you create a folder named `v8.9` in `C:\Program Files\NVIDIA\CUDNN`, if you downloaded 8.9.1 you name it `v8.9.1`. Then just paste `bin`, `include`, `lib` inside it.

Then create environment variable and you're done 
![SystemPropertiesAdvanced_8bNMhaRABW](https://github.com/s0md3v/roop/assets/46696708/698c6db9-6fa6-4aa5-adae-8d64ca63c53b)

**Comment by JimZeeKing** [comment]
@kex0 You created the whole C:\Program Files\NVIDIA\CUDNN too? beacuse i don't have that folder root at all
Thanks

**Comment by kex0** [comment]
> @kex0 You created the whole C:\Program Files\NVIDIA\CUDNN too? beacuse i don't have that folder root at all Thanks

Sorry I don't remember that. I've been using cuDNN for other things for a long time. I'd try it though.

**Comment by JimZeeKing** [comment]
@kex0  What ever the folder is, as long as its in the PATH, it works! Thanks

**Comment by bbecausereasonss** [comment]
Hmm, so anyone figure out how to get GPU running? I'm on a 4090.

**Comment by JimZeeKing** [comment]
Got it running following kex0 tips including the  :
```
pip install torch torchvision torchaudio --force-reinstall --index-url https://download.pytorch.org/whl/cu118
```

**Comment by Moeblack** [comment]
> 

CUDA 11.8 TORCH 2.0.1 TENSORRT 8.9.0 RUNS WELL.

**Comment by LokeYourC3PH** [comment]
Ayo how DID anyone with TensorRT install it properly on the system? Linux? Windows?

**Comment by s0md3v** [comment]
@Moeblack

1. please share your os and how install tensorrt
2. did you need to install cuda-toolkit or cudnnn?

**Comment by Moeblack** [comment]
@s0md3v 
I don't know what happened either, I only succeeded in running it once.
When I tried to run the program using GPU again later, the program started overflowing memory crazily. Even running the same task.

**Comment by henryruhs** [comment]
There are multiple ENV variables that are important and versions have to match as well.

```
LD_LIBRARY_PATH
PATH
CUDA_PATH
CUDA_HOME
````

Please install CUDA 11.6 and make sure you have the latest Nvidia Drivers installed.

Cannot give more details at the moment but I got it running under Ubuntu.

**Comment by bbecausereasonss** [comment]
No luck in WSL still :/

**Comment by UberGuidoZ** [comment]
These steps should allow you to get the nVidia GPU option working on Windows. (It worked on MY machine! 😂) Many of the downloads are larger and take some registration to access. I've thought about posted alternative downloads direct from Github (downloaded from the same official sources as linked) to save time, if desired...

Download and install [Visual Studio - Community Edition](https://visualstudio.microsoft.com/downloads/) if you don't already have it. During install, make sure to include the `Python` and `C++` packages. (ALT DOWNLOAD)

Download [CUDA Toolkit LOCAL v11.8](https://developer.nvidia.com/cuda-11-8-0-download-archive). (ALT DOWNLOAD)

Download [CUDNN for 11.x](https://developer.nvidia.com/rdp/cudnn-download). Yes, you need to register and go through everything. (ALT DOWNLOAD)

After downloading the CUDNN ZIP file, create the following full path: `C:\Program Files\NVIDIA\CUDNN\v8.9.1`
***(NOTE: If your Windows install is on a different drive, substitute that drive letter for C:)***

Within that `v8.9.1` folder, extract the downloaded CUDNN ZIP. It should have the `bin`, `include`, `lib`, and `LICENSE` folders/file directly in the v8.9.1 folder.

After all that setup is complete, open Powershell as an admin and execute this command:
`pip install torch torchvision torchaudio --force-reinstall --index-url https://download.pytorch.org/whl/cu118`

Finally, we need to add something to the Windows PATH environmental variable. Either launch this from the WIN+R (Windows Run box) `rundll32.exe sysdm.cpl,EditEnvironmentVariables` or search "Environmental Variables" in the Windows search then open it snd click `Environment Variables` (button). Now navigate to the following (clicking OK on all open windows when done):

`System Variables` (section) -> click `Path` (variable) -> `Edit...` (button) -> `New` (button) -> Enter `C:\Program Files\NVIDIA\CUDNN\v8.9.1\bin` (or your bin directory)

Now pop into PowerShell, cd to your git cloned roop directory and launch it with: `python .\run.py --gpu --max-memory 16`
***NOTE: Replace "16" in the command with the maximum memory, in GB, that you want it to use. (16 is also the default.)***

**Comment by henryruhs** [comment]
I think we figured out matching versions, the new [pre_check()](https://github.com/s0md3v/roop/blob/main/run.py#L64-L87) should help most people.

**Comment by CaptainCodeAU** [comment]
> 

"maximum memory"... is that RAM or VRAM?
