### ISSUE TITLE
Stops at 75%

### ISSUE THREAD

**Issue by crowbait** [s0md3v/roop#590]
**Describe the bug**
Jobs complete very rarely. The first run after opening the program *often* (but not always) runs to 100%, but subsequent jobs without restarting the application always conclude at 75% or 87%. A video is generated but the last bit is not processed and stays original.

I do not know if this is related, but during processing I also consistently get the following error (but not only during the last 25%, but throughout):
```
[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Gemm node. Name:'Gemm_128' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=DESKTOP-VPL61PN ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=164 ; expr=cublasCreate(&cublas_handle_);
```

**To Reproduce**
Select any face and target, with FPS limit ON and Process all frames OFF

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 11
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [X] I have the latest code from the github repository
- [X] I have followed the installation guide

**Comment by crowbait** [comment]
I've also noted this error very soon after starting such subsequent jobs:

```
Exception in thread Thread-21 (process_frames):
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\roop\roop\swapper.py", line 43, in process_frames
    source_face = get_face_single(cv2.imread(source_img))
  File "E:\roop\roop\analyser.py", line 16, in get_face_single
    face = get_face_analyser().get(img_data)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\app\face_analysis.py", line 75, in get
    model.get(img, face)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 67, in get
    face.embedding = self.get_feat(aimg).flatten()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 84, in get_feat
    net_out = self.session.run(self.output_names, {self.input_name: blob})[0]
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Gemm node. Name:'Gemm_128' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=DESKTOP-VPL61PN ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=164 ; expr=cublasCreate(&cublas_handle_);
```

I'm also intrigued by the errors listing some path on D: , which definitely does not exist.

**Comment by henryruhs** [comment]
We need to debug the errors on Discord.

**Comment by crowbait** [comment]
I have completely reinstalled the program and switched to venv, following basic installation and GPU installation.
I have also flagged --keep-fps .

The issue is persistent, including the onnx error.
I do not use discord and github issues actually ARE the appropriate platform for this.
Closing valid issues and pointing to discord is harshly the opposite of what GitHub and its community stand for.
