### ISSUE TITLE
Network problem？

### ISSUE THREAD

**Issue by ccencon** [s0md3v/roop#594]
**Describe the bug**
This problem occurred the first time I ran the run.py script. Is this a network problem? and how do I fix it

**To Reproduce**
See error in the picture

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [✓ ] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ✓] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**
![Snipaste_2023-06-23_13-51-13](https://github.com/s0md3v/roop/assets/57783430/6f3b4768-7f0a-4000-a116-9e524a14daa0)

**Sanity Check**
- [ ✓] I have the latest code from the github repository
- [✓ ] I have followed the installation guide

**Comment by henryruhs** [comment]
See https://github.com/s0md3v/roop/wiki/1.-Installation#4-done

**Comment by carpetaa** [comment]
Downlaod "inswapper_128.onnx" here 'https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx' and move it to 'roop\models' fix it for me

**Comment by ccencon** [comment]
> Downlaod "inswapper_128.onnx" here 'https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx' and move it to 'roop\models' fix it for me

it works, thanks so much!!!
