### ISSUE TITLE
Roop crashes with no output

### ISSUE THREAD

**Issue by ForsakenTwilight** [s0md3v/roop#596]
**Describe the bug**
The issue is: the program just crashes, and the UI window disappears, leaving only the PowerShell window open with no output. THis happens after i choose the face, then the target video, i click on start to choose an output location 

**To Reproduce**
1. Roop (Nvidia)
2. choose face model
3. select target video
4. click on start
5. choose save location
6. wait for  this to fill up: set det-size: (640, 640)
100%|█████████████████████████████████████████████████████████████████████████████| 2545/2545 [00:03<00:00, 792.23it/s]
7. software crashes without any output

**Details**
What OS are you using?
-windows 11

Are you try to use a GPU?
- [x] NVIDIA RTX 3080

**Screenshots**
https://i.imgur.com/RAnPJNW.png
![WindowsTerminal_2H8jHYAT7l](https://github.com/s0md3v/roop/assets/7201155/9b946d9e-826d-4196-a1f4-220cf510bbf5)

I have already tried the suggestion in the screenshot to Use --execution-provider cuda instead. but it did not make a difference

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by kraibse** [comment]
This sounds like the NSFW filter is triggering. Repo owner should work on providing error messages when they occur instead of just hiding them. AT lea

**Comment by phineas-pta** [comment]
the problem with error messages is they're easily searchable in source code so u can remove it

**Comment by ForsakenTwilight** [comment]
Thank you both for your comments, it at least made me realize what the issue is. and I indeed did use a NSFW model just to test this. 
do you by any chance know how to remove the filter?
