### ISSUE TITLE
[TODO] Add DirectML installation guide for Windows 11/10 system to support AMD GPU Acceleration

### ISSUE THREAD

**Issue by carpetaa** [s0md3v/roop#597]
I have an AMD radeon rx6650xt GPU, and with my Windows 11 system, I have to use DirectML to utilize my AMD GPU. It will be grateful if you can add DirectML installation guide.
- [ ] Add DirectML installation guide for Windows 11/10 system to support AMD GPU Acceleration

**Comment by henryruhs** [comment]
You can send a PR to https://github.com/s0md3v/roop.wiki.git
