### ISSUE TITLE
the resolution on video generated is not good, link to the video below

### ISSUE THREAD

**Issue by neozbr** [s0md3v/roop#601]
the video generated quality is not good and the resolution of the original video is good link: https://www.youtube.com/watch?v=ky7S_WKX4i8 , I've tried to change quality to 1 but still generate very poor resolution quality, I've put the original and the generated then side by side, can someone help to understand or how to improve the final quality ? thanks.

**Comment by henryruhs** [comment]
Don't open a second issue just because your

**Comment by henryruhs** [comment]
Closed as of spam...
