### ISSUE TITLE
Is there any method to upscale swapper a bit?

### ISSUE THREAD

**Issue by crwpw** [s0md3v/roop#604]
128x128 is too low for adequate face replacement, maybe there is any chance to replace the "inswapper_128.onnx" to more powerful model? :| Thanks

**Comment by henryruhs** [comment]
Use the enhancer

**Comment by crwpw** [comment]
> Use the enhancer via `--frame-processor face_swapper face_enhancer`.

I used it, but anyway the source projection face in 128p is too low for speach for example

**Comment by jasan-s** [comment]
tried the enhancer, its not really good. it distorts the face

**Comment by henryruhs** [comment]
if you are on mac, do not use the latest onnxruntime, but the one from the requirements.txt... for more help use discord - will lock this issue as GitHub issues are meant for software tickets and not support
