### ISSUE TITLE
update the newest files, error as bellow

### ISSUE THREAD

**Issue by jasoncow007** [s0md3v/roop#606]
**Describe the bug**
update the newest files, error as bellow

**Details**
What OS are you using?
- [ ] Windows 

Are you try to use a GPU?
- [ ] NVIDIA

**Screenshots**
D:\>python run.py --execution-provider cuda
Traceback (most recent call last):
  File "D:\run.py", line 3, in <module>
    from roop import core
ImportError: cannot import name 'core' from 'roop' (unknown location)

**Comment by henryruhs** [comment]
I assume you did something wrong while git pull / git merge - try a fresh copy.
