### ISSUE TITLE
Video is not getting saved

### ISSUE THREAD

**Issue by vyadav33e** [s0md3v/roop#607]
**Describe the bug**
Video is not getting saved

**To Reproduce**
When running "Start", the operation completes successfully but video is not saved. I looked everywhere but no where to be found. Other people are also facing same issue.

```Processing: 100%|█| 412/412 [00:45<00:00,  9.08frame/s, execution_providers=['CUDAExecutionProvider']
[ROOP.CORE] Creating video with 30.0 fps...
[ROOP.CORE] Restoring audio might cause issues as fps are not kept...
[ROOP.CORE] Processing to video succeed!
```

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [X] I have the latest code from the github repository
- [X] I have followed the installation guide

**Comment by henryruhs** [comment]
Define a video file and name... it generates it automatically at the given output directory.

**Comment by vyadav33e** [comment]
@henryruhs already doing that by naming file like output.mp4 and choosing a save location. But video is not getting saved.

**Comment by henryruhs** [comment]
It works 100% ...
