### ISSUE TITLE
use --frame-processor face_enhancer failed, no ui 

### ISSUE THREAD

**Issue by lix19937** [s0md3v/roop#609]
**Describe the bug**  
run `python run.py --execution-provider cuda`  ok 
run  `python run.py --execution-provider cuda --frame-processor face_enhancer `  no ui appear.   It seems that  
not executed to follow  
```
frame_processor.pre_check() 
```

**Details**
What OS are you using?
- [x] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [x] I have the latest code from the github repository
- [ ] I have followed the installation guide

**Comment by phineas-pta** [comment]
`pip install gfpgan`

**Comment by lix19937** [comment]
@phineas-pta, It works, thanks.
