### ISSUE TITLE
[ERROR] ONNXRunTimeError

### ISSUE THREAD

**Issue by peepeepeepoopoopoo** [s0md3v/roop#612]
**Describe the bug**
I get this when I use the GPU:

Processing: 8%|█████████▉ | 118/1487 [01:46<1:37:48, 4.29s/frame, execution_providers=['CUDAExecutionProvider'], threads=8, memory=16]62 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime:: ExecuteKernel] Non-zero status code returned while running Conv node. Name:'conv_15_conv2d' Status Message: D:\a\_work\1\s\onnxruntime\core\framework\bfc_arena.cc:368 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 165888

[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core \providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=DESKTOP-D3TU9QU ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=50 ; expr=cublasCreate(&cublas_handle_);

**Comment by duyifan02** [comment]
update your GEFORCE EXPERIENCE.
I don't know why, but this solve my problem.

**Comment by lix19937** [comment]
@duyifan02  what is onnxruntime version, maybe need update.

**Comment by henryruhs** [comment]
Discord for platform support.
