### ISSUE TITLE
It does not support the moving person in video which include many persons ?

### ISSUE THREAD

**Issue by lix19937** [s0md3v/roop#613]
**Describe your suggestion**   

My case as follow:  
The video contains multiple persons, changing the face of a certain person in the video, 
and **the person's position often changes** in the video, such as O'Neal and his teammates on the NBA basketball court, 
I just only want to swap **O'Neal**'s face, others not.  

I think this feature maybe need **face recognition** and do **person recognition** in every frame.

**Comment by henryruhs** [comment]
Correct
