### ISSUE TITLE
The face in the photo is blurry after conversion in CLI mode. It's ok when using UI.

### ISSUE THREAD

**Issue by kkiqq22** [s0md3v/roop#615]
**Describe the bug**
I'm using CLI mode on Ubuntu, the swapped face in the output images looks very blurry. My environment is Ubuntu20.04+3090(CUDA11.8+Python3.10). The strangest thing is that my friend using GUI on Windows can get a clear face swap result, but when using CLI the result is also blurry. So I suspect there is an essential difference between CLI and GUI.

**To Reproduce**

**Details**
What OS are you using?
- [1 ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [1 ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [ 1] I have the latest code from the github repository
![3eef29238caaddc88293b944f8841d6](https://github.com/s0md3v/roop/assets/20888251/b5bf946c-9f9b-4c8f-8e23-cd7cdc1891ad)

- [x] I have followed the installation guide

![081fdabbfe263901a60dbb8a93658f0](https://github.com/s0md3v/roop/assets/20888251/573c6062-a52a-4b2c-92fd-4504265cb65d)

**Comment by phineas-pta** [comment]
how can u go to that conclusion? u have to compare cli vs gui on your pc, and ur friend doing the same on his pc, with same command

**Comment by henryruhs** [comment]
Comparing apples with bananas results in false statements.

> I suspect there is an essential difference between CLI and GUI.

Absolutely not.
