### ISSUE TITLE
While running the 18.8MB mp4 file it shutdown and crash.

### ISSUE THREAD

**Issue by popking5466** [s0md3v/roop#617]
(native) piccolo@Piccolos-MacBook-Pro roop-main % sudo python3.9 run.py --execution-provider coreml
Password:
2023-06-26 00:49:02.566 python3.9[38485:611747] +[CATransaction synchronize] called within transaction
2023-06-26 00:49:04.452 python3.9[38485:611747] +[CATransaction synchronize] called within transaction
2023-06-26 00:49:12.012 python3.9[38485:611747] +[CATransaction synchronize] called within transaction
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
find model: /Users/piccolo/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
find model: /Users/piccolo/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
find model: /Users/piccolo/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
find model: /Users/piccolo/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
find model: /Users/piccolo/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
 92%|██████████████████████████████████████████▌   | 340/368 [00:01<00:00, 266.12it/s]
[ROOP.CORE] Creating temp resources...
[ROOP.CORE] Extracting frames...
[ROOP.FACE-SWAPPER] Progressing...
Processing:   0%| | 0/753 [00:00<?, ?frame/s, execution_providers=['CoreMLExecutionProApplied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Processing:  87%|▊| 655/753 [03:42<00:37,  2.62frame/s, execution_providers=['CoreMLExzsh: killed     sudo python3.9 run.py --execution-provider coreml
(native) piccolo@Piccolos-MacBook-Pro roop-main % /usr/local/anaconda3/envs/native/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by henryruhs** [comment]
> There appear to be 1 leaked semaphore objects to clean up at shutdown...

Use less execution threads.

**Comment by popking5466** [comment]
Could you tell me how can I solve this problem? Thanks :)

**Comment by popking5466** [comment]
> > There appear to be 1 leaked semaphore objects to clean up at shutdown...
> 
> Use less execution threads.



> > There appear to be 1 leaked semaphore objects to clean up at shutdown...
> 
> Use less execution threads.

Could you tell me how can I solve this problem? Thanks :)

**Comment by Blairding96** [comment]
I use just 1 thread and crash again
![image](https://github.com/s0md3v/roop/assets/64246515/7d7e3234-b4de-4e1c-b0f2-779710ba3bac)

**Comment by henryruhs** [comment]
Nothing we can solve on GitHub issues... Join Discord
