### ISSUE TITLE
Visual output issue on Apple M1 with CoreML

### ISSUE THREAD

**Issue by echtme** [s0md3v/roop#618]
When I use the CoreML (--execution-provider coreml) on my MBA M1, I get all frames distorted as attached.

**To Reproduce**
Start with: python run.py --execution-provider coreml

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [x] Mac OSX13.4

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [x] Mac

**Screenshots**
1. Default 2. with CoreML
![s1](https://github.com/s0md3v/roop/assets/20922271/e4bd6eb8-d943-4320-b314-357bce3d68a6)

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by henryruhs** [comment]
Don't install dependencies that are not locked by us via requirements.txt.
