### ISSUE TITLE
[PR Wanted] Lock face analyser to one face (by position)

### ISSUE THREAD

**Issue by henryruhs** [s0md3v/roop#622]
During processing the face analyser should always detect the same face so "face-bouncing" should no longer be a thing.

1. Introduce a new arg name `--face-position` that defaults to 1
1. Positions are calculated and stored based on the first frame with faces
1. The method `get_one_face()` takes this position into account
1. Using `--many-faces` will cause `--face-position` to be set to None (disabled)
1. Using `--face-position` with a number out of range should default to last face position
1. There should be a public methods for later use in UIs
   - `detect_faces(frame: Frame) -> List[Faces]`
   - `pick_face(face: Face) -> bool`
   - `store_faces(faces: List[Faces]) -> None`
1. Positions should be flushed after processing
1. Don't implement a UI for this

---

API to replace the second face:

```
python run.py --face-position 2
```

**Comment by alex00ds** [comment]
I suggest to move forward for swapping of many faces. Such way will resolve this issue.
Sources could be passed many times (1+). 
And the special value `none` will be introduced to skip a face for a case when a person in middle of three faces should not be swapped.
`-s face1.jpg -s none -s face2.jpg`
```
parser.add_argument('-s', '--source', help='select an source image', dest='source_path', action='append')

def pre_start() -> bool:
    if len(myrp.globals.source_path) < 1:
        update_status('Select an image for source path.', NAME)
        return False
        
    myrp.globals.source_faces = []
    for i, src_path in enumerate(myrp.globals.source_path):
        if src_path == "none":
            myrp.globals.source_faces.append(None)
            continue

        if not is_image(src_path):
            update_status(f'Select an image for source path ({i}: {src_path}).', NAME)
            return False

        test_face = get_one_face(cv2.imread(src_path))

        if not test_face:
            update_status('No face in source path detected ({i}: {src_path}).', NAME)
            return False
            
        myrp.globals.source_faces.append(test_face)
```
`process_frame` will be called with `myrp.globals.source_faces` prepopulated at `pre_start()`
`result = process_frame(myrp.globals.source_faces, temp_frame)`

The stack of other functions these carry `source_path: str` to `process_frames` also should be changed

```
def process_frame(source_faces: Any, temp_frame: Any) -> Any:
    if myrp.globals.many_faces:
        many_faces = get_many_faces(temp_frame)
        if many_faces:
            for i, target_face in enumerate(many_faces):
                if i < len(source_faces) and source_faces[i]:
                    temp_frame = swap_face(source_faces[i], target_face, temp_frame)
    else:
        target_face = get_one_face(temp_frame)
        if target_face:
            for source_face in source_faces:
                if source_face:
                    temp_frame = swap_face(source_face, target_face, temp_frame)
                    break
    return temp_frame

```
Additionally it's will be good to introduce the sorting order for target faces (the align edge where from to count/iterate faces). Like _left to right_, _top to bottom_, etc
```
parser.add_argument('--sort-target-faces', help='target faces sorting by l2r|r2l|t2b|b2t', dest='target_faces_sort', choices=['l2r', 'r2l', 't2b', 'b2t'])

def get_many_faces(frame: Any) -> Any:
    try:
        reverse_direction = False
        sort_dimention = 0
        if myrp.globals.target_faces_sort == 'r2l' or myrp.globals.target_faces_sort == 'b2t':
             reverse_direction = True
        if myrp.globals.target_faces_sort == 't2b' or myrp.globals.target_faces_sort == 'b2t':
             sort_dimention = 1

        return sorted(get_face_analyser().get(frame), key=lambda x: x.bbox[sort_dimention], reverse=reverse_direction)
    except IndexError:
        return None

def get_one_face(frame: Any) -> Any:
    faces = get_many_faces(frame)
    if faces:
        return faces[0]

    return None
```

**Comment by henryruhs** [comment]
Implemented via https://github.com/s0md3v/roop/pull/679
