### ISSUE TITLE
black screen of panel ?

### ISSUE THREAD

**Issue by gillbates** [s0md3v/roop#623]
**Describe the bug**

Just start with following command and it shows an empty panel without those buttons?

```
[21:10:55] [~/projs/github/roop] git(main) ❱❱❱ python3 run.py --execution-provider coreml

DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.

```

![CleanShot 2023-06-26 at 21 11 03@2x](https://github.com/s0md3v/roop/assets/783547/e76b5f80-a04d-4734-9790-86b6b14efc5d)

**Details**
What OS are you using?
- [ ] Mac

Are you try to use a GPU?
- [ ] Mac

**Sanity Check**
Latest code from github with Python 3.10.0 on my mac m1 pro.

**Comment by henryruhs** [comment]
If I remember correct this happens if your global tk library is outdated or does not match the local version.
