### ISSUE TITLE
Multiple source face files

### ISSUE THREAD

**Issue by vongillern** [s0md3v/roop#628]
I can only assume that having multiple source files of the same person would help improve results (different angles, etc). A lot of the heavy lifting is done by insightface, right? Do they have this capability to take in multiple source photos? If that isn't possible, allowing a user to add multiple photos and processing all of them as single photos would help users cherry pick the one that happens to work best. The same goes for automatically using an upscaler within the UI. AFAICT (from results only), going from one photo to a video looks much better than to a single frame from the same photo (fewer artifacts around the face). Maybe I'm just hallucinating that and the mp4 compression is smoothing blending those artifacts together. 

I'm a dev, and although I'm a python n00b I've been programming for 27 years, I'd be happy to try to help try to tackle this if you could help point me in the right direction for some experimentation, that'd be great.

All the same, this is a fantastic app, thank you for putting it together!

**Comment by henryruhs** [comment]
Sorry but we don't plan this feature... Take a look into the workshop section of the wiki if something fits your needs.

If you want to contribute then see the pick a todo issue.
