### ISSUE TITLE
Forzen at inswapper-shape in new version

### ISSUE THREAD

**Issue by Moeblack** [s0md3v/roop#63]
I can swap in the old version (the last version that can swap normally is 6c98f67c1c), just the last step of synthesizing the video will fail due to path errors (Windows 11). However, after you modified the Windows path, my software freezes at inswapper.

I tried swap pictures, it frozen at "inswapper-shape: [1, 3, 128, 128]", but give me swapped png in dir, but in vedio, it's just freeze. output original vedio cuts, and give a error output, 

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\moebl\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "E:\roop\run.py", line 181, in <lambda>
    start_button = tk.Button(window, text="Start", bg="#f1c40f", relief="flat", borderwidth=0, highlightthickness=0, command=lambda: [save_file(), start()])

                           ^^^^^^^
  File "E:\roop\run.py", line 135, in start
    start_processing()
  File "E:\roop\run.py", line 52, in start_processing
    if args['gpu']:
       ~~~~^^^^^^^
KeyError: 'gpu'

![image](https://github.com/s0md3v/roop/assets/28835093/d0869999-dfae-4093-9121-b916885023bd)

**Comment by Moeblack** [comment]
just frozen here.
![image](https://github.com/s0md3v/roop/assets/28835093/c7f2a254-acae-4197-9d7d-01d507a5e1d3)

CPU is basiclly not occupied. just a 1 second test vedio.

**Comment by JimZeeKing** [comment]
i have this error too but as soon as the swaping starts : 
![image](https://github.com/s0md3v/roop/assets/19315887/9f5e1ebc-bc08-4f02-8d89-8b25ffb1fd69)

**Comment by Moeblack** [comment]
I reinstall all requirements, and get a new error.
![image](https://github.com/s0md3v/roop/assets/28835093/52b0fc73-0390-4e5f-9a08-bcf133a8a67b)
still forzen at “inswapper-shape: [1, 3, 128, 128]”

**Comment by Moeblack** [comment]
LAST VERSION  solved this problem

**Comment by JimZeeKing** [comment]
Can confirm

**Comment by s0md3v** [comment]
Just for clarity, @Moeblack do you mean the latest version or an older version fixed the problem?
