### ISSUE TITLE
[PR Wanted] Remove torch and torchvision

### ISSUE THREAD

**Issue by henryruhs** [s0md3v/roop#631]
Importing `torch` right before `onnxruntime` solves installation issues of CUDA + CUDNN, this hack needs to be removed in order do have faster processing time for CPU-only mode. Recent PR https://github.com/s0md3v/roop/pull/624 was not successful as the contributor doesn't own the correct GPU for testing.

- [x] Remove `torch` and `torchvision` from dependencies
- [x] Remove `torch` import and del from `core.py`
- [x] Cover invalid system wide install of CUDA + CUDNN - [Related comment](https://github.com/microsoft/onnxruntime/issues/11092#issuecomment-1484756347)

**Comment by najafshafi** [comment]
I hope all of you are doing well, I want to inform you about these issue came up with me while installing the roop.

On my Mac 2019 model, the roop is not working. The following issue came up from time to time. sometimes it says Python sometime onnxruntime and sometimes.

There following errors from same time to time. One after one there errors came up. I tried Python python3.10, Python 3.11.4. 
tried pip3 install onnxruntime and all other Acceleration mentioned in the repo.

Is there any video tutorial that I should follow from Scratch?

Error 1:
Traceback (most recent call last):
  File "/Users/najafshafee/Downloads/roop/run.py", line 3, in <module>
    from roop import core
  File "/Users/najafshafee/Downloads/roop/roop/core.py", line 24, in <module>
    import roop.ui as ui
  File "/Users/najafshafee/Downloads/roop/roop/ui.py", line 4, in <module>
    import customtkinter as ctk
ModuleNotFoundError: No module named 'customtkinter'

Error 2.
zsh: command not found: python
najafshafee@Najafs-MacBook-Pro roop % python3 run.py
Traceback (most recent call last):
  File "/Users/najafshafee/Downloads/roop/run.py", line 3, in <module>
    from roop import core
  File "/Users/najafshafee/Downloads/roop/roop/core.py", line 17, in <module>
    import onnxruntime
ModuleNotFoundError: No module named 'onnxruntime

Error 3:
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement onnxruntime-coreml==1.13.1 (from versions: none)
ERROR: No matching distribution found for onnxruntime-coreml==1.13.1

Error 4.
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement onnxruntime-coreml==1.13.1 (from versions: none)
ERROR: No matching distribution found for onnxruntime-coreml==1.13.1

**Comment by henryruhs** [comment]
Solved via: https://github.com/s0md3v/roop/commit/4c9cf80b82884f557f1c67228b5a4fbb3af3bb4b
Extended troubleshooting: https://github.com/s0md3v/roop/wiki/4.-Troubleshooting#could-not-load-library-libcublasltso12-linux
