### ISSUE TITLE
The instructions are wrong. Please correct them.

### ISSUE THREAD

**Issue by mapleroyal** [s0md3v/roop#639]
**Describe the bug**
Steps are given to use GPU on Apple silicon, and these steps result in onnxruntime-silicon 1.15.0 being installed (which produces bugged output), but @henryruhs comments on Discord suggest an unawareness of this guidance. The devs should either correct or else remove the instructions.

**To Reproduce**
https://github.com/s0md3v/roop#how-do-i-install-it
Per the docs:
_first follow the basic install instructions given above and then follow GPU-specific instructions [here](https://github.com/s0md3v/roop/wiki/2.-Acceleration)_

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [X] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [X] Mac

**Screenshots**
https://i.imgur.com/hiMn2Mc.png
https://i.imgur.com/KJ54dSg.png
https://i.imgur.com/WP4xHzY.png

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by henryruhs** [comment]
Done
