### ISSUE TITLE
Support for more models

### ISSUE THREAD

**Issue by PodTT** [s0md3v/roop#642]
**Describe your suggestion**

Is it possible that different models that have higher quality like simswap are supported? It would be nice because these models have higher resolutions compared to inswapper.

**Comment by phineas-pta** [comment]
wiki -> Write-your-Frame-Processor

**Comment by henryruhs** [comment]
Simswap needs training, so this is not a thing we would ever support. Other than that, you can of course train your models and write your own frame processor.
