### ISSUE TITLE
Roop is crashing without error after I click start

### ISSUE THREAD

**Issue by kraitfps** [s0md3v/roop#643]
tt

**Comment by kraitfps** [comment]
x

**Comment by xxxDeathxxx** [comment]
+ тоже хотел написать, раньше при выборе фото/видео если оно не подходило просто ничего не происходило, а сейчас вылетает, очень не бесит и неудобно, и при выборе имени если нажать отмена то сохраняло дефолт "swapped_name" а сейчас приходится в ручную всё писать..
