### ISSUE TITLE
[PR Wanted] Allow image directory for target_path

### ISSUE THREAD

**Issue by henryruhs** [s0md3v/roop#644]
- [ ] Allow multiple images from a directory for `target_path`
- [ ] Skip `create_temp` and  `extract_frames` step when target_path is a directory
   - [ ] Update status with "Using existing frames"
- [ ] UI modifications
    - [ ] Allow to select multiple image from directory
    - [ ] Empty target_source if selection is invalid
    - [ ] Render first found image in the thumbnail
    - [ ] Find a solution to make preview work on the fly
- [ ] Update CLI help for target_path (code and readme)

**Comment by octimot** [comment]
Hey there!

I have a few suggestions to make these things work and could try to develop them in a PR.

But, I would first consider converting the UI into its own class to be able to pass progress / frames / etc. from backend cleaner and more efficiently. Working with globals is messy and could be painful on the long run.

Also, some of the suggestions mentioned in #257 would be trivial to implement once that is in place...

Is this something you could work with later, or you prefer staying on the global variables route?

Cheers!

**Comment by henryruhs** [comment]
@octimot I have to hide your post as offtopic - the idea is not to hijack issues and try to extend the scope.

**Comment by akashAD98** [comment]
@henryruhs can i try this?

**Comment by henryruhs** [comment]
Sure
