### ISSUE TITLE
Coreml do not support face enhancer? (Gfpgan) 

### ISSUE THREAD

**Issue by bikingfree1989** [s0md3v/roop#645]
Coreml do not support face enhancer? (Gfpgan) 
I found it is not speeding on my m1 macbook pro on processing the face enhancer, but acceleratting the face swapper process.
is there any solution?

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ✔️] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ✔️] Mac

**Comment by henryruhs** [comment]
only cuda and gpu are supported
