### ISSUE TITLE
[PR Wanted, Bug] Video with frames lower than threads

### ISSUE THREAD

**Issue by henryruhs** [s0md3v/roop#646]
Observation by a user: Video with frames lower than threads does not proceed as of falsy Query calculation.

Needs evaluation!

**Comment by CheddarSoftware** [comment]
I did a few tries to confirm the situation you mentioned. Progress stops when the number of frames the video contains is less than the threads. For example, when I process a video consisting of 6 frames with 8 threads, the aforementioned problem occurs. No error messages etc. just the progress stops completely.
