### ISSUE TITLE
No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by paddotk** [s0md3v/roop#647]
**Describe the bug**
Having followed the install instructions in the readme, I cannot get roop to run, as the last step (`pip install -r requirements.txt`) does not work: `ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`. I am in the roop folder in the cmd, the cmd was opened as admin, and `pip install -r ./requirements.txt` doesn't work either.
Additionally, if I try to manually install packages (with pip) that I see errors about when trying to run the program, I get stuck at the package 'cv2' which doesn't seem to exist.

**To Reproduce**
1. Install the prerequisites
2. Try to install the packages with `pip install -r requirements.txt``
3. Error

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 11
- [ ] Mac

**Screenshots**
![image](https://github.com/s0md3v/roop/assets/11683974/c7f796fa-9238-4bc1-9dd2-5f623bf9b2ee)

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by phineas-pta** [comment]
@henryruhs in wiki there's an extra ` at the end of `pip install -r requirements.txt`

**Comment by phineas-pta** [comment]
@henryruhs in wiki there's an extra \` at the end of `pip install -r requirements.txt`

**Comment by henryruhs** [comment]
Fixed the wiki, thanks

**Comment by phineas-pta** [comment]
@paddotk try again without the extra \`
