### ISSUE TITLE
does not change the face returns the video with the original face

### ISSUE THREAD

**Issue by angelluce25** [s0md3v/roop#651]
the program loads I can load the image the video, when it starts to process, it gives me a certain error and then it saves the video but without changing the face instead it saves the video with the original face without changing it

ALID_PROTOBUF : Load model from D:\******\roop\models\inswapper_128.onnx failed:Protobuf parsing failed.
[ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from D:\******\roop\models\inswapper_128.onnx failed:Protobuf parsing failed.
Processing:  75%|▊| 115/153 [01:41<00:18,  2.01frame/s, execution_providers=['CPUExecutionProvider'], threads=8, memory[ONNXRuntimeError] : 
7 : INVALID_PROTOBUF : Load model from D:\descargas IDM\para ia video\roop\models\inswapper_128.onnx failed:Protobuf parsing f

I reinstalled the inswapper_128.onnx file, and still the error persists.

windows 
nvidia

**Comment by henryruhs** [comment]
See troubleshooting on the wiki
