### ISSUE TITLE
support for mac intel with amd gpu to use coreml

### ISSUE THREAD

**Issue by sukualam** [s0md3v/roop#653]
i cant get gpu acceleration, i cant use onnxruntime-silicon because it seem for arm , i just want use this command

`python run.py --execution-provider coreml` 

i have no idea why onnxruntime devs wont support coreml with amd gpu since it is actually supported when i using stable diffusion webui on macos with amd gpu.

my gpu: amd rx 560 (it can use coreml on stable diffusion macos)
macos: ventura 13.4

**Comment by henryruhs** [comment]
It works, read the wiki or join our Discord.
