### ISSUE TITLE
Can it save face data which It read/analyze from source video file?

### ISSUE THREAD

**Issue by mukeshsnp12** [s0md3v/roop#655]
Can it save face data which It read from source video file?
Reading/analyzing face data of a 4 minute video took almost 40 minutes, if it can save face data in a file for later use and later can get that face data from file, it can help to create next video of same source video.
Suppose I have a source video and I swap face of 1 person in source video and next time I want to swap face of same source video with other person, it will again take same time for reading/analyzing face of same source video.
If you can create this feature, it will save lot of time.

**Comment by henryruhs** [comment]
There is only `--keep-frames` at the moment an near future.
