### ISSUE TITLE
[PR WANTED] Slider bar for enhanced processor

### ISSUE THREAD

**Issue by TalentlessGoon** [s0md3v/roop#657]
The Enhancer when off is quite blurry/low res. The Enhancer when on is too sharp/plasticky. It would be great to have a slider bar to manually adjust the enhancer.
Failing that, a fixed incrementation, like, 25% - 50% - 75% - 100%

Thanks

**Comment by henryruhs** [comment]
First, you are not the person to decide if a PR is wanted... Second, this opion is not present in the underlaying library.

**Comment by TalentlessGoon** [comment]
> First, you are not the person to decide if a PR is wanted... Second, this opion is not present in the underlaying library.

Sorry, I don't know how the system works, I thought this was a request area.

**Comment by henryruhs** [comment]
True, but you call it [Feature Request] then.

**Comment by TalentlessGoon** [comment]
> True, but you call it `[Feature Request]` then.

Thank you, I'll remember that for the future,
