### ISSUE TITLE
Using cuda is slower than using cpu

### ISSUE THREAD

**Issue by ChusanTang** [s0md3v/roop#658]
CPU:I5-13400F
GPU:GTX 4070

It take about 7s when i set `--execution-provider cuda cpu`or`--execution-provider cuda`, it run well but the cuda only be used in 30%.
![image](https://github.com/s0md3v/roop/assets/60557402/94865fce-1d0a-406b-8e7f-41f77eb2127a)

When i try to use cpu and set `--execution-provider cpu`,it runs faster ...About 5s.

And tensorrt didn't work well ,it takes 120 seconds to load something. Tensorrt generate a picture takes about 30s 
![image](https://github.com/s0md3v/roop/assets/60557402/e6043b8d-4cd6-425a-a91c-59d8b1a3393a)

![image](https://github.com/s0md3v/roop/assets/60557402/4ee04f20-6837-40df-90ae-3d921d25beaf)

**Comment by henryruhs** [comment]
GitHub issues are not the right place to report or discuss this -> Discord.

**Comment by gefule** [comment]
> CPU:I5-13400F GPU:GTX 4070
> 
> It take about 7s when i set `--execution-provider cuda cpu`or`--execution-provider cuda`, it run well but the cuda only be used in 30%. ![image](https://user-images.githubusercontent.com/60557402/249718837-94865fce-1d0a-406b-8e7f-41f77eb2127a.png)
> 
> When i try to use cpu and set `--execution-provider cpu`,it runs faster ...About 5s.
> 
> And tensorrt didn't work well ,it takes 120 seconds to load something. Tensorrt generate a picture takes about 30s ![image](https://user-images.githubusercontent.com/60557402/249721362-e6043b8d-4cd6-425a-a91c-59d8b1a3393a.png)
> 
> ![image](https://user-images.githubusercontent.com/60557402/249723635-4ee04f20-6837-40df-90ae-3d921d25beaf.png)

有优化方案了吗？老铁
