### ISSUE TITLE
Issue when running the python script, uses all my memory 25GB

### ISSUE THREAD

**Issue by demonslay677** [s0md3v/roop#66]
Hi, I'm trying to run the script and it hogs ALL my CPU (13900k) and ALL my ram (32GB RAM but using 25GB for the python process).
Is this normal? 
I keep getting memory errors in the terminal screen as it scrolls, can I somehow restrict how much RAM I'm using?
I also ran this with my GPU using --gpu tag, I have a 4070 and still the same issue, please help.
-JPG face is 62KB
-Video is 9.4MB

**Comment by rootsdub2** [comment]
how long did it take to generate?

**Comment by demonslay677** [comment]
It never generated, I left it running for 2mins (perhaps I needed longer) but the log was full of errors and I felt like nothing actually was happening - my computer was freaking out as there was no RAM.
I'll leave it for 5 mins and get back to you

**Comment by rootsdub2** [comment]
Mine generated but I used 480p video, proc time was  500 seconds

**Comment by henryruhs** [comment]
Try with smaller 10 sec files and report the actual error log.

**Comment by Moeblack** [comment]
> Try with smaller 10 sec files and report the actual error log.

log here 
[log.txt](https://github.com/s0md3v/roop/files/11596179/log.txt)

**Comment by henryruhs** [comment]
You could try my fork via https://github.com/s0md3v/roop/pull/91 or (if you are a developer) play around with `limit_resources()` that introduces `--max-memory` flag.

**Comment by kex0** [comment]
> Try my fork via #91 ... if you are a developer you can play with `limit_resources()` that introduces `--max-memory` flag.

You're using `import resource` which does not work on Windows

**Comment by henryruhs** [comment]
Does this help?

```
pip install python-resources
``

**Comment by henryruhs** [comment]
Thanks, I try to refactor to work cross platform:
https://stackoverflow.com/questions/43775551/how-to-limit-memory-and-cpu-usage-in-python-under-windows

**Comment by henryruhs** [comment]
I updated the fork using `win32api` - please try again.

**Comment by kex0** [comment]
> I updated the fork using `win32api` - please try again.
```
Traceback (most recent call last):
  File "G:\roop2\run.py", line 216, in <module>
    limit_resources()
  File "G:\roop2\run.py", line 54, in limit_resources
    win32api.SetProcessWorkingSetSize(-1, memory, memory)
AttributeError: module 'win32api' has no attribute 'SetProcessWorkingSetSize'
```

**Comment by henryruhs** [comment]
ChatGPT: This could be due to a version mismatch or an issue with the installation of the win32api module. You can try updating or reinstalling the module to see if this resolves the issue.

Here's an example of how you can update the win32api module using pip:

```
pip install --upgrade pywin32
```

**Comment by kex0** [comment]
> ChatGPT: This could be due to a version mismatch or an issue with the installation of the win32api module. You can try updating or reinstalling the module to see if this resolves the issue.
> 
> Here's an example of how you can update the win32api module using pip:
> 
> ```
> pip install --upgrade pywin32
> ```
> 
> @kex0 in case you are a dev... spend the 5 minutes and **fix** it for us

I couldn't make it run with pywin32 so I did this but I still run out of memory.
```
            import ctypes
            kernel32 = ctypes.windll.kernel32
            kernel32.SetProcessWorkingSetSize(-1, ctypes.c_size_t(memory), ctypes.c_size_t(memory))
```

I'll keep looking into it.

**Comment by kex0** [comment]
> @kex0 I came accros that issue... there is something fancy like an `memory_arena_shrinkage`. Not sure if this helps but instead of setting max memory via the Python level we could try to pass the correct provider options.
> 
> [microsoft/onnxruntime#14526 (comment)](https://github.com/microsoft/onnxruntime/issues/14526#issuecomment-1413457011)

I was playing with provider options yesterday with no success, I didn't try `enable_memory_arena_shrinkage` though.

**Comment by henryruhs** [comment]
I still switched to the ctypes approach for the moment... at least it should not crash then

**Comment by henryruhs** [comment]
@kex0 You can reach out to me via Discord if you like

**Comment by henryruhs** [comment]
@kex0 your code actual worked for the people and landed in the master - thanks for that

Memory issues can now be resolved using `--max-memory` flag.

**Comment by kex0** [comment]
It started working on my GPU yesterday too. When I get to my PC I'll try to identify why exactly.
