### ISSUE TITLE
Detected Face Priority or Manual Choice And More

### ISSUE THREAD

**Issue by mlnima** [s0md3v/roop#660]
I should first Thank You so much for this amazing project, Already I've made so many cool things.

Mostly I use Adobe Premier Pro while trying to deep fake video, If there is 2 person and I need the second one from the left, I could invert that part, and it's fine, but when there is 3+ person it becomes difficult, and take much much more editing.

- My First Suggestion is to make an input or a select box to target which face from the left should be changed.
- The second one is to allow higher resolution for the users who has better GPU
- The Third one is so much to ask if we can Deep Fake the voice this project becomes a masterpiece, I understand that in order to do that we will need a data set of targeted voices and more. But please please make it happen 😀

Thank you in advance and all the best

**Comment by henryruhs** [comment]
> My First Suggestion is to make an input or a select box to target which face from the left should be changed.

There is a issue to control face swapping via face position.

> The second one is to allow higher resolution for the users who has better GPU

Not possible as of third party model that is low resolution for now

> The Third one is so much to ask if we can Deep Fake the voice this project becomes a masterpiece, I understand that in order to do that we will need a data set of targeted voices and more.

> We have frame processors, so audio processors could be a thing. Just not in the near future
