### ISSUE TITLE
Frame processor face_enhancer crashed

### ISSUE THREAD

**Issue by gefule** [s0md3v/roop#663]
**Describe the bug**
python run.py -s 222.png -t 333.mp4 -o out/ --execution-provider cuda --keep-fps  --execution-threads 12 --max-memory 28 --frame-processor face_swapper face_enhancer

Frame processor face_enhancer crashed.

 have：
(roop) root@I13858e88d300601973:~/roop/models# ls
GFPGANv1.4.pth  inswapper_128.onnx

**To Reproduce**

**Details**
What OS are you using?
- [ ✔️] Linux

Are you try to use a GPU?
- [✔️ ] NVIDIA

**Screenshots**

**Comment by gefule** [comment]
success
python run.py -s 222.png -t 333.mp4 -o out/ --execution-provider cuda --keep-fps  --execution-threads 16 --max-memory 28 --frame-processor face_swapper face_enhancer

Processing: 100%|███████████████████| 267/267 [00:17<00:00, 15.15frame/s, memory_usage=06.40GB, execution_providers=['CUDAExecutionProvider'], execution_threads=16]
[ROOP.FACE-ENHANCER] Progressing...
Processing: 100%|███████████████████| 267/267 [02:09<00:00,  2.07frame/s, memory_usage=07.27GB, execution_providers=['CUDAExecutionProvider'], execution_threads=16]
[ROOP.CORE] Detecting fps...

GUP 12G, cpu12, memory32GB
face_enhancer is very slow, is there any optimization solution?

**Comment by bryanbrunetti** [comment]
I'm running into the same error, how did you fix it?

I'm using Windows 11 with an NVIDIA GPU
```
python run.py --execution-provider cuda --frame-processor face_swapper face_enhancer
Frame processor face_enhancer crashed.

**Comment by bryanbrunetti** [comment]
After debugging here: https://github.com/s0md3v/roop/blob/main/roop/processors/frame/core.py#L31
I was able to seethe exception: `ModuleNotFoundError: No module named 'gfpgan'`

`pip install gfpgan` fixed
