### ISSUE TITLE
Have seen three problems and have one suggestion

### ISSUE THREAD

**Issue by handypro2** [s0md3v/roop#664]
Hi, first of all thanks for this awesome tool. Especially for educational purposes, it is going to be something really good.
I wanted to report about 3 things. One of them is an obvious bug.

1-As i also shared the screenshots, you can clearly see the speed difference between 2 videos.
First video has needed 54 sec to enhance for 119 frames.
Second video has needed 7.7 [probably more than] minutes to enhance 261 frames.
This is happening if Roop UI is once opened and if i add second video with the same photo/video source or vice versa.
If i close both the console and Roop UI and restart it, it is faster than before.

2-Even i have 64GB Ram, if an Adobe Product is opened and uses any RAM or does not need any Graphics card, becuse it is working just at background, Roop speed is really slow. And interestingly if i do not open OBS, when i use Roop, on taskbar it does not show that it uses Cuda Nvidia. If i open OBW as the same time, even OBS will not used actively, then Roop starts to use Nvidia Card. [I already installed Cuda and activated in environment]

3- Even i use this parameter > --max-memory 56, Roop just uses max. about 16GB RAM.

And lastly, i do not know if it's already in your to-do list but, could you add an option in UI or even as selection in Windows Console, if it first analyzes the target video and if does exist more than one face, then we can select faces to add to the faces from target video?

Thanks for your hard work and i hope soon i can support you also.

Btw. I use 8 cores i7 CPU and Mobile Nvidia Card with 8GB VRAM.

- [x] Windows 

![Roop-Lack-Screenshot-2023-06-28-231235-1](https://github.com/s0md3v/roop/assets/119154016/d4fe8a66-6d1e-451e-8221-8ffccc75a6e7)
![Roop-Lack-Screenshot-2023-06-25-121918-2](https://github.com/s0md3v/roop/assets/119154016/ca0df6c3-bc5c-4918-87e3-1ac35df2a2fb)

- [x] NVIDIA
- [x] Intel

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by henryruhs** [comment]
1. If you have speed differences then just use the CLI
2. Roop is using CUDA if you setup your platform correct
3. Max memory is a limit, not the obligation to use all memory
