### ISSUE TITLE
assert 'detection' in self.models

### ISSUE THREAD

**Issue by rainynight100** [s0md3v/roop#666]
how to solve this problem？i have tried all my ways

**Comment by aakashag1** [comment]
The insightface model is not stored correctly. Go to this path - ~/.insightface/models/ and remove buffalo_1 model and the issue might resolve. This error comes when the insightface model which is loaded does not have a detection element which happens when the model is not loaded correctly.

**Comment by henryruhs** [comment]
For issues like that, Discord is the better place to resolve issues. Thanks
