### ISSUE TITLE
Event based threading (ref: #629)

### ISSUE THREAD

**Issue by octimot** [s0md3v/roop#667]
Hey,

Sorry for opening another issue, but #629 is locked for non-collaborators.

I would recommend instead of using the destroy() function which imo is not a safe way to kill threads (I'm concluding this without knowing how you intend to implement it further, of course) to use an observer pattern between the UI/CLI and the backend which checks if "destroy" was called and gracefully stops the execution of the thread from within the thread itself.

I think this is useful, especially if you're planning to update and keep the UI updates in a separate thread which would then have to communicate somehow with the model/backend.

I'd be happy to detail more on how this works, if you're interested.

Cheers!

**Comment by henryruhs** [comment]
@octimot Just unlocked https://github.com/s0md3v/roop/issues/629 again so let's continue talking about technical details there - best place would be Discord in my opinion and use issues just for the API drafts and contracts.

We have a [CONTRIBUTING.md](https://github.com/s0md3v/roop/blob/main/CONTRIBUTING.md) that you might right before.
