### ISSUE TITLE
I can´t create any video...

### ISSUE THREAD

**Issue by EngRS78** [s0md3v/roop#668]
**Describe the bug**
I open the roop, select photo and target when i click to start the creation of video starts arrives at 100% in seconds and the window closes. If i try the preview all swap face working well.

This is some kind of video resolution or time i try few seconds of video.
If use the examples videos and swap face all work.

Where can i see the errors of roop when create the video?

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

Are you try to use a GPU?
- [X ] No. I am not using the `---gpu` flag
- [X ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

NOTE: I made various clean install but without success

**Sanity Check**
- [X] I have the latest code from the github repository
- [ ] I have followed the installation guide

**Comment by bishalw** [comment]
NSFW videos doesn't work for the most part.

**Comment by EngRS78** [comment]
What is NSFW videos? What check?

**Comment by henryruhs** [comment]
NSFW filter kicked in

**Comment by EngRS78** [comment]
No solution?

**Comment by henryruhs** [comment]
Nope
