### ISSUE TITLE
There appear to be 1 leaked semaphore objects to clean up at shutdown

### ISSUE THREAD

**Issue by airib** [s0md3v/roop#669]
There appear to be 1 leaked semaphore objects to clean up at shutdown

**1. python run.py --execution-provider coreml**
2. running a few mins later 
4. See error:   resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Details**
What OS are you using?
- m1 pro 16G

Are you try to use a GPU?
- [ ] Mac apple

**Sanity Check**
- [ ] I have the latest code from the github repository
- [ ] I have followed the installation guide

**Comment by henryruhs** [comment]
Nothing I can do about that, just lower your threads

**Comment by phineas-pta** [comment]
memory leak problem, see #321 for possible solutions

for more help, join discord link in #110
