### ISSUE TITLE
Apple Silicon

### ISSUE THREAD

**Issue by josete89** [s0md3v/roop#672]
**Describe the bug**

**To Reproduce**
python run.py -s assets/rtest.jpeg -t assets/rodri-on-fire.mp4 -o assets/test-on-fire.mp4 --keep-audio --many-faces  --keep-fps  --max-memory 2

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [X ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [X ] Mac

**Screenshots**
Processing:  12%| | 177/1510 [01:36<10:35,  2.10frame/s, memory_usage=07.19GB, execution_providers=['CoreMLExecutionProvider'], execution_zsh: killed     python run.py --execution-provider coreml -s assets/richi.jpeg -t  -o      2
(roop-env) joseluisalcalaramos@MacBook-Pro-de-Jose roop % /Users/joseluisalcalaramos/.pyenv/versions/3.10.12/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

Ram went crazy over 100 GB

**Sanity Check**
- [X] I have the latest code from the github repository
- [X] I have followed the installation guide

**Comment by phineas-pta** [comment]
memory leak problem, see #321 for possible solutions

for more help, join discord link in #110

**Comment by josete89** [comment]
I've done the following:
```
 pip uninstall onnxruntime onnxruntime-silicon
 pip install onnxruntime-silicon==1.15.0
```
Now it works like a charm!
