### ISSUE TITLE
When the program prompts roop Processing to video succeed! but no video file is output

### ISSUE THREAD

**Issue by pt21014** [s0md3v/roop#673]
**Describe the bug**
When the program prompts roop Processing to video succeed! but no video file is output

**To Reproduce**

**Details**
What OS are you using?
Windows 10

Are you try to use a GPU?
 NVIDIA

**Screenshots**
![微信截图_20230701093122](https://github.com/s0md3v/roop/assets/76955998/f17fb850-943e-472f-a1bc-aec4a3ddd493)
![微信图片_20230701093103](https://github.com/s0md3v/roop/assets/76955998/3951457e-258c-47a3-bded-68144bfde1d6)

**Sanity Check**
- [ √] I have the latest code from the github repository
- [ √] I have followed the installation guide

**Comment by pt21014** [comment]
找到问题了，删除roop-main目录下的ffmpeg就可以生成视频了

**Comment by steseven** [comment]
hello。Have you solved this problem? How did u solve it?

**Comment by pt21014** [comment]
> 

Only put ffmpeg.exe in the roop-main/roop/ directory to generate video
