### ISSUE TITLE
Update GUI documentation

### ISSUE THREAD

**Issue by crowbait** [s0md3v/roop#675]
The latest update introduced a new GUI with new options, which are not explained in the README.

- What does the `Destroy`-Button do?
- `Keep frames` was self-explanatory before ("Keep extracted frame folder after processing"), but is not self-explanatory anymore.
- Same for `Many faces`. Does it swap all faces like before or is it something different?

I'd suggest adding tooltips to the three lower buttons as well as the option switches.

**Comment by henryruhs** [comment]
Nope, but thanks for the suggestions.

**Comment by crowbait** [comment]
Properly explaining the interface and options or at least make them self-explanatory is a "nope"..? Alright then...

**Comment by sahildeshpande** [comment]
Yeah have a read at all the closed issues lol. The response is always similar. This dude has some weird superiority complex.
