### ISSUE TITLE
DMDNET upscaler support?

### ISSUE THREAD

**Issue by 2blackbar** [s0md3v/roop#676]
It retains identity better than codeformer , i have it installed but would be nice for roop and sd webui, you give it reference image and it gets very close to the persons face

 https://github.com/csxmli2016/DMDNet)

![image](https://github.com/s0md3v/roop/assets/33694664/41b7bf16-4176-4aa3-9624-60c61f168465)

**Comment by henryruhs** [comment]
You can write your own frame processor with whatever restorer / upscaler you like to use.

https://github.com/s0md3v/roop/wiki/Write-your-Frame-Processor

We don't have the human resources to provide every code modification the community is requesting.
