### ISSUE TITLE
Cannot run Roop with GPU (Nvidia)

### ISSUE THREAD

**Issue by toodead** [s0md3v/roop#677]
(FYI I am super new to python/coding). I have followed all installation steps and have been using Roop through my CPU for days with no issues but since I installed it, I have not been able to use my GPU instead of my CPU.

When I run the run-roop-nvidia.bat, I get the error below and have tried all manners of fixes and updates but nothing has worked;

usage: run.py [-h] [-s SOURCE_PATH] [-t TARGET_PATH] [-o OUTPUT_PATH]
              [--frame-processor FRAME_PROCESSOR [FRAME_PROCESSOR ...]] [--keep-fps] [--keep-audio] [--keep-frames]
              [--many-faces] [--video-encoder {libx264,libx265,libvpx-vp9}] [--video-quality [0-51]]
              [--max-memory MAX_MEMORY] [--execution-provider {tensorrt,cuda,cpu} [{tensorrt,cuda,cpu} ...]]
              [--execution-threads EXECUTION_THREADS] [-v]
run.py: error: unrecognized arguments: --gpu-vendor nvidia

As I said above, everything is working great on the CPU version but I wanted to improve the processing times/load on my CPU. I keep seeing people talk about changing the execution provider to CUDA for Nvidia, which I have installed, but don't know where/how to do it.

I am on Windows 10 using a Nvidia RTX 3060 GPU.

Hoping someone can help. Couldn't find an Issue Report that sounded similar to my problem so sorry if there's already a report open on this.

**Comment by phineas-pta** [comment]
there is no file `run-roop-nvidia.bat`

u r using a custom version, not original roop

**Comment by toodead** [comment]
I think I am using a one-line installed version

**Comment by oracle9i88** [comment]
+1

**Comment by phineas-pta** [comment]
u should ask its author for any problem, unknown if any other files change which may incompatible with original roop

**Comment by toodead** [comment]
Okay will check with them, thanks for the help.

**Comment by henryruhs** [comment]
you don't need a bat file to run a simple cli like ours... see the wiki for the cpu only issue.
