### ISSUE TITLE
When the program prompts roop Processing to video succeed! but no video file is output，just output some picture

### ISSUE THREAD

**Issue by steseven** [s0md3v/roop#680]
**Describe the bug**
When the program prompts roop Processing to video succeed! but no video file is output，just output some picture

**To Reproduce**

**Details**
What OS are you using?
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag

**Screenshots**
![image](https://github.com/s0md3v/roop/assets/15796999/d05bf97a-711a-4f3f-a3d4-437e0755c069)
![image](https://github.com/s0md3v/roop/assets/15796999/62ad2024-2e74-4165-aaee-ceb75df9d2db)
![image](https://github.com/s0md3v/roop/assets/15796999/792af50e-6b94-4900-a6a9-e194795b38c6)

**Sanity Check**
I have the latest code from the github repository
I have followed the installation guide

**Comment by henryruhs** [comment]
I cannot reproduce this...

**Comment by steseven** [comment]
> I cannot reproduce this...

Have other people encountered this issue,is there a solution available?
