### ISSUE TITLE
My PC turns off after some time of rendering with GPU

### ISSUE THREAD

**Issue by snackye** [s0md3v/roop#683]
I am using this command python run.py --execution-provider cuda

After sometime - 3-4 minutes of rendering my PC turns off.  I have  RTX 3090

Is there any way to reduce the power or any fix to this? could it be due to temperature I guess or idk.

UPDATE:

I have just installed EVGA PX1 and I have tried GPU temperatura and it was under 60º C all time. 

So it might be due to CPU temp then?, I will check too

2ND UPDATE:

Yes CPU runs high %  I have a i9 12900k with a liquid cooled corsair , How can I keep my cpu under certain cpu usage? 

At the final step it goes tp 100%

**Comment by snackye** [comment]
I have just installed EVGA PX1

I am rendering again now, and I've put fan speed at 100%

Wish i could understand the clock speed thing to limit it

**Comment by snackye** [comment]
I see temperatures of CPU going high, so I had to tweak the fan settings, and try to reduce the maximum % of CPU usage, still testing how it goes

**Comment by phineas-pta** [comment]
r u overclocking/undervolting ?

**Comment by snackye** [comment]
> r u overclocking/undervolting ?

I am not overclocking or undervolting, and I've been using this PC for 1 year to render other things and never had an issue, the problem is at final stage of roop processing vid CPU heats too much and very quickly and PC turns off for security.

I have seen that on windows, on energy plans you can turn down CPU usage maximum but I'm not sure if that works because I set it up at 90% and at windows task manager I still see 100% of CPU usage.

However when I tirned all fans at maximum speed and water pump I successfully rendered the video, but It would be good to limit CPU in some way, I will keep testing

**Comment by henryruhs** [comment]
Discord
