### ISSUE TITLE
roop cannot run

### ISSUE THREAD

**Issue by jerryWu1985** [s0md3v/roop#686]
![image](https://github.com/s0md3v/roop/assets/138738968/15adb7f9-2c27-4c3f-8f46-38ef49843474)
As shown in the figure

**Comment by ShionWakanae** [comment]
but, that is NOT roop.

**Comment by qq515114557** [comment]
pip install insightface==0.7.3

**Comment by henryruhs** [comment]
Please stop using GitHub for platform and installation issues - we have DIscord for that!
