### ISSUE TITLE
python run.py --execution_provider cuda  ，linux, Unable to use GPU 

### ISSUE THREAD

**Issue by liushifu12138** [s0md3v/roop#687]
![b6f87c849566dbadf2da092aa19a88b](https://github.com/s0md3v/roop/assets/71754694/79dc9695-d216-4e24-a27b-76aaa1975d49)

**Comment by phineas-pta** [comment]
what's your gpu and cuda

**Comment by liushifu12138** [comment]
4090 cuda11.1

**Comment by phineas-pta** [comment]
![](https://github.com/s0md3v/roop/assets/37548991/68991b4b-449d-4c46-89a0-1819dc634e2b)

**Comment by henryruhs** [comment]
This is a software issue tracker, not a support ticket system.
