### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'configure'

### ISSUE THREAD

**Issue by ghassansobh** [s0md3v/roop#691]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [ ] I have the latest code from the github repository
- [ ] I have followed the installation guide

**Comment by henryruhs** [comment]
See troubleshooting in our wiki...

**Comment by Amritha-07** [comment]
Same issue here have you solved it?
