### ISSUE TITLE
Roop on OpenCL

### ISSUE THREAD

**Issue by mberg2007** [s0md3v/roop#693]
Well it's a simple case of how to support GPU accelleration for users who don't happen to own nVidia GPU's.

I don't have the insight to make specific technical suggestions so apologies for the somewhat vague details here. However it is my understanding that the OpenCL framework supports AMD GPU's so I'm hoping there is some way to have an execution provider for OpenCL.

**Comment by henryruhs** [comment]
We are limited to the onnxruntime execution providers.

**Comment by mberg2007** [comment]
Thanks for the quick response.

Again not an expert here but there seems to be an onnx runtime for AMD called ROCm.

Would this somehow be possible to use?

**Comment by henryruhs** [comment]
I removed it from the installation guide as this is a deadend for most users as you have to compile your own version from source and the setup afterwards seems to be very... very difficult.
