### ISSUE TITLE
Manual face tracking and video reference for selecting face.

### ISSUE THREAD

**Issue by TROLL-PIRATE** [s0md3v/roop#695]
From what I have observed with this app, is when it comes to certain pan ranges such as close up zoom or far, the face tracking breaks.
Other issues, such as face turning, usually leads to the mask not fading out naturally, instead you're left with a strange dissolve out effect.

It could possibly be a Cuda version issue.

I think using video as face reference, or an additional for face angles, select more faces for the same face, could possibly improve the face tracking.

**Comment by henryruhs** [comment]
I would love to have a chat with your, but for that we have Discord... GitHub is for software issue tracking.
