### ISSUE TITLE
Full face swap - So that face structure is also swapped. i.e. a boxy face swapped with a round face

### ISSUE THREAD

**Issue by QaisarRajput** [s0md3v/roop#697]
I see in practice that if the face structure doesn't match. The results don't look as convincing, which limits the use of this in many cases. I think there is something which can be done using the 3d mesh Insightface provides. Don't know if such a setup is already applied and isn't that apparent, but i think there is a potential here.

**Comment by henryruhs** [comment]
This is not "make a wish" but a software issue tracker... if you want to chat or share your thoughts, we have an active community on Discord.
