### ISSUE TITLE
How to face swap with the biggest face in a photo of multiple faces?

### ISSUE THREAD

**Issue by arnold408** [s0md3v/roop#698]
Hello,
in image to image photo swapping, if source photo has one face, and target photo has multiple faces, roop is doing face swap with the left most face.
How to face swap with the biggest face in the target photo of multiple faces? 
(without knowing the position of that biggest face)

Thanks

**Comment by henryruhs** [comment]
I think it depends how much the face is in the foreground, but general speaking: there is no accurate way of doing this.
