### ISSUE TITLE
[Feature Request] Improve software's ability to handle faces with glasses

### ISSUE THREAD

**Issue by mammuthus** [s0md3v/roop#703]
I suggest implementing an improved algorithm that can accurately handle faces with glasses when creating deepfake videos. Currently, the software struggles to produce convincing results when the input face photo includes glasses, resulting in noticeable discrepancies in the final video.

Enhancing the software's capability to work with glasses will significantly improve the versatility and user experience of the tool, particularly for users who wear glasses or for scenarios where the character image includes glasses.

**Comment by henryruhs** [comment]
Sorry but the models are not made by us. Nothing we can do about your request.
