### ISSUE TITLE
Just close without do anything

### ISSUE THREAD

**Issue by kimimorgam** [s0md3v/roop#704]
(venv) C:\roop>python run.py
Downloading: 529MB [00:25, 22.1MB/s]
1/1 [==============================] - 1s 621ms/step
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\kimim/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\kimim/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\kimim/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\kimim/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\kimim/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
1/1 [==============================] - 1s 580ms/step
1/1 [==============================] - 1s 579ms/step
100%|██████████████████████████████████████████████████████████████████████████| 10800/10800 [00:09<00:00, 1088.27it/s]

---------------------------------------------

I cant understand, no erros, all parts of instalation OK, what is happening to me?

**Comment by kimimorgam** [comment]
After that, the program just close and do not save the file.

**Comment by henryruhs** [comment]
That's what happens using porn ... no error messages as it would be easy to identify the code for the check

**Comment by kimimorgam** [comment]
lol, im not using for porn and this are happening to all vids :/

But ok, i will try reinstalt using venv
