### ISSUE TITLE
CUDA version

### ISSUE THREAD

**Issue by liushifu12138** [s0md3v/roop#705]
**Describe the bug**
CUDA must be 11.8? CUDA12.0 not work. 

**To Reproduce**

**Details**
What OS are you using?
- [! ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [! ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [ ] I have the latest code from the github repository
- [ ] I have followed the installation guide

**Comment by blurymind** [comment]
why close this, it still doesnt work with 12 :(
