### ISSUE TITLE
--face-position will never work as expected

### ISSUE THREAD

**Issue by felixsanz** [s0md3v/roop#709]
If it works with indexes (0, 1, 2...) it will never work because if you assign:

Face1: Id=0
Face2: Id=1

When Id=0 dissapears from a frame, now Id=1 will be Id=0 and Face1 will be replaced in this subject. And that is wrong because that face is supposed to be Face2. This will happen A LOT. Maybe because Id=0's head is turned to one side too much, or because there is a hand covering the face... whatever. There will be a constant swap between subject faces.

It is possible somehow to not rely on numeric indexes but some sort of unique ids? Like Id=0 will be Id=a53b45c7762 and that Id will never change in the whole video. So we can assign an specific face to an specific unique id?

**Comment by henryruhs** [comment]
Not true... that position/index is used to create a face reference for a later face recognition that is applied to all frames.

**Comment by felixsanz** [comment]
> Not true... that position/index is used to create a face reference on a specific frame for a later face recognition that is matching the face on all frames.
> 
> Update the next branch, the CLI ARGS have been renamed 2 days ago.
> 
> How the face analyser is getting it's position ordering is actually a mystery, you need to trail and error unless there is a UI.

Oh, this name makes so much sense. Just to confirm... once face analyser tags a face, it will be the same for the whole video? Like fixing the face.

And does this happen even if scene changes? let's say you want to face swap john travolta on a 2 hour movie, it should work as intended?

**Comment by henryruhs** [comment]
Once a face reference has been created it can be used across various scenes, depending how good the reference is.

I plan to create a simple UI for that in the preview window, so we can select via frame and by clicking on a boxed face.

**Comment by felixsanz** [comment]
> Once a face reference has been created it can be used across various scenes, depending how good the reference is.
> 
> I plan to create a simple UI for that in the preview window, so we can select via frame and by clicking on a boxed face.

Thanks. The reference is created by the model and we have no way to know how the model create them right?

**Comment by henryruhs** [comment]
Nope, the model only identifies the faces but that order is somehow random. We can manipulate the reference at any time via the UI afterwards.
