### ISSUE TITLE
GPU work suggestion

### ISSUE THREAD

**Issue by allen1224** [s0md3v/roop#710]
When using ROOP for video face swapping, even with GPU.  the CPU usage remains high, especially during the frame extraction and creating video. Hope to use GPU  for theframe extraction and video encoding , or at least for video encoding?
ps: im not sure , it's seems like GFPGAN is also work on CPU?

**Comment by henryruhs** [comment]
We use ffmpeg for frame extraction and video creation, it should use acceleration if available.

**Comment by allen1224** [comment]
> We use ffmpeg for frame extraction and video creation, it should use acceleration if available.
> 
> GFPGAN is using CPU, CUDA and MPS.

guess ffmpeg  is using CPU in default mode
