### ISSUE TITLE
Execution_threads not work when enable face_enhancer

### ISSUE THREAD

**Issue by LeiHao0** [s0md3v/roop#712]
**Describe the bug**

Execution_threads become to 1 thread when face_enhancer enabled.

**To Reproduce**
```
python run.py --execution-provider coreml \
    -s xxx.png \
    -t xxx.mp4 \
    -o output.mp4 \
    --frame-processor face_swapper face_enhancer \
    --keep-audio \
    --keep-fps \
    --execution-threads 20 
```

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [x] Mac (M2 Ultra)

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [x] Mac

**Screenshots**
```
inswapper-shape:     136/136 [00:17<00:00,  7.76frame/s, memory_usage=06.59GB, execution_providers=['CoreMLExecutionProvider'], execution_threads=20]
[ROOP.FACE-ENHANCER] 136/136 [08:56<00:00,  3.95s/frame, memory_usage=07.21GB, execution_providers=['CoreMLExecutionProvider'], execution_threads=20]
```
face_swapper took 17s with threads works but face_enhancer took 8:56s with only 1 thread works. 

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by henryruhs** [comment]
Nothing I can do about it, it uses multithreading but in a limited way as the gpfgan is not thread safe. On next branch you might have better results as MPS for MacOS is enabled.
