### ISSUE TITLE
Fail to install onnxruntime-silicon following installation guide

### ISSUE THREAD

**Issue by LronDC** [s0md3v/roop#713]
**Describe the bug**
Fail to install onnxruntime-silicon==1.13.1 follow the [guide](https://github.com/s0md3v/roop/wiki/2.-Acceleration#coreml-execution-provider-apple-silicon)
```shell
ERROR: Could not find a version that satisfies the requirement onnxruntime-silicon==1.13.1 (from versions: none)
ERROR: No matching distribution found for onnxruntime-silicon==1.13.1
```

**To Reproduce**
Follow the installation guide, using conda environment with python 3.10.11 and pip 23.1.2, get the error above.
**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [x] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [x] Mac

**Screenshots**
![image](https://github.com/s0md3v/roop/assets/59912384/34844b13-7b66-4fc1-9181-4aeb98e88fcb)

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by henryruhs** [comment]
Discord for help
