### ISSUE TITLE
Why is there no video file output after the processing is successful?

### ISSUE THREAD

**Issue by bardonnie** [s0md3v/roop#715]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [x] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [x] Mac

**Screenshots**

**Sanity Check**
- [ ] I have the latest code from the github repository
- [ ] I have followed the installation guide

2023-07-16 09:29:35.308 Python[24221:166889] +[CATransaction synchronize] called within transaction
2023-07-16 09:29:40.091 Python[24221:166889] +[CATransaction synchronize] called within transaction
2023-07-16 09:29:55.863 Python[24221:166889] +[CATransaction synchronize] called within transaction
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/donnie/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/donnie/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/donnie/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/donnie/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/donnie/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
100%|████████████████████████████████████████| 247/247 [00:00<00:00, 380.91it/s]
[ROOP.CORE] Creating temp resources...
[ROOP.CORE] Extracting frames...
[ROOP.FACE-SWAPPER] Progressing...
Processing:   0%|                                    | 0/247 [00:00<?, ?frame/s]Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Processing: 100%|█| 247/247 [03:55<00:00,  1.05frame/s, memory_usage=03.65GB, ex
[ROOP.CORE] Creating video with 30.0 fps...
[ROOP.CORE] Restoring audio might cause issues as fps are not kept...
[ROOP.CORE] Processing to video succeed!

**Comment by henryruhs** [comment]
Use Discord, this kind of issues cannot be resolved via GitHub. Especially without an error or exception thrown.
