### ISSUE TITLE
illegal hardware instruction  python run.py

### ISSUE THREAD

**Issue by galois777** [s0md3v/roop#716]
**Describe the bug**
Getting error message `zsh: illegal hardware instruction  python run.py`

**To Reproduce**
1. Go to 'roop' in terminal
2. Run python run.py
3. See error

**Details**
What OS are you using?
- [x] Mac Ventura

Are you try to use a GPU?
- [x] No. I am not using the `---gpu` flag

**Comment by henryruhs** [comment]
Read our wiki -> troubleshooting
