### ISSUE TITLE
--gpu flag but CUDA isn't available on your system. (I have CUDA installed)

### ISSUE THREAD

**Issue by ZeroCool22** [s0md3v/roop#72]
![Screenshot_10](https://github.com/s0md3v/roop/assets/13344308/b66db908-9aff-4473-91a1-f079bfa44f36)

So...?

**Comment by s0md3v** [comment]
It means its not installed properly.

**Comment by ZeroCool22** [comment]
> It means its not installed properly.

Well, could you explain what is properly, then?

Because i downloaded all files from the Nvidia website and follow the normal procedure...

https://www.youtube.com/watch?v=ctQi9mU7t9o

**(Minus steps 6 & 7).**
