### ISSUE TITLE
UI element become invisible. 

### ISSUE THREAD

**Issue by altezza04** [s0md3v/roop#720]
**Describe the bug**
All UI elements are invisible, but I can still click on the button by guess and everything works fine.

**To Reproduce**
Just open the APP

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [x ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ X] Mac

**Screenshots**
<img width="634" alt="Screenshot 2023-07-17 at 1 47 15 PM" src="https://github.com/s0md3v/roop/assets/59946405/3ceeb85c-b8fc-4dbe-a95c-ec90b632a1f2">

**Sanity Check**
- [X ] I have the latest code from the github repository
- [ ] I have followed the installation guide

**Comment by henryruhs** [comment]
See our troubleshooting in the wiki...
