### ISSUE TITLE
Functions and buttons on the webui cannot be displayed

### ISSUE THREAD

**Issue by xiaoshitoukb** [s0md3v/roop#721]
After the webui is started, the content in the application cannot be seen.
This command pip3 install -r requirements.txt has already been used and pip3 install customtkinter== 5.1.3 & tk ==0.1.0 has been used.I do not know how to solve it, please help to see what the problem caused.Thank you very much!

<img width="600" alt="image" src="https://github.com/s0md3v/roop/assets/20159437/6e03476a-ace5-4136-917c-62ad875e97d3">

**Comment by henryruhs** [comment]
https://github.com/s0md3v/roop/wiki/4.-Troubleshooting#blank-ui-under-macos
