### ISSUE TITLE
 No module named 'onnxruntime'

### ISSUE THREAD

**Issue by orgsiedur** [s0md3v/roop#728]
question：No module named 'onnxruntime'？
![image](https://github.com/s0md3v/roop/assets/139244302/4d93ae7f-44a1-40a5-9092-116a5c8a0f46)

**Comment by MantisTree** [comment]
follow the installation steps - on the homepage under **How do I install it?** click the link at the end of the line starting with **Basic**

note the command in step 3: **pip install -r requirements.txt** which will install onnx

**Comment by henryruhs** [comment]
Stop opening issues...
