### ISSUE TITLE
name 'args' is not defined

### ISSUE THREAD

**Issue by Moeblack** [s0md3v/roop#73]
I use the --gpu flag to run the program.
![image](https://github.com/s0md3v/roop/assets/28835093/332f46d6-62bb-4c51-9052-4394a5da9045)

**Comment by s0md3v** [comment]
ah man, i should really get some sleep. thanks for the heads up. fixed it.

**Comment by Moeblack** [comment]
> ah man, i should really get some sleep. thanks for the heads up. fixed it.

you‘d better have a break, thanks for your working.

**Comment by LokeYourC3PH** [comment]
> > ah man, i should really get some sleep. thanks for the heads up. fixed it.
> 
> you‘d better have a break, thanks for your working.

Moe, how did you install TensorRT on Windows? Many of us can't get it to work. Mind sharing?

**Comment by LokeYourC3PH** [comment]
Was just gonna mention that I face the same issue @s0md3v
But mate, get some sleep. I know how it is to be in the "I WANNA FIX THIS" death spiral 😂
