### ISSUE TITLE
[Bug ?] De-Aging, near no effect

### ISSUE THREAD

**Issue by Sor3nt** [s0md3v/roop#737]
## Description

I'm not sure if this is a bug, but it's a bit strange.
I try to make people younger but the result is near the same as input.

Do not get me wrong, once i use a different face it works very well. It just do not like the same face.

## Details

I try to de-age the new "Back to the Future 4" Trailer, the issue appear on any character.

I took a young looking image from Michael J. Fox also from Emmett Brown.

The result is always the same, the "swap" is applied but they are still damn old, far away from the given input.

Any ideas ?

What operating system are you using?

- [x] Windows 
- [ ] MacOS (Apple Silicon)
- [ ] MacOS (Apple Legacy)
- [ ] Linux
- [ ] Linux in WSL

What execution provider are you using?

- [ ] CPU
- [x] CUDA
- [ ] CoreML
- [ ] DirectML
- [ ] OpenVINO
- [ ] Other

What version of Roop are you using?

- [ ] 1.0.0
- [x] 1.1.0
- [x] 1.2.0
- [ ] next

**Comment by henryruhs** [comment]
I have a hard time to understand this issue. Did you [write your own frame processor](https://github.com/s0md3v/roop/wiki/Write-your-Frame-Processor) using something like [Fast-AgingGAN](https://github.com/HasnainRaz/Fast-AgingGAN)?

**Comment by Sor3nt** [comment]
sry 🙈  

no, i did not, but thank you for the links!

But why would be a "custom" frame processor required ? I mean roop should swap the face anyway.

So this is my Input Image

![michael-j-fox-high-school](https://github.com/s0md3v/roop/assets/1684233/298c37d7-b2e7-4808-a08b-57193615a51c)

and this is the result (left original, right result)

![Screenshot 2023-07-19 220918](https://github.com/s0md3v/roop/assets/1684233/a740c2b7-09de-41b6-ae5c-056b81cc1c72)

**Comment by henryruhs** [comment]
> But why would be a "custom" frame processor required

To let someone age that is currently 20 years? :D

The swap works for me... closing the issue

![output](https://github.com/s0md3v/roop/assets/1835397/e2b0be5e-2b1f-406b-a2cb-9ba0cd554eb1)

**Comment by henryruhs** [comment]
Join Discord for help, I will not confirm it twice that something is working
