### ISSUE TITLE
even after installing python using home-brew it says PIP not found, unable to resolve this

### ISSUE THREAD

**Issue by dhawan1997** [s0md3v/roop#74]
rohit@RDs-MacBook-Pro ~ % cd roop
pip install -r requirements.txt
zsh: command not found: pip
rohit@RDs-MacBook-Pro roop % 

But above this I already checked for PIP:

rohit@RDs-MacBook-Pro ~ % brew install pip
Warning: No available formula with the name "pip". Did you mean pipx, pig, pit, php, pup, pcp, zip, sip or vip?
pip is part of the python formula:
  brew install python

**Comment by LokeYourC3PH** [comment]
That is an issue with your system, not with this software. You gotta be able to install pip yourself at least somewhat. Check tutorials if need be.

**Comment by dhawan1997** [comment]
This is an error I get after installing till step 5 and then when i try the command

rohit@RDs-MacBook-Pro roop % python run.py
zsh: command not found: python


Which is why I changed to python3

rohit@RDs-MacBook-Pro roop % python3 run.py
Traceback (most recent call last):
  File "/Users/rohit/roop/run.py", line 22, in <module>
    import tkinter as tk
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'


But even then some error

**Comment by dhawan1997** [comment]
When I try to install 

rohit@RDs-MacBook-Pro roop % pip install onnxruntime-silicon
ERROR: Could not find a version that satisfies the requirement onnxruntime-silicon (from versions: none)
ERROR: No matching distribution found for onnxruntime-silicon

It gives an error on my M1 Mac

**Comment by LokeYourC3PH** [comment]
Again, it's an issue with your usage of Python. You seem to not know how to properly install or use Python.

I don't know what command it is for Mac (would never touch it), but you gotta do "sudo apt-get install python3-tk" amongst others. You are missing various dependencies, which is something you must solve on your end first.

**Comment by TitasDas** [comment]
This issue is a known issue with mac and lies outside the scope of this particular project.

**Comment by LokeYourC3PH** [comment]
> This issue is a known issue with mac and lies outside the scope of this particular project.

Exactly this. It's a Mac issue in particular, so fixing Mac Python is something that you need to do on your end. Or just make it easier on yourself and install a Virtual Machine for Windows/Linux on your Mac. Better yet, dual boot a Linux system on your Mac if possible.

**Comment by dhawan1997** [comment]
> > This issue is a known issue with mac and lies outside the scope of this particular project.
> 
> Exactly this. It's a Mac issue in particular, so fixing Mac Python is something that you need to do on your end. Or just make it easier on yourself and install a Virtual Machine for Windows/Linux on your Mac. Better yet, dual boot a Linux system on your Mac if possible.

OK thank you. Sorry yes I am a noob who came across this, hence all my stupid questions. Can you guide me what are the conmands to unistall all the things I install in "Installation" Step 1 through 5. just to make sure I can clean of the space and try with virtual machine tomorrow

**Comment by LokeYourC3PH** [comment]
> > > This issue is a known issue with mac and lies outside the scope of this particular project.
> > 
> > 
> > Exactly this. It's a Mac issue in particular, so fixing Mac Python is something that you need to do on your end. Or just make it easier on yourself and install a Virtual Machine for Windows/Linux on your Mac. Better yet, dual boot a Linux system on your Mac if possible.
> 
> OK thank you. Sorry yes I am a noob who came across this, hence all my stupid questions. Can you guide me what are the conmands to unistall all the things I install in "Installation" Step 1 through 5. just to make sure I can clean of the space and try with virtual machine tomorrow

https://docs.python-guide.org/starting/install3/osx/
