### ISSUE TITLE
which one would be more suitable for roop?3060 12G or 4060?

### ISSUE THREAD

**Issue by guanxing20** [s0md3v/roop#743]
I don't have a large budget, and I have two options for graphics cards: the 3060 12G and the 4060. The 3060 12G has a CUDA core count of 3584, while the 4060 has a CUDA core count of 3072. Additionally, the 3060 12G has 4GB more VRAM compared to the 4060. Based on these two pieces of information, it seems that the 3060 12G is better. However, when I checked the official NVIDIA website, I found that the CUDA capability of the 3060 is 8.6, while the 4060 has a capability of 8.9. This has left me quite confused. Could you please provide some advice on which one would be more suitable for roop? Thank you.

**Comment by henryruhs** [comment]
Do you watch tech reviews? The 4060 has the worst value ever and 3060 outperforms it... being low on budget, buy a used Tesla K80 on ebay for 150$ or less...  4.992 CUDA Cores and 24GB of VRAM

**Comment by guanxing20** [comment]
I don't follow tech reviews, and I'm not considering a used graphics card. Since the 4060 has the worst value, I'll go with the 3060 12G. Thank you for your advice.

**Comment by guanxing20** [comment]
> Do you watch tech reviews? The 4060 has the worst value ever, in some scenarios the 3060 is actual faster. Being low on budget, I suggest to buy a used Tesla K80 on eBay for 110 - 150€... 4.992 CUDA Cores and 24GB of VRAM
I don't follow tech reviews, and I'm not considering a used graphics card. Since the 4060 has the worst value, I'll go with the 3060 12G. Thank you for your advice.

**Comment by henryruhs** [comment]
Make your decision based on numbers... cuda core per euro :-)

https://www.studio1productions.com/Articles/NVidia-GPU-Chart.htm

**Comment by guanxing20** [comment]
> Make your decision based on numbers... cuda cores per euro :-)
> 
> https://www.studio1productions.com/Articles/NVidia-GPU-Chart.htm
OK！Thank you for your advice.
