### ISSUE TITLE
[Installation] Getting error while installing roop in Mac system

### ISSUE THREAD

**Issue by boxty3456** [s0md3v/roop#745]
The error message i am getting while trying to install the roop using the command pip install -r requirements.txt in MAC system. I am using python 3.10.0

ERROR: Could not find a version that satisfies the requirement onnxruntime-coreml==1.13.1 (from versions: none)
ERROR: No matching distribution found for onnxruntime-coreml==1.13.1

**Comment by henryruhs** [comment]
Use Python 3.9
