### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by branwith** [s0md3v/roop#746]
## Description

A concise description of the bug and how to reproduce it.

## Error

Paste the error or exception from your console:

```
![Screenshot 2023-07-21 at 8 20 31 PM](https://github.com/s0md3v/roop/assets/87488089/c2097b99-47c1-468b-ace9-e49f348d1460)


Stuck here, more than 30 mins
```

## Details

What operating system are you using?
- [ ] MacOS (Apple Legacy)

What execution provider are you using?
- [ ] CPU

What version of Roop are you using?

**Comment by henryruhs** [comment]
Update to latest version... that screenshot is from 6 weeks ago
