### ISSUE TITLE
The tkinterdnd2 library is not compatible with the M1 chip, even under Rosetta 2.

### ISSUE THREAD

**Issue by shadybrook** [s0md3v/roop#748]
Please **BE AWARE** platform and installation issues!

The  tkinterdnd2 library is not compatible with the M1 chip, even under Rosetta 2, therefore giving trouble to launch the UI for the roop-main on my MacBook Air 2020 M1 . Please try to use an alternate library. The arms64 architecture won't allow you to run tkinterdnd2. The developers of tkinterdnd2 are aware of the compatibility issues with the M1 chip. They are currently working on a port of the library to the M1 chip, but there is no ETA for its release.

**Comment by henryruhs** [comment]
That's why we added this: https://github.com/s0md3v/roop/blob/main/requirements.txt#L10-L11

**Comment by shadybrook** [comment]
Thankyouu, sorry for the trouble
