### ISSUE TITLE
[Bug] Squares around enhanced faces

### ISSUE THREAD

**Issue by dayuwl** [s0md3v/roop#750]
Facial optimization with framed faces。There will be obvious squares on the face

**Comment by henryruhs** [comment]
Thanks, I'm aware of it... either I revert cropped faces in the enhancer (as of performance reason) or find a solution.

![image(1)](https://github.com/s0md3v/roop/assets/1835397/f237b446-95d9-498d-a1be-a72cbb0ef7fb)

**Comment by dayuwl** [comment]
I'm looking forward to your fixes, this version is much faster!

**Comment by henryruhs** [comment]
Fixed in [next](https://github.com/s0md3v/roop/tree/next) branch via https://github.com/s0md3v/roop/commit/97633db25956a8a1789b775538337c4fc4d55427

Please reopen issue if boxes are is still present.
