### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by MicheleDaVinci** [s0md3v/roop#753]
## Description

Hi after upgrading to the new version i encountered this problem. I have installed all required modules.

Thanks good job.

python run.py --execution-provider cuda

## Error

Paste the error or exception from your console:

```
(DeepRoop) c:\DeepRoop>python run.py --execution-provider cuda
Traceback (most recent call last):
  File "c:\DeepRoop\run.py", line 3, in <module>
    from roop import core
  File "c:\DeepRoop\roop\core.py", line 24, in <module>
    import roop.ui as ui
  File "c:\DeepRoop\roop\ui.py", line 5, in <module>
    from tkinterdnd2 import TkinterDnD, DND_ALL
ModuleNotFoundError: No module named 'tkinterdnd2'
```

## Details

What operating system are you using?

- [x ] Windows 
- [ ] MacOS (Apple Silicon)
- [ ] MacOS (Apple Legacy)
- [ ] Linux
- [ ] Linux in WSL

What execution provider are you using?

- [ ] CPU
- [x ] CUDA
- [ ] CoreML
- [ ] DirectML
- [ ] OpenVINO
- [ ] Other

What version of Roop are you using?

- [ ] 1.0.0
- [ ] 1.1.0
- [ x] 1.2.0
- [ ] next

**Comment by henryruhs** [comment]
https://github.com/s0md3v/roop/wiki/4.-Troubleshooting
