### ISSUE TITLE
how to choose  a specific face to swap in multi face target image/video ?

### ISSUE THREAD

**Issue by gfyfiyfiyyv** [s0md3v/roop#757]
i m using the command line not the GUI 
  i think the answer involve using the following  params but i did not find any examples 
  
  --reference-face-position REFERENCE_FACE_POSITION        position of the reference face
  --reference-frame-number REFERENCE_FRAME_NUMBER          number of the reference frame
  --similar-face-distance SIMILAR_FACE_DISTANCE            face distance used for recognition

**Comment by henryruhs** [comment]
Does this help? https://github.com/s0md3v/roop/wiki/Understand-the-face-vocabulary

**Comment by gfyfiyfiyyv** [comment]
thanks mate that actually very helpful
i just need some clarifications :
let's suppose i choose REFERENCE_FRAME_NUMBER that contain three faces how are they ordered ?
from left to right of from right to left ?
and does ordering position start from 0 or 1 ?
thanks in advance

**Comment by henryruhs** [comment]
The face analyser is hard to predict, that means it has some kind of random order while detection. I could sort the faces be their size, but not sure if this is a huge win.

0 to 2 if you have 3 facea
