### ISSUE TITLE
despite having python installed i can't get it to work

### ISSUE THREAD

**Issue by JO-R-D-AN** [s0md3v/roop#763]
and my ticket keeps getting falsely closed
C:\Users\username\Desktop\New folder\roop>python run.py
Traceback (most recent call last):
File "run.py", line 3, in
from roop import core
File "C:\Users\username\Desktop\New folder\roop\roop\core.py", line 33
def parse_args() -> None:
^
SyntaxError: invalid syntax
this is the error i'm getting (remember, i do have python installed)
i'm on windows 10

**Comment by Orchoidizer** [comment]
is python properly on your 'PATH'in environment variables?

**Comment by henryruhs** [comment]
NO SUPPORT FOR INSTALLATION ON GITHUB - STOP OPENING ISSUES
