### ISSUE TITLE
[Bug]Frame processor face_enhancer not found

### ISSUE THREAD

**Issue by xqqcylh6780** [s0md3v/roop#767]
## Description

A concise description of the bug and how to reproduce it.

## Error

Paste the error or exception from your console:

``` python run.py --execution-provider cuda --frame-processor face_enhancer
Frame processor face_enhancer not found.

```

## Details

What operating system are you using?

- [x] Windows 
- [ ] MacOS (Apple Silicon)
- [ ] MacOS (Apple Legacy)
- [ ] Linux
- [ ] Linux in WSL

What execution provider are you using?

- [ ] CPU
- [x] CUDA
- [ ] CoreML
- [ ] DirectML
- [ ] OpenVINO
- [ ] Other

What version of Roop are you using?

- [ ] 1.0.0
- [ ] 1.1.0
- [x] 1.2.0
- [ ] next

**Comment by henryruhs** [comment]
It works 100% ... I assume you manipulated the codebase

**Comment by blokzfordayz** [comment]
> It works 100% ... I assume you manipulated the codebase

It's happening to me as well and I did not manipulate the codebase at all.

**Comment by henryruhs** [comment]
Then it's probably a missing dependency like GPFGAN... if you would just not ignore the fact that Discord is better to solve issues like that
