### ISSUE TITLE
'FaceAnalysis' object has no attribute 'det_model'

### ISSUE THREAD

**Issue by thepvuguy** [s0md3v/roop#77]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "c:\Users\user\OneDrive\Área de Trabalho\Coding\deepai\roop\run.py", line 217, in <lambda>
    start_button = tk.Button(window, text="Start", bg="#f1c40f", relief="flat", borderwidth=0, highlightthickness=0, command=lambda: [save_file(), start()])    
  File "c:\Users\user\OneDrive\Área de Trabalho\Coding\deepai\roop\run.py", line 145, in start
    test_face = get_face(cv2.imread(args['source_img']))
  File "c:\Users\user\OneDrive\Área de Trabalho\Coding\deepai\roop\core\config.py", line 9, in get_face
    analysed = face_analyser.get(img_data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\app\face_analysis.py", line 57, in get
    bboxes, kpss = self.det_model.detect(img,
AttributeError: 'FaceAnalysis' object has no attribute 'det_model'

**Comment by TitasDas** [comment]
Whats the image filetype and dimensions of the image you are uploading?

**Comment by thepvuguy** [comment]
PNG and 367x604 px

**Comment by thepvuguy** [comment]
> Whats the image filetype and dimensions of the image you are uploading?

Any solution?

**Comment by thepvuguy** [comment]
For this solution just change the function GET of FaceAnalysis object:

`def get(self, img, max_num=0):
    bboxes, kpss = self.models['detection'].detect(img, max_num=max_num, metric='default')
    if bboxes.shape[0] == 0:
        return []
    ret = []
    for i in range(bboxes.shape[0]):
        bbox = bboxes[i, 0:4]
        det_score = bboxes[i, 4]
        kps = None
        if kpss is not None:
            kps = kpss[i]
        face = Face(bbox=bbox, kps=kps, det_score=det_score)
        for taskname, model in self.models.items():
            if taskname == 'detection':
                continue
            model.get(img, face)
        ret.append(face)
    return ret
`

**Comment by s0md3v** [comment]
This is a dependency issue which is out of scope for this project in the first place. Thanks @thepvuguy for the hack, I will close it now.
