### ISSUE TITLE
[Bug] Some frame are skipped

### ISSUE THREAD

**Issue by elanciel** [s0md3v/roop#779]
## Description

Face swapping  issue on a video :

Command line:  `python3 run.py --keep-frames --keep-fps --execution-provider=coreml --output-video-quality=30 --max-memory=6 --execution-threads=64 --frame-processor face_swapper face_enhancer `

GUI: The face swapping is working
CLI: Some frame are skipped

## Error

Paste the error or exception from your console:

The execution-threads is 64 : 
```
[ROOP.CORE] Creating temporary resources...
[ROOP.CORE] Extracting frames with 30.0 FPS...
[ROOP.FACE-SWAPPER] Progressing...
Processing:   1%|▏                             | 2/348 [00:06<16:00,  2.78s/frame, memory_usage=08.65GB, execution_providers=['CoreMLExecutionProvider'], execution_threads=64]Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
Processing:   2%|▋                             | 8/348 [00:16<33:22,  5.89s/frame, memory_usage=09.29GB, execution_providers=['CoreMLExecutionProvider'], execution_threads=64]inswapper-shape: [1, 3, 128, 128]
Processing: 100%|████████████████████████████| 348/348 [00:57<00:00,  6.08frame/s, memory_usage=10.24GB, execution_providers=['CoreMLExecutionProvider'], execution_threads=64]
[ROOP.FACE-ENHANCER] Progressing...
Processing:   7%|██                           | 24/348 [00:13<02:42,  2.00frame/s, memory_usage=10.28GB, execution_providers=['CoreMLExecutionProvider'], execution_threads=64]

```
Turn the execution-threads to 1: same issue
 
```
[ROOP.CORE] Creating temporary resources...
[ROOP.CORE] Extracting frames with 30.0 FPS...
[ROOP.FACE-SWAPPER] Progressing...
Processing:   0%|                                                                                                                                   | 0/348 [00:00<?, ?frame/s]Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Processing: 100%|█████████████████████████████| 348/348 [01:38<00:00,  3.53frame/s, memory_usage=04.14GB, execution_providers=['CoreMLExecutionProvider'], execution_threads=1]


```

Something not working well on the processing loop

## Details

What operating system are you using?

- [ ] Windows 
- [x] MacOS (Apple Silicon)
- [ ] MacOS (Apple Legacy)
- [ ] Linux
- [ ] Linux in WSL

What execution provider are you using?

- [ ] CPU
- [ ] CUDA
- [x] CoreML
- [ ] DirectML
- [ ] OpenVINO
- [ ] Other

What version of Roop are you using?

- [ ] 1.0.0
- [ ] 1.1.0
- [x] 1.2.0
- [x] next

**Comment by henryruhs** [comment]
I wonder that 64 threads don't throw memory exceptions, but usually that is the case and will cause the described issue. Other than that, use a higher `--similar-face-distance` like `1.5` to match different face angles.

GitHub issues are not a good place to help, you can join our Discord.
