### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by renkchina** [s0md3v/roop#787]
## Description

When I select it the following effect occurs, the ears and eyebrows are misaligned and the quality of the drawing is not good.

## Error

Paste the error or exception from your console:

```

```

## Details
![image](https://github.com/s0md3v/roop/assets/17176354/7f3a421a-eca1-4697-8470-965c7e01d0a2)

What operating system are you using?

- [ v] Windows 
- [ ] MacOS (Apple Silicon)
- [ ] MacOS (Apple Legacy)
- [ ] Linux
- [ ] Linux in WSL

What execution provider are you using?

- [v ] CPU
- [ ] CUDA
- [ ] CoreML
- [ ] DirectML
- [ ] OpenVINO
- [ ] Other

What version of Roop are you using?

- [ ] 1.0.0
- [ ] 1.1.0
- [ ] 1.2.0
- [ ] 1.3.0
- [ v] 1.3.1
- [ ] next

**Comment by henryruhs** [comment]
The third party model does not support sunglasses
