### ISSUE TITLE
performance issue face recognition

### ISSUE THREAD

**Issue by roycho87** [s0md3v/roop#79]
there seems to be issues when objects are interacting with or in front of the face. the gif example in the <> code second shows a woman's hand going in front of her face so i'm guessing the coding should fix this. is there a likely issue or is this a limit of the software?

Is there intention of integrating an alpha mask feature in the future? that would be amazing and far beyond anything i know of currently

**Comment by TitasDas** [comment]
Yes this is an issue I identified as well. @s0md3v can we make a note of this and add this to our **_ToDo_** feature list , will circle back to it. I think this is worth solving for along with the other features that are there.

**Comment by wagesj45** [comment]
It also seemed to break when no faces are detected in the frame.

**Comment by s0md3v** [comment]
@wagesj45 that was fixed yesterday. It will now just tell you that no faces were found.

**Comment by henryruhs** [comment]
Reopen if issue is not solved
