### ISSUE TITLE
[Installation] Fail to install

### ISSUE THREAD

**Issue by ZionTLV** [s0md3v/roop#791]
Hello,

After I tried multiple time, using different installation method, I always got the same when it comes to set up dependencies:

It looks like it install everythin but at the very end I always go this:

ERROR: Cannot install -r requirements.txt (line 15), -r requirements.txt (line 20), -r requirements.txt (line 4), -r requirements.txt (line 5), -r requirements.txt (line 6) and numpy==1.23.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.23.5
    opencv-python 4.8.0.74 depends on numpy>=1.21.2; python_version >= "3.10"
    opencv-python 4.8.0.74 depends on numpy>=1.23.5; python_version >= "3.11"
    opencv-python 4.8.0.74 depends on numpy>=1.17.0; python_version >= "3.7"
    opencv-python 4.8.0.74 depends on numpy>=1.17.3; python_version >= "3.8"
    opencv-python 4.8.0.74 depends on numpy>=1.19.3; python_version >= "3.9"
    onnx 1.14.0 depends on numpy
    insightface 0.7.3 depends on numpy
    torchvision 0.15.2+cu118 depends on numpy
    onnxruntime-gpu 1.15.1 depends on numpy>=1.24.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

What would you suggest me to do? 

thank you

**Comment by henryruhs** [comment]
Python 3.10

**Comment by ZionTLV** [comment]
I should use Python3.10 , correct?
