### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by daarkwulf** [s0md3v/roop#793]
## Description

A concise description of the bug and how to reproduce it.

## Error

Paste the error or exception from your console:
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

Warning: PowerShell detected that you might be using a screen reader and has disabled PSReadLine for compatibility purposes. If you want to re-enable it, run 'Import-Module PSReadLine'.

Loading personal and system profiles took 3025ms.
-----------------------------------------
TroubleChute Roop One-Line Launcher
https://tc.ht/ & YouTube.com/TroubleChute
-----------------------------------------
Launching Roop...
usage: run.py [-h] [-s SOURCE_PATH] [-t TARGET_PATH] [-o OUTPUT_PATH]
              [--frame-processor FRAME_PROCESSOR [FRAME_PROCESSOR ...]] [--keep-fps] [--keep-frames] [--skip-audio]
              [--many-faces] [--reference-face-position REFERENCE_FACE_POSITION]
              [--reference-frame-number REFERENCE_FRAME_NUMBER] [--similar-face-distance SIMILAR_FACE_DISTANCE]
              [--temp-frame-format {jpg,png}] [--temp-frame-quality [0-100]]
              [--output-video-encoder {libx264,libx265,libvpx-vp9,h264_nvenc,hevc_nvenc}]
              [--output-video-quality [0-100]] [--max-memory MAX_MEMORY]
              [--execution-provider {tensorrt,cuda,cpu} [{tensorrt,cuda,cpu} ...]]
              [--execution-threads EXECUTION_THREADS] [-v]
run.py: error: unrecognized arguments: --gpu-vendor amd

--------------------------------
TroubleChute One-Line installer:
--------------------------------
(roop) PS E:\folder\roop>

```

```

## Details

What operating system are you using?

- [yes ] Windows 
- [ ] MacOS (Apple Silicon)
- [ ] MacOS (Apple Legacy)
- [ ] Linux
- [ ] Linux in WSL

What execution provider are you using?

- [m just new dont know much its normal useing after installing but cpu provider is showing ] CPU
- [ ] CUDA
- [ ] CoreML
- [ ] DirectML
- [ ] OpenVINO
- [ ] Other

What version of Roop are you using?

- [ ] 1.0.0
- [ ] 1.1.0
- [ ] 1.2.0
- [ ] 1.3.0
- [ ] 1.3.1
- [ yes latest version ] next

**Comment by henryruhs** [comment]
We don't support third party scripting... this is not a bug but false usage of the CLI

**Comment by henryruhs** [comment]
We don't support third party scripting... this is not a bug but false usage of the CLI

run.py: error: unrecognized arguments: --gpu-vendor amd

**Comment by daarkwulf** [comment]
ok also one more issue is that after choosing face and target the frame process run gud but then after going 100percent roop software got quit and only cmd be present 

and also not able to process longer video like 30sec it takes 1 hour to complete process

one more is that many times it only able to process further when i take blurry and pixelated video like of 360p but not like 480p or above and roop get close..

plz tell what to do

windows 10
ram 20gb
i3 7th gen

**Comment by henryruhs** [comment]
This is not a chat but a software issue tracker... we have Discord for that
