### ISSUE TITLE
[Bug] UI not showing

### ISSUE THREAD

**Issue by superbunny38** [s0md3v/roop#795]
## Description & Error & Details
Hello, I was trying to execute run.py file, but what happens is:
I get an empty UI popup, with nothing showing. However, there is no error showing in the terminal, and I have successfully installed the libraries as provided in requirement.txt file. I attach the screenshot below for better explanation :)

FYI, as suggested in https://github.com/s0md3v/roop/wiki/4.-Troubleshooting#blank-ui-under-macos,  I have ran `brew install python-tk@3.10` command with no error, but it still doesn't work and gives me an empty screen.

[Empty screen in UI popup]

<img width="606" alt="image" src="https://github.com/s0md3v/roop/assets/48243487/da780574-c4a0-4732-8e7e-e36b8cdd8e99">

What operating system are you using?

- [ ] Windows 
- [V] MacOS (Apple Silicon)
- [ ] MacOS (Apple Legacy)
- [ ] Linux
- [ ] Linux in WSL

What execution provider are you using?

- [V] CPU
- [ ] CUDA
- [ ] CoreML
- [ ] DirectML
- [ ] OpenVINO
- [ ] Other

What version of Roop are you using?

- [ ] 1.0.0
- [ ] 1.1.0
- [ ] 1.2.0
- [ ] 1.3.0
- [ V ] 1.3.1
- [ ] next

**Comment by henryruhs** [comment]
We know about this bug and documented it in our wiki under troubleshooting.

In case you are unable to fix it on your side, wait for the new Gradio UI that is web based.

**Comment by superbunny38** [comment]
Hello, thank you for your reply.
I had read your wiki content about trouble shooting, and the link attached to my initial issue is the content.
However, I was unable to resolve the issue.

**Comment by henryruhs** [comment]
Nothing more I can do now as this issue does not appear either on Linux or MacOS on my machines. I can offer you the early access to the new web UI in case you like to become a sponsor.

**Comment by superbunny38** [comment]
Fixed it by running codes without UI pop-up :)
