### ISSUE TITLE
File "inswapper_128.onnx" does not exist!

### ISSUE THREAD

**Issue by RemmyLee** [s0md3v/roop#80]
Running Linux.

The Buffalo zip doesn't seem to include this.

**Comment by s0md3v** [comment]
pip installhttps://github.com/s0md3v/roop#installation

**Comment by FrenchGithubUser** [comment]
I have the same issue, installed all the deps, also running on linux.

**Comment by MustafaAlahmid** [comment]
I have downloded the model from here:

**[Link to model ](https://drive.google.com/file/d/1krOLgjW2tAPaqV-Bw4YALz0xT5zlb5HF/view)**

put the file into ./roop/inswrapper_128.onnx

then 

`python run.py`

**Comment by FrenchGithubUser** [comment]
Thanks for your answer @MustafaAlahmid . However, can't this model be malicious ? Shouldn't it be linked in the official doc/readme ?

Also, it would be nice to know why it worked out of the box for some and not for us
