### ISSUE TITLE
 Why gpu has no performance benefit in image swap

### ISSUE THREAD

**Issue by Senna1960321** [s0md3v/roop#800]
What operating system are you using?

- [1] Windows 
- [ ] MacOS (Apple Silicon)
- [ ] MacOS (Apple Legacy)
- [ ] Linux
- [ ] Linux in WSL

What execution provider are you using?

- [1] CPU
- [1] CUDA
- [ ] CoreML
- [ ] DirectML
- [ ] OpenVINO
- [ ] Other

**Comment by henryruhs** [comment]
What do you expect me to answer to this question? With zero information...
