### ISSUE TITLE
REQUEST - having option to install on custom location

### ISSUE THREAD

**Issue by daarkwulf** [s0md3v/roop#803]
hi lord . hope u are doing great

so the issue is that after installing roop i thought it would take around 6gb space but i saw that it installed multiple software also which is necessary too like visual studio and stuff 
but i thought when roop asked in cmd about diff location i choose diff drive other than C drive.. still it only installed roop and resst in 
c drive. coz of which it full my c drive and its an issue for me. and pehaps for most..

my request is can u plz make or give an option or do some settings to install all the required files at specific locaation instead of C drive.. there has to be an option coz 
despite your hard work which is so respectable still we users have to compromise the space it taking in system vs the result we getting on roop.
its a fair deal i know but having custom location will be gift to us.. 
m ready to reinstall if u give us this option..

thanx lord again

**Comment by henryruhs** [comment]
You can install roop on whatever drive you prefer, just use venv... we gonna try to provide a installer in the future.

**Comment by daarkwulf** [comment]
But sir I tried on installing somewhere else and it did but my request is to install rest of necessary software like visual studios or pip etc also to roop drive not the c drive

**Comment by henryruhs** [comment]
Use venv, like I said.
