### ISSUE TITLE
conda for custom location (experiment base)

### ISSUE THREAD

**Issue by daarkwulf** [s0md3v/roop#807]
ok so due to our previous talk i manage to realease some of the space from c drive and now i made env as u told me 

now i installed miniconda at d drive and also acctivated it and installed visual build tools too.. 
when i ran the one liner installation at the stage of conda asking it stops and this error came 
..................................................................................................................................................................................................................

Do you want to install Roop in a Conda environment called 'roop'?
You'll need to use 'conda activate roop' before being able to use it?

Use Conda (y/n) [Default: y]: y
conda : The term 'conda' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At C:\Users\kamal\AppData\Local\Temp\Get-Python.tc.psm1:280 char:21
+             $null = conda init powershell
+                     ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundException
Downloading the latest required model (inswapper_128.onnx)
--> If this fails, manually download it: https://civitai.com/api/download/models/85159, and place it in 'F:\roop\roop'
[#7a38dc 0B/0B CN:1 DL:0B]conda : The term 'conda' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:142 char:5
+     conda deactivate
+     ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
conda : The term 'conda' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:145 char:5
+     conda activate roop
+     ~~~~~
There are more launch options you can add, such as max memory. Add these to the start powershell files. See here: https://github.com/s0md3v/roop#how-do-i-use-it
Launching Roop!
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.   

Try the new cross-platform PowerShell https://aka.ms/pscore6

Warning: PowerShell detected that you might be using a screen reader and has disabled PSReadLine for compatibility purposes. If you want to re-enable it, run 'Import-Module PSReadLine'.

& : The term 'C:\tools\miniconda3\Scripts\conda.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At F:\one drive\OneDrive\Documents\WindowsPowerShell\profile.ps1:4 char:4
+ (& "C:\tools\miniconda3\Scripts\conda.exe" "shell.powershell" "hook") ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\tools\miniconda3\Scripts\conda.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
-----------------------------------------
TroubleChute Roop One-Line Launcher      
https://tc.ht/ & YouTube.com/TroubleChute
-----------------------------------------
Launching Roop...

Conda seems to have moved, or was uninstalled. Checking for a new location.
Please note: If packages aren't installed, or the environment was deleted please run the one-line installer again.
Import-FunctionIfNotExists : The term 'Import-FunctionIfNotExists' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At F:\roop\roop\run-roop-amd.ps1:46 char:5
+     Import-FunctionIfNotExists -Command Get-UseConda -ScriptUri "Get- ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Import-FunctionIfNotExists:String) [], CommandNotFoundException    
    + FullyQualifiedErrorId : CommandNotFoundException
 
Get-CondaPath : The term 'Get-CondaPath' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
of the name, or if a path was included, verify that the path is correct and try again.
At F:\roop\roop\run-roop-amd.ps1:47 char:18
+     $condaPath = Get-CondaPath
+                  ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-CondaPath:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 

This likely means that the Conda environment was removed. Please run the one-line installer again.
Conda does not seem to be installed. Please consider running the one-line installer again.
......................................................................................................................................................................................................................

so  now my question is even if i ran code from activated env from powershell still it asking conda path.. does it say that i again have to install conda at c drive as usual way..??? 

there are some software like visual build tools and window kit  which needs to be instlled on c drive as they dont allow custom location but as per your advice i tried env mode still it not catching conda... 

or should i try installing python on d drive and then saying no to conda in installing 
does it will help me to install roop in d drive ??

any suggestion lord ??

**Comment by henryruhs** [comment]
Discord for help... do not open new issues that are installation or platform related. This is not a support chat, but a software issue tracker - related to the software and not your Windows that is not setup correct...
