### ISSUE TITLE
yes i did it - saved 12gb in c drive

### ISSUE THREAD

**Issue by daarkwulf** [s0md3v/roop#809]
henry bro i did it by env mode and i saved 12gb on c drive
also it was showing error in red which is shown below in pic but still it running normal as earlier 

this is to tell u that plz tag or pin it so that rest of new commers who dont know these coding stuff and just want roop as tool can save their disk in c drive .
if u say i can tell the procedure here...

in crux what i did was -
uninstall all the required software like visual build tools,python,conda
and reinstall the python and conda in d drive,, and visual build tools in c drive
with powershell and visual studio code editor made an environment in conda
and then run the iex (irm roop.tc.ht)
ofcourse it said that visual build tool is not installed (even it was already installed)
then it asked about conda using ,, i said no it went to package installing from pip cache of earlier 
and then it showed module not found..i again ran the code and then it succesfully installed.
then i ran the cpu only from desktop and this image below was the result 
it worked sucessfully

![2023-08-02 22_33_28-](https://github.com/s0md3v/roop/assets/140973129/b8eeefdf-c0bd-4fd2-949c-e4cf4b358d22)

error was this red lines..
![2023-08-02 22_22_08-Roop CPU-Only](https://github.com/s0md3v/roop/assets/140973129/671690e0-6457-4f3c-96b9-dd41d933f993)

**Comment by daarkwulf** [comment]
thanx for ur time u gave lot of concerned to me..thanx again.. !

**Comment by daarkwulf** [comment]
ok so (feeling little sad)
that now this error is coming
frame not found.. can u tell due to which component it casuing this issue ??


![2023-08-02 22_54_16-Issues · s0md3v_roop](https://github.com/s0md3v/roop/assets/140973129/65e3431a-6322-4415-a793-f96da1686ec9)

**Comment by daarkwulf** [comment]
yes it working... only few videos are capable to work in this... 
dont know what is the parametere of target videos to use ...

**Comment by henryruhs** [comment]
I said Discord... I reported you to GitHub
