### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by raut7218** [s0md3v/roop#816]
## Description

Swap face of human to cartoon image in real time on live cam with lips and eye sync

## Details

What execution provider are you using?

We need to implement live face swap of human face to cartoon image face
In real time on live camera with lips sync rest is same 
we are giving single input image of cartoon for overplay 
And in real time it's overplaying cartoon face on human face with lips sync

**Comment by henryruhs** [comment]
Sorry but we don't plan to support this.
