### ISSUE TITLE
[Feature Request] Multiple GPU / Select GPU

### ISSUE THREAD

**Issue by psykokwak-com** [s0md3v/roop#819]
## Description

It could be great have an option to select the GPU(s) we want to use in the CUDA context.

**Comment by henryruhs** [comment]
That is actual a good idea - we could extend the CLI arguments by `--device-id` and list available devices via choices.

**Comment by ooofest** [comment]
I just set

SET "CUDA_VISIBLE_DEVICES=1"

and it uses my second GPU.  So, perhaps Torch is picking this up automagically?

**Comment by henryruhs** [comment]
Roop is not only using torch... onnxruntime aswell. To make it right we need to have a CLI arguments and pass it to every library.

**Comment by henryruhs** [comment]
This issue is currently blocked as the `FaceAnalysis` by insightface does not respect the environment variables. In case there is no `ctx_id` passed it automatically falls back to CPU.

```
FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=roop.globals.execution_providers)
FACE_ANALYSER.prepare(ctx_id=0)
```

**Comment by psykokwak-com** [comment]
Hi,
@henryruhs you closed the ticket as completed.
Did you add the feature ? I don't see any commit about it.

**Comment by henryruhs** [comment]
Nope, it indeed has a different reason... I will announce it on Discord
