### ISSUE TITLE
Rename 'inswapper_128.onnx' in basic instructions

### ISSUE THREAD

**Issue by TitasDas** [s0md3v/roop#82]
Under the basic instructions , please rename the file in this [link ](https://civitai.com/models/80324?modelVersionId=85159) to  **_'inswapper_128.onnx'_** from **_'roopVideoFace_v10'_** otherwise it throws out an error - 

> File "inswapper_128.onnx" does not exist!

 and can be potentially confusing to newbies to this project. 

Also lets make this instruction a standalone instruction which lies outside the basic and gpu instruction in the readme because this is a necessary step for both.

**Comment by s0md3v** [comment]
Done.

**Comment by TitasDas** [comment]
That works.
