### ISSUE TITLE
no output and the cuda is invalid

### ISSUE THREAD

**Issue by guoguozhang** [s0md3v/roop#820]
## Description

I have run successfully, the video also says processing is complete, the result can not find the output video. And the processing is very slow, no gpu is used.
this is my code: python run.py -s test.jpeg -t 1.mp4 2.mp4 --execution-provider cuda

## Error

the output is like this

```
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
[ROOP.CORE] Creating temporary resources...
[ROOP.CORE] Extracting frames with 60.0 FPS...
[ROOP.FACE-SWAPPER] Progressing...
[ROOP.CORE] Creating video with 60.0 FPS...
[ROOP.CORE] Restoring audio...
[ROOP.CORE] Cleaning temporary resources...
[ROOP.CORE] Processing to video succeed!
```

## Details

What operating system are you using?

- [ ] Windows 
- [ ] MacOS (Apple Silicon)
- [ ] MacOS (Apple Legacy)
- [x] Linux
- [ ] Linux in WSL

What execution provider are you using?

- [ ] CPU
- [x] CUDA
- [ ] CoreML
- [ ] DirectML
- [ ] OpenVINO
- [ ] Other

What version of Roop are you using?

- [ ] 1.0.0
- [ ] 1.1.0
- [ ] 1.2.0
- [ ] 1.3.0
- [x] 1.3.1
- [ ] 1.3.2
- [ ] next

**Comment by henryruhs** [comment]
Not a bug

**Comment by guoguozhang** [comment]
？

**Comment by guoguozhang** [comment]
How should I solve this problem？

**Comment by guoguozhang** [comment]
python run.py -s test.jpeg -t 1.mp4 -o 2.mp4 --execution-provider cuda，this is the cmd.  my cmd is no problem, but no output
