### ISSUE TITLE
Using Face enhancer upscale value greater than 1 causes numpy error.

### ISSUE THREAD

**Issue by TusharAgey** [s0md3v/roop#821]
## Description

Numpy array conversion error occurs if upscale value in face enhancer is > 1 
Updated snippet of upscale value:

`            FACE_ENHANCER = GFPGANer(model_path=model_path, upscale=3, device=get_device())
`
## Error
```
~/roop/processors/frame/face_enhancer.py", line 79, in enhance_face
    temp_frame[start_y:end_y, start_x:end_x] = temp_face
ValueError: could not broadcast input array from shape (912,663,3) into shape (304,221,3)
```

This is after https://github.com/s0md3v/roop/commit/fe9b2bc8e58f958580961165d35dc5813055e81e#diff-90dbea14040ea406d47db50a77c28bd0446e04480ce5c482a8314b1796235968 Merge

## Details

What operating system are you using?

- [ ] Windows 
- [x] MacOS (Apple Silicon)
- [ ] MacOS (Apple Legacy)
- [ ] Linux
- [ ] Linux in WSL

What execution provider are you using?

- [ ] CPU
- [ ] CUDA
- [x] CoreML
- [ ] DirectML
- [ ] OpenVINO
- [ ] Other

What version of Roop are you using?

- [ ] 1.0.0
- [ ] 1.1.0
- [ ] 1.2.0
- [ ] 1.3.0
- [ ] 1.3.1
- [x] 1.3.2
- [ ] next

**Comment by henryruhs** [comment]
Don't touch code if you don't know what you are doing. And why do you open an issue here and not at the GFPGAN project?

**Comment by TusharAgey** [comment]
@henryruhs, the upscale value is a custom parameter. It should be allowed to be changed. If you think that must not to be done, I'm okay with current implementation.

**Comment by TusharAgey** [comment]
> Don't touch code if you don't know what you are doing. And why do you open an issue here and not at the GFPGAN project?

And this is not a GFPGAN related issue. The error occurs after GFPGAN has finished processing and we put back the face frame into the main frame.

**Comment by henryruhs** [comment]
Not planned
