### ISSUE TITLE
no output file

### ISSUE THREAD

**Issue by guoguozhang** [s0md3v/roop#825]
No video output despite multiple tries, I have put the image and video in the same folder but still no seeing any output video after the render finish. Pls advise. Thanks. you close the issue, but how can this problem be solved.

**Comment by guoguozhang** [comment]
https://github.com/s0md3v/roop/issues/820, this bug is close.

**Comment by guoguozhang** [comment]
I've seen a lot of people raise this issue, but it's been shut down

**Comment by henryruhs** [comment]
Stop opening new issues and read the docs instead.
