### ISSUE TITLE
i can not start roop ..need help

### ISSUE THREAD

**Issue by chemistiano** [s0md3v/roop#828]
(venv) E:\Deepface\roop>python run.py --keep-frames --keep-fps --core 1
Traceback (most recent call last):
  File "E:\Deepface\roop\run.py", line 3, in <module>
    from roop import core
  File "E:\Deepface\roop\roop\core.py", line 16, in <module>
    import onnxruntime
ModuleNotFoundError: No module named 'onnxruntime'

**Comment by beepony** [comment]
it seems like you don't install the  'onnxruntime', may be you can check this doc: https://roop-ai.gitbook.io/roop/installation/acceleration
