### ISSUE TITLE
Protect me from my stupidity -check for valid output path before executing

### ISSUE THREAD

**Issue by MantisTree** [s0md3v/roop#836]
Ran an entire batch of transforms overnight and they all appeared to run and failed with message "`[ROOP.CORE] Frames not found...`"

Turns out the output path specified in the `-o` parameter didn't exist. I had specified "c:\path\to\file\output.mp4" but that preceding path was invalid.

Save us from ourselves :D

Thanks for an amazing project!

**Comment by henryruhs** [comment]
Thanks for letting us know
