### ISSUE TITLE
run.py not launching

### ISSUE THREAD

**Issue by IHNIWhatImDoing** [s0md3v/roop#84]
It will show a cmd screen for a split second then close. This happens repeatedly without launching anything. 
I downloaded all the requirements as far as I know.

**Comment by s0md3v** [comment]
You aren't supposed to click on it like an exe.

**Comment by IHNIWhatImDoing** [comment]
Okay thank you. Sorry, I'm really new to this but I found it really interesting so I wanted to try it out. I'll keep looking into it.
