### ISSUE TITLE
cant use cuda

### ISSUE THREAD

**Issue by Zakabaka** [s0md3v/roop#842]
I know maybe some one report such an isuue before but I just could not find an answer.
I cant run it with cuda. Cuda 11.8 installed and cudnn 11.x also. but every time I start the run.py with cuda provider it gaves me an error, without it it works notmal but still sometime in video face is missed (blinking fake/original faces) I thought that with gpu it will be more efficient and better quality, At some videos where the person move his head the fake face just disappears or the face starts blinking by changing he fake face with original. I cant find why. Also it works for videos from (youtube shorts) but for a wide format. For example I cut the scene from moovie and would like to replace the face of person, the program gaves me an errors. 
Ill attach them later. 
please see attachment.
![Screenshot 2023-08-13 141844](https://github.com/s0md3v/roop/assets/83984191/b58bf91f-3183-44b0-a79b-65e280441bbb)

**Comment by henryruhs** [comment]
Discord!
