### ISSUE TITLE
-- output-video-quality option is not working.

### ISSUE THREAD

**Issue by Mr-Nobody-dey** [s0md3v/roop#844]
## Description

!python run.py --output-video-quality 50 --temp-frame-quality 50 -f snip1.jpg -t inp_01.mp4 -o op_01.mp4 --keep-frames --keep-fps --gpu

## Error

Paste the error or exception from your console:

```
Invalid options --output-video-quality 50 --temp-frame-quality 50
```

## Details

What operating system are you using?

colab

What execution provider are you using?

- [ ] CUDA

What version of Roop are you using?

- [ ] 1.3.2

**Comment by henryruhs** [comment]
U are using false arguments
