### ISSUE TITLE
Memory Error on Apple M2 pro Mac Mini

### ISSUE THREAD

**Issue by visherandro** [s0md3v/roop#846]
## Description

any video which were more than few seconds long, the memory of python instance is keep onincreasing untill it the OS throws an error mentioned below. Observerd the memory in Activity monitor. 

## Error

 /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

## Details

What operating system are you using?
MacOS (Apple Silicon)

What execution provider are you using?
- [x] CoreML

What version of Roop are you using?
- [x] 1.3.2
- [x] next

**Comment by henryruhs** [comment]
Yes the onnxruntime has a memory leak.

1. Leaked semaphore objects: https://roop-ai.gitbook.io/roop/troubleshooting#leaked-semaphore-objects
2. Use the fixed community wheels: https://github.com/cansik/onnxruntime-silicon/releases/tag/v1.14.2
