### ISSUE TITLE
Can it swap hair?

### ISSUE THREAD

**Issue by guijuzhejiang** [s0md3v/roop#847]
Thank you for your work. I tried using it and the face swap works great. I just noticed that the hair still retains the hair of the character in the original video, which looks a little strange, is it possible to replace it with the target character along with the hair?

**Comment by henryruhs** [comment]
Not yet... a talented developer could write a frame processor based on:

https://github.com/Taeu/Style-Your-Hair
https://stylegan-salon.github.io

due the extensibility of roop.
