### ISSUE TITLE
In next branch has a bug that set wrong value to keep_temp

### ISSUE THREAD

**Issue by tomtrije** [s0md3v/roop#848]
## Description

In next branch has a bug that set wrong value to keep_temp, the value been set to `roop.globals.keep_fps` but the true value must be `roop.globals.keep_temp`

## Error

Code detail here in `settings.py` file line `24`

```
KEEP_TEMP_CHECKBOX = gradio.Checkbox(
            label='KEEP TEMP',
            value=roop.globals.keep_fps
        )
```

## Details

What operating system are you using?

- [ ] Windows 

What execution provider are you using?

- [ ] CUDA

What version of Roop are you using?
- [ ] next

**Comment by henryruhs** [comment]
I fixed it... thanks for checking up on me. Enjoy the new version.
