### ISSUE TITLE
Program completely freeze the PC....

### ISSUE THREAD

**Issue by ZeroCool22** [s0md3v/roop#85]
Finally, after launching it with the GPU argument without errors, when i pres the start it runs, but after some seconds freeze the whole PC and don't have another option than restart it from the restart button.

**Are there some lines we can add to the script to limit the resources it uses?**

**PC Specs:**

-AMD Ryzen 5900x.
-GPU 1080 TI.
-32gb of RAM.

**Comment by henryruhs** [comment]
Does not give us helpful information to be honest. Until what point does it processed?

**Comment by zaazii** [comment]
My PC freezes too. Right before the pc freezes, the percentage of time the D disk is processing reaches %100. 
![Screenshot 2023-05-30 093909](https://github.com/s0md3v/roop/assets/134853680/cbfc986b-0c95-4d05-9a43-1c533c5d0e41)

**Comment by henryruhs** [comment]
Could you try https://github.com/s0md3v/roop/pulls please? Sounds like a possible version mismatch.

**Comment by screan** [comment]
same, two crashes so far. successfully installed and appeared to be running ok.

**Comment by zaazii** [comment]
I get:
AttributeError: module 'win32api' has no attribute 'SetProcessWorkingSetSize'

**Comment by ZeroCool22** [comment]
I didn't try it again, because i got a little scared lol, the second time i tried it, the PC "almost" _(the monitor screen went off and the lights of the mother flickered)_ rebooted itself after some seconds of the script running.

Also, the argument **--gpu** doesn't works, i could watch the CPU activity before the PC crash and use the CPU only, hitting peaks of **85 % usage** and a **TEMP of 81** Degrees.

**Comment by zaazii** [comment]
I see that you've changed the memory limit code so I tried the newest version but I am getting this error:
inswapper-shape: [1, 3, 128, 128]
File "inswapper_128.onnx" does not exist!

**Comment by henryruhs** [comment]
do you have that file actual laying in the root? otherwise please tweak the path in the code...

**Comment by zaazii** [comment]
I have downloaded the file and put in the insightface models folder. Now I am getting this:

inswapper-shape: [1, 3, 128, 128]
Traceback (most recent call last):
  File "D:\df\roop\run.py", line 17, in <module>
    from core.processor import process_video, process_img
  File "D:\df\roop\core\processor.py", line 5, in <module>
    from core.config import get_face
  File "D:\df\roop\core\config.py", line 4, in <module>
    face_analyser = insightface.app.FaceAnalysis(name='buffalo_l', providers=core.globals.providers)  File "C:\Users\amout\anaconda3\lib\site-packages\insightface\app\face_analysis.py", line 37, in __init__
    elif model.taskname not in self.models and (allowed_modules is None or model.taskname in allowed_modules):
AttributeError: 'INSwapper' object has no attribute 'taskname'

**Comment by 132world** [comment]
so if I want the app to only use 10 GB of Ram do I type it like this: 
--max-memory 10

**Comment by zaazii** [comment]
When I put it in the root folder it says inswapper_128 doesn't exist. When I put it in the buffalu folder it says 'INSwapper' object has no attribute 'taskname'.

**Comment by tonzak** [comment]
using "--cores X" greatly reduced (if not completely eliminated) any freezing and crashing
5900x + 32 gb RAM, I used --cores 6 and was able to at least use my browser at the same time

Did not know about "--max-memory X", but cores argument still uses 100% of CPU, yet RAM usage is limited.

**Comment by henryruhs** [comment]
@zaazii This issue is fixed in latest version.
@tonzak For CPU only you can try to reduce the cores via `--max-cores` flag
