### ISSUE TITLE
Apart from inswapper_128.onnx, are there any other pre-trained models for face swapping? Or is there a training course

### ISSUE THREAD

**Issue by kelepig** [s0md3v/roop#850]
## Description

A concise description of the bug and how to reproduce it.

## Error

Paste the error or exception from your console:

```

```

## Details

What operating system are you using?

- [ ] Windows 
- [ ] MacOS (Apple Silicon)
- [ ] MacOS (Apple Legacy)
- [ ] Linux
- [ ] Linux in WSL

What execution provider are you using?

- [ ] CPU
- [ ] CUDA
- [ ] CoreML
- [ ] DirectML
- [ ] OpenVINO
- [ ] Other

What version of Roop are you using?

- [ ] 1.0.0
- [ ] 1.1.0
- [ ] 1.2.0
- [ ] 1.3.0
- [ ] 1.3.1
- [ ] 1.3.2
- [ ] next

**Comment by henryruhs** [comment]
Nope
