### ISSUE TITLE
Issue in roop 1.3.2

### ISSUE THREAD

**Issue by kallu143** [s0md3v/roop#856]
When I click on start button then this show is in the last

[ROOP.CORE] Frames not found... 

How to solve this? Please help me 
![Untitled (2)_LI](https://github.com/s0md3v/roop/assets/141266942/82f95a87-60cc-4399-822f-ad8caa10682a)

**Comment by PhantomAyz** [comment]
had the same problem

i downloaded from the latest release and i have no issues now

**Comment by kallu143** [comment]
> had the same problem
> 
> i downloaded from the latest release and i have no issues now
I download latest version two times but same issue facing.

**Comment by alexdjonson** [comment]
Roop 1.3.2 latest. Git pull - already up to date.
Python 3.10.7
Visual Studion 17.7.1 - just installed. Python and C++ checkboxes when install
CUDNN v.8.9.4.25 added to path in Invironment variables
ffmpeg - latest, added to path in Invironment variables
CUDA toolkit v11.6
Additionaly installed ffmpeg from GitHub instruction: winget install -e --id Gyan.FFmpeg

REBOOTED I swear)

R9 5900HX, 16 GB RAM, RTX3060laptop with 6 GB

I think it's something wrong with ffmpeg.
![image](https://github.com/s0md3v/roop/assets/142660327/532db9fa-f4ae-49c1-a860-15d60789c306)
![image](https://github.com/s0md3v/roop/assets/142660327/64c205f0-7152-4311-adb3-784d755e90b1)

Then I deleted winget ffmpeg, transfered to C:\ffmpeg6\bin. PATH updated. Still error.

C:\Games\Roop_Diffusion\roop.github\examples>ffmpeg -i target.mp4 %04d.png
Video split into frames correctly
![image](https://github.com/s0md3v/roop/assets/142660327/031b32d3-ba7e-44b0-86b7-1926be70a6d6)

**Comment by kallu143** [comment]
> 
still error i dont know what to do?
![1](https://github.com/s0md3v/roop/assets/141266942/c4cafabb-998b-40d7-bed5-c4fc681309b2)

**Comment by alexdjonson** [comment]
Removed from code of utilities.py **_hwaccel_**  in this block:
def extract_frames(target_path: str, fps: float = 30) -> bool:
    temp_directory_path = get_temp_directory_path(target_path)
    temp_frame_quality = roop.globals.temp_frame_quality * 31 // 100
    **return run_ffmpeg([_'-hwaccel', 'auto',_ '-i', target_path, '-q:v', str(temp_frame_quality), '-pix_fmt', 'rgb24', '-vf', 'fps=' + str(fps), os.path.join(temp_directory_path, '%04d.' + roop.globals.temp_frame_format)])**

Now this line is:
return run_ffmpeg(['-i', target_path, '-q:v', str(temp_frame_quality), '-pix_fmt', 'rgb24', '-vf', 'fps=' + str(fps), os.path.join(temp_directory_path, '%04d.' + roop.globals.temp_frame_format)])

Worked for me

**Comment by kallu143** [comment]
> Removed from code of utilities.py **_hwaccel_** in this block: def extract_frames(target_path: str, fps: float = 30) -> bool: temp_directory_path = get_temp_directory_path(target_path) temp_frame_quality = roop.globals.temp_frame_quality * 31 // 100 **return run_ffmpeg([_'-hwaccel', 'auto',_ '-i', target_path, '-q:v', str(temp_frame_quality), '-pix_fmt', 'rgb24', '-vf', 'fps=' + str(fps), os.path.join(temp_directory_path, '%04d.' + roop.globals.temp_frame_format)])**
> 
> Now this line is: return run_ffmpeg(['-i', target_path, '-q:v', str(temp_frame_quality), '-pix_fmt', 'rgb24', '-vf', 'fps=' + str(fps), os.path.join(temp_directory_path, '%04d.' + roop.globals.temp_frame_format)])
> 
> Worked for me

Thank you so much bro. This code work for me also 😊😊🙏
