### ISSUE TITLE
What about Intel Arc ?

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [s0md3v/roop#86]
How can I use this software with Intel Arc ? Does it has support for Intel oneAPI ?
There's nothing in the doc about Intel Arc, would be nice to add it because right now I don't know at all how I'm supposed to use it with my Arc

**Comment by s0md3v** [comment]
Support exists. I will add instructions to the guide, thanks for the heads up!

https://onnxruntime.ai/docs/execution-providers/OpenVINO-ExecutionProvider.html
https://onnxruntime.ai/docs/execution-providers/oneDNN-ExecutionProvider.html
