### ISSUE TITLE
Anyone managed to get the Mac version to use CoreML?

### ISSUE THREAD

**Issue by kellemar** [s0md3v/roop#89]
I followed the instructions, but it still says it's using the CPU.

**Comment by ad-ops** [comment]
I did `pip install onnxruntime-coreml==0.13.1` and I hardcoded in the `run.py` to use `core.globals.providers = ['CoreMLExecutionProvider']`. This can most likely be improved but it was just for a quick test.

Ran in ~1 min (down from 1.5 min) on my MacBook Pro M1.

**Comment by s0md3v** [comment]
hey @ad-ops, can you check if output of following script includes `CoreMLExecutionProvider`?

```
import onnxruntime

print(onnxruntime.get_available_providers())
```

**Comment by ad-ops** [comment]
> 

['CoreMLExecutionProvider', 'CPUExecutionProvider'] so I think it will work fine.

**Comment by Maki9009** [comment]
> ```python
> import onnxruntime
> 
> print(onnxruntime.get_available_providers())
> ```
> 
> Prints:
> 
> `['CoreMLExecutionProvider', 'CPUExecutionProvider']`
do you have an available fork to use for this for CoreML?

**Comment by iatsiuk** [comment]
I simply use this command on my Mac M1 Pro:

```
python3 run.py --gpu-vendor apple
```

On my sample video, it reduces the duration from 60 minutes to about 10 minutes.
