### ISSUE TITLE
Onnxruntime has no attribute 'get_available_providers'

### ISSUE THREAD

**Issue by ESOCHI** [s0md3v/roop#90]
Windows 10, cpu install, running python run.py and stuck on following:

`C:\Windows\System32\roop>python run.py
Traceback (most recent call last):
  File "C:\Windows\System32\roop\run.py", line 5, in <module>
    import core.globals
  File "C:\Windows\System32\roop\core\globals.py", line 4, in <module>
    providers = onnxruntime.get_available_providers()
AttributeError: module 'onnxruntime' has no attribute 'get_available_providers'`

I've got https://github.com/microsoft/onnxruntime placed in roop and I believe all other dependencies are satisfied, is it possible I need to use a different version of onnx? I'm new to onnxruntime so very possible I'm missing something.

AMD 3900x cpu and 5600xt gpu

**Comment by s0md3v** [comment]
You are supposed to install it with `pip install -r requirements.txt`, not download it.

**Comment by ESOCHI** [comment]
Thank you for your reply!

I did originally via
`C:\WINDOWS\system32>cd roop && pip install -r requirements.txt`

However that gave me this
`C:\Windows\System32\roop>python run.py
Traceback (most recent call last):
  File "C:\Windows\System32\roop\run.py", line 5, in <module>
    import core.globals
  File "C:\Windows\System32\roop\core\globals.py", line 1, in <module>
    import onnxruntime
ModuleNotFoundError: No module named 'onnxruntime'`

So then I ran this in roop
`git clone https://github.com/microsoft/onnxruntime`

which got me to the "Onnxruntime has no attribute 'get_available_providers'"
`C:\Windows\System32\roop>python run.py
Traceback (most recent call last):
  File "C:\Windows\System32\roop\run.py", line 5, in <module>
    import core.globals
  File "C:\Windows\System32\roop\core\globals.py", line 4, in <module>
    providers = onnxruntime.get_available_providers()
AttributeError: module 'onnxruntime' has no attribute 'get_available_providers'`

When running 'pip install -r requirements.txt' at this point, I get only "Requirements already satisfied" as expected.

Looking further, I found this https://github.com/microsoft/onnxruntime/issues/11907 which mentioned a different onnxruntime, so I ran that instead.
`pip install onnxruntime-gpu`

Now the gui pops up after running python run.py
Ran a quick img2img swap and it functioned well! Very satisfying.
