### ISSUE TITLE
I keep getting "The save file operation failed to connect to the open and save panel service"-I am on Mac and have tried reinstalling ffmpeg. But still occurs.

### ISSUE THREAD

**Issue by jmsquis** [s0md3v/roop#93]

**Comment by s0md3v** [comment]
Try restarting your device. closing this issue because its a duplicate

**Comment by egoslaw** [comment]
same

**Comment by Pawandeep-prog** [comment]
@egoslaw @jmsquis 
I am also on Mac m1, that same happened with me, I reinstalled ffmpeg, via brew, then again that error occurred, 

but you just have to press `okay` button several time (about 2-3 times) and in terminal you will see the progress starts. and everything will work fine.
