### ISSUE TITLE
error with "onnxruntime"

### ISSUE THREAD

**Issue by sandiks** [s0md3v/roop#94]
import onnxruntime
ModuleNotFoundError: No module named 'onnxruntime'

**Comment by s0md3v** [comment]
install it then

**Comment by nosy-b** [comment]
Same on Mac. Any idea @s0md3v  ? Thanks :)

**Comment by nosy-b** [comment]
A simple pip install onnxruntime did the job   :)

**Comment by henryruhs** [comment]
RTFM

**Comment by sandiks** [comment]
i installed with pip install -r requiments.txt
