### ISSUE TITLE
Output deleted

### ISSUE THREAD

**Issue by wanderjones** [s0md3v/roop#96]
Runs fine, and I can see the individual frames in the folder but at the end the folder and the output are deleted.

**Comment by s0md3v** [comment]
Yes, that's supposed to happen unless you use the "keep frames" option. Are you saying that the output video OUTSIDE the frames folder is deleted too?

**Comment by tomasalonsorehor** [comment]
yes that happened to me too..

**Comment by macnversion** [comment]
output.mp4 is inside frames dir now on mac m1

**Comment by StanislavAlexandrov** [comment]
In my case, the new output directory isn't being created, and the file 'output.mp4' gets deleted.

**Comment by nosy-b** [comment]
Same here, I could see it's processing and looks incredible :). But it deletes the output at the end before I can watch the whole video :)

**Comment by nosy-b** [comment]
'Keep frames" doesn't keep them on mac m2

**Comment by wanderjones** [comment]
Yeah, the output is being put in the frames folder.

**Comment by StanislavAlexandrov** [comment]
Created a pull request #113 
Works for me (M1 13.4)

**Comment by s0md3v** [comment]
Can you check if the issue still exists with the latest change?

CC: @wanderjones @nosy-b @macnversion

**Comment by wanderjones** [comment]
Getting a traceback error related to Tkinter now.

**Comment by s0md3v** [comment]
Can you please post your terminal output? I don't have a Mac to test. @wanderjones

**Comment by macnversion** [comment]
> Can you check if the issue still exists with the latest change?
> 
> CC: @wanderjones @nosy-b @macnversion

    args['output_file'] = rreplace(args['target_path'], "/", "/swapped-", 1) if "/" in target_path else "swapped-"+target_path
UnboundLocalError: local variable 'target_path' referenced before assignment

**Comment by adithya-s-sekhar** [comment]
Can confirm #issuecomment-1568527678 happens when used in cli on wsl too. Only gui works.

**Comment by MesumRaza** [comment]
> Yes, that's supposed to happen unless you use the "keep frames" option. Are you saying that the output video OUTSIDE the frames folder is deleted too?

I said the same, but issue was deleted, neverthless its fixed, also the CWD should be output by default, on colab it was sending to root folder.

**Comment by jmp909** [comment]
"Keep Frames" checkbox isn't working (Windows 11) when running with `python run.py --gpu`

specifying `--keep-frames` on command line (ie `python run.py --gpu --keep-frames) does work though after the GUI launches, but note the box isn't pre-ticked in this case

**Comment by Pawandeep-prog** [comment]
quick solution I found is just goto core>utils.py>add_audio() function there just comment last 4 lines 
`
#if not os.path.isfile(save_to):
#       shutil.move(output_dir + f"/output.mp4", save_to)
#  if not keep_frames:
#        shutil.rmtree(output_dir)
`

then your output video will be at the folder named with your input video :)

**Comment by henryruhs** [comment]
We fixed that `target_path` been undefined. Is is resolved now?

**Comment by jmp909** [comment]
I would add the following:

```
if(args["keep_frames"]):
    frames_checkbox.select()
```
maybe there's a shorthand way. otherwise if you launch with `--keep-frames` and then tick the box it will toggle it to false currently

**Comment by henryruhs** [comment]
please send a PR
